;;; AUTO GENERATED FILE
;;; generated by: gen_mos6502 -u -C 65816 -o gen_w65c816.asm
      CPU 65816
      BRK
      ORA  ($02,X)
      COP  #3
      ORA  $04,S
      TSB  $05
      ORA  $06
      ASL  $07
      ORA  [$08]
      PHP
      ORA  #10
      ASL  A
      PHD
      TSB  >$000D
      ORA  >$000E
      ASL  >$000F
      ORA  >>$001110
      BPL  *+$13
      BPL  *-$23
      BPL  *
      ORA  ($12),Y
      ORA  ($13)
      ORA  ($14,S),Y
      TRB  $15
      ORA  $16,X
      ASL  $17,X
      ORA  [$18],Y
      CLC
      ORA  >$001A,Y
      ORA  $0100,Y
      INC  A
      TCS
      TRB  >$001D
      ORA  >$001E,X
      ASL  >$001F,X
      ORA  >>$002120,X
      JSR  >$0021
      JSR  $0100
      AND  ($22,X)
      JSL  >>$002423
      JSL  $010023
      AND  $24,S
      BIT  $25
      AND  $26
      ROL  $27
      AND  [$28]
      PLP
      AND  #$2A
      ROL  A
      PLD
      BIT  >$002D
      AND  >$002E
      ROL  >$002F
      AND  >>$003130
      BMI  *+$33
      BMI  *-$79
      BMI  *
      AND  ($32),Y
      AND  ($33)
      AND  ($34,S),Y
      BIT  $35,X
      AND  $36,X
      ROL  $37,X
      AND  [$38],Y
      SEC
      AND  >$003A,Y
      AND  $0100,Y
      DEC  A
      TSC
      BIT  >$003D,X
      AND  >$003E,X
      ROL  >$003F,X
      AND  >>$004140,X
      RTI
      EOR  ($42,X)
      EOR  $44,S
      MVP  $000000,$450000
      EOR  $46
      LSR  $47
      EOR  [$48]
      PHA
      EOR  #$4A
      LSR  A
      PHK
      JMP  >$004D
      JMP  $0100
      EOR  >$004E
      LSR  >$004F
      EOR  >>$005150
      BVC  *+$53
      BVC  *-$7E
      BVC  *
      EOR  ($52),Y
      EOR  ($53)
      EOR  ($54,S),Y
      MVN  $000000,$550000
      EOR  $56,X
      LSR  $57,X
      EOR  [$58],Y
      CLI
      EOR  >$005A,Y
      EOR  $0100,Y
      PHY
      TCD
      JMP  >>$005E5D
      EOR  >$005E,X
      LSR  >$005F,X
      EOR  >>$006160,X
      RTS
      ADC  ($62,X)
      PER  *+$0066
      ADC  $64,S
      STZ  $65
      ADC  $66
      ROR  $67
      ADC  [$68]
      PLA
      ADC  #$6A
      ROR  A
      RTL
      JMP  (>$006D)
      JMP  ($0100)
      ADC  >$006E
      ROR  >$006F
      ADC  >>$007170
      BVS  *+$73
      BVS  *-$7E
      BVS  *
      ADC  ($72),Y
      ADC  ($73)
      ADC  ($74,S),Y
      STZ  $75,X
      ADC  $76,X
      ROR  $77,X
      ADC  [$78],Y
      SEI
      ADC  >$007A,Y
      ADC  $0100,Y
      PLY
      TDC
      JMP  (>$007D,X)
      JMP  ($0100,X)
      ADC  >$007E,X
      ROR  >$007F,X
      ADC  >>$008180,X
      BRA  *-$7D
      BRA  *
      BRA  *+1
      STA  ($82,X)
      BRL  *+$0086
      STA  $84,S
      STY  $85
      STA  $86
      STX  $87
      STA  [$88]
      DEY
      BIT  #$8A
      TXA
      PHB
      STY  >$008D
      STA  >$008E
      STX  >$008F
      STA  >>$009190
      BCC  *-$6D
      BCC  *
      BCC  *+1
      STA  ($92),Y
      STA  ($93)
      STA  ($94,S),Y
      STY  $95,X
      STA  $96,X
      STX  $97,Y
      STA  [$98],Y
      TYA
      STA  >$009A,Y
      STA  $0100,Y
      TXS
      TXY
      STZ  >$009D
      STA  >$009E,X
      STZ  >$009F,X
      STA  >>$00A1A0,X
      LDY  #$A1
      LDA  ($A2,X)
      LDX  #$A3
      LDA  $A4,S
      LDY  $A5
      LDA  $A6
      LDX  $A7
      LDA  [$A8]
      TAY
      LDA  #$AA
      TAX
      PLB
      LDY  >$00AD
      LDA  >$00AE
      LDX  >$00AF
      LDA  >>$00B1B0
      BCS  *-$4D
      BCS  *
      BCS  *+1
      LDA  ($B2),Y
      LDA  ($B3)
      LDA  ($B4,S),Y
      LDY  $B5,X
      LDA  $B6,X
      LDX  $B7,Y
      LDA  [$B8],Y
      CLV
      LDA  >$00BA,Y
      LDA  $0100,Y
      TSX
      TYX
      LDY  >$00BD,X
      LDA  >$00BE,X
      LDX  >$00BF,Y
      LDA  >>$00C1C0,X
      CPY  #$C1
      CMP  ($C2,X)
      REP  #$C3
      CMP  $C4,S
      CPY  $C5
      CMP  $C6
      DEC  $C7
      CMP  [$C8]
      INY
      CMP  #$CA
      DEX
      WAI
      CPY  >$00CD
      CMP  >$00CE
      DEC  >$00CF
      CMP  >>$00D1D0
      BNE  *-$2D
      BNE  *
      BNE  *+1
      CMP  ($D2),Y
      CMP  ($D3)
      CMP  ($D4,S),Y
      PEI  ($D5)
      CMP  $D6,X
      DEC  $D7,X
      CMP  [$D8],Y
      CLD
      CMP  >$00DA,Y
      CMP  $0100,Y
      PHX
      STP
      JMP  [>$00DD]
      JMP  [$0100]
      CMP  >$00DE,X
      DEC  >$00DF,X
      CMP  >>$00E1E0,X
      CPX  #$E1
      SBC  ($E2,X)
      SEP  #$E3
      SBC  $E4,S
      CPX  $E5
      SBC  $E6
      INC  $E7
      SBC  [$E8]
      INX
      SBC  #$EA
      NOP
      XBA
      CPX  >$00ED
      SBC  >$00EE
      INC  >$00EF
      SBC  >>$00F1F0
      BEQ  *-13
      BEQ  *
      BEQ  *+1
      SBC  ($F2),Y
      SBC  ($F3)
      SBC  ($F4,S),Y
      PEA  >$00F5
      PEA  $0100
      SBC  $F6,X
      INC  $F7,X
      SBC  [$F8],Y
      SED
      SBC  >$00FA,Y
      SBC  $0100,Y
      PLX
      XCE
      JSR  (>$00FD,X)
      JSR  ($0100,X)
      SBC  >$00FE,X
      INC  >$00FF,X
