;;; AUTO GENERATED FILE
;;; generated by: gen_ins8060 -u -C ins8060 -o gen_ins8060.asm

      HALT
      XAE
      CCL
      SCL
      DINT
      IEN
      CSA
      CAS
      NOP
      SIO
      SR
      SRL
      RR
      RRL
      XPAL PC
      XPAL P1
      XPAH PC
      XPAH P1
      XPPC PC
      XPPC P1
      LDE
      ANE
      ORE
      XRE
      DAE
      ADE
      CAE
      DLY  0x90
      JMP  0x0FB0
      JMP  E(PC)
      JMP  0x0FA4
      JMP  -110(P1)
      JMP  E(P1)
      JMP  -127(P1)
      JMP  E(P2)
      JMP  -127(P2)
      JMP  E(P3)
      JMP  -127(P3)
      JP   0x0FC8
      JP   E(PC)
      JP   0x0FB8
      JP   -106(P1)
      JP   E(P1)
      JP   -127(P1)
      JP   E(P2)
      JP   -127(P2)
      JP   E(P3)
      JP   -127(P3)
      JZ   0x0FE0
      JZ   E(PC)
      JZ   0x0FCC
      JZ   -102(P1)
      JZ   E(P1)
      JZ   -127(P1)
      JZ   E(P2)
      JZ   -127(P2)
      JZ   E(P3)
      JZ   -127(P3)
      JNZ  0x0FF8
      JNZ  E(PC)
      JNZ  0x0FE0
      JNZ  -98(P1)
      JNZ  E(P1)
      JNZ  -127(P1)
      JNZ  E(P2)
      JNZ  -127(P2)
      JNZ  E(P3)
      JNZ  -127(P3)
      ILD  0x0017
      ILD  E(PC)
      ILD  0x0FF3
      ILD  -86(P1)
      ILD  E(P1)
      ILD  -127(P1)
      ILD  E(P2)
      ILD  -127(P2)
      ILD  E(P3)
      ILD  -127(P3)
      DLD  0x003B
      DLD  E(PC)
      DLD  0x0007
      DLD  -70(P1)
      DLD  E(P1)
      DLD  -127(P1)
      DLD  E(P2)
      DLD  -127(P2)
      DLD  E(P3)
      DLD  -127(P3)
      LD   0x0057
      LD   E(PC)
      LD   0x001B
      LD   -62(P1)
      LD   E(P1)
      LD   -127(P1)
      LD   E(P2)
      LD   -127(P2)
      LD   E(P3)
      LD   -127(P3)
      LDI  0xC5
      LD   @-58(P1)
      LD   @E(P1)
      LD   @-127(P1)
      LD   @E(P2)
      LD   @-127(P2)
      LD   @E(P3)
      LD   @-127(P3)
      ST   0x0083
      ST   E(PC)
      ST   0x003F
      ST   -54(P1)
      ST   E(P1)
      ST   -127(P1)
      ST   E(P2)
      ST   -127(P2)
      ST   E(P3)
      ST   -127(P3)
      ST   @-50(P1)
      ST   @E(P1)
      ST   @-127(P1)
      ST   @E(P2)
      ST   @-127(P2)
      ST   @E(P3)
      ST   @-127(P3)
      AND  0x00AD
      AND  E(PC)
      AND  0x0061
      AND  -46(P1)
      AND  E(P1)
      AND  -127(P1)
      AND  E(P2)
      AND  -127(P2)
      AND  E(P3)
      AND  -127(P3)
      ANI  0xD5
      AND  @-42(P1)
      AND  @E(P1)
      AND  @-127(P1)
      AND  @E(P2)
      AND  @-127(P2)
      AND  @E(P3)
      AND  @-127(P3)
      OR   0x00D9
      OR   E(PC)
      OR   0x0085
      OR   -38(P1)
      OR   E(P1)
      OR   -127(P1)
      OR   E(P2)
      OR   -127(P2)
      OR   E(P3)
      OR   -127(P3)
      ORI  0xDD
      OR   @-34(P1)
      OR   @E(P1)
      OR   @-127(P1)
      OR   @E(P2)
      OR   @-127(P2)
      OR   @E(P3)
      OR   @-127(P3)
      XOR  0x0105
      XOR  E(PC)
      XOR  0x00A9
      XOR  -30(P1)
      XOR  E(P1)
      XOR  -127(P1)
      XOR  E(P2)
      XOR  -127(P2)
      XOR  E(P3)
      XOR  -127(P3)
      XRI  0xE5
      XOR  @-26(P1)
      XOR  @E(P1)
      XOR  @-127(P1)
      XOR  @E(P2)
      XOR  @-127(P2)
      XOR  @E(P3)
      XOR  @-127(P3)
      DAD  0x0131
      DAD  E(PC)
      DAD  0x00CD
      DAD  -22(P1)
      DAD  E(P1)
      DAD  -127(P1)
      DAD  E(P2)
      DAD  -127(P2)
      DAD  E(P3)
      DAD  -127(P3)
      DAI  0xED
      DAD  @-18(P1)
      DAD  @E(P1)
      DAD  @-127(P1)
      DAD  @E(P2)
      DAD  @-127(P2)
      DAD  @E(P3)
      DAD  @-127(P3)
      ADD  0x015D
      ADD  E(PC)
      ADD  0x00F1
      ADD  -14(P1)
      ADD  E(P1)
      ADD  -127(P1)
      ADD  E(P2)
      ADD  -127(P2)
      ADD  E(P3)
      ADD  -127(P3)
      ADI  0xF5
      ADD  @-10(P1)
      ADD  @E(P1)
      ADD  @-127(P1)
      ADD  @E(P2)
      ADD  @-127(P2)
      ADD  @E(P3)
      ADD  @-127(P3)
      CAD  0x0189
      CAD  E(PC)
      CAD  0x0115
      CAD  -6(P1)
      CAD  E(P1)
      CAD  -127(P1)
      CAD  E(P2)
      CAD  -127(P2)
      CAD  E(P3)
      CAD  -127(P3)
      CAI  0xFD
      CAD  @-2(P1)
      CAD  @E(P1)
      CAD  @-127(P1)
      CAD  @E(P2)
      CAD  @-127(P2)
      CAD  @E(P3)
      CAD  @-127(P3)
