;;; AUTO GENERATED FILE
;;; generated by: gen_mos6502 -u -C W65C02S -o gen_w65c02s.asm -l gen_w65c02s.lst
      CPU  W65C02S
      ORG  $0200
      BRK
      ORA  ($02,X)
      TSB  $05
      ORA  $06
      ASL  $07
      RMB0 $08
      PHP
      ORA  #10
      ASL  A
      TSB  $0E0D
      TSB  >$000C
      ORA  $0F0E
      ORA  >$000D
      ASL  $100F
      ASL  >$000E
      BBR0 $10,*+20
      BBR0 $0F,*-125
      BBR0 $0F,*
      BPL  *+19
      BPL  *-126
      BPL  *
      ORA  ($12),Y
      ORA  ($13)
      TRB  $15
      ORA  $16,X
      ASL  $17,X
      RMB1 $18
      CLC
      ORA  $1B1A,Y
      ORA  >$0019,Y
      INC  A
      TRB  $1E1D
      TRB  >$001C
      ORA  $1F1E,X
      ORA  >$001D,X
      ASL  $201F,X
      ASL  >$001E,X
      BBR1 $20,*+36
      BBR1 $1F,*-125
      BBR1 $1F,*
      JSR  $2221
      JSR  >$0020
      AND  ($22,X)
      BIT  $25
      AND  $26
      ROL  $27
      RMB2 $28
      PLP
      AND  #$2A
      ROL  A
      BIT  $2E2D
      BIT  >$002C
      AND  $2F2E
      AND  >$002D
      ROL  $302F
      ROL  >$002E
      BBR2 $30,*+52
      BBR2 $2F,*-125
      BBR2 $2F,*
      BMI  *+51
      BMI  *-126
      BMI  *
      AND  ($32),Y
      AND  ($33)
      BIT  $35,X
      AND  $36,X
      ROL  $37,X
      RMB3 $38
      SEC
      AND  $3B3A,Y
      AND  >$0039,Y
      DEC  A
      BIT  $3E3D,X
      BIT  >$003C,X
      AND  $3F3E,X
      AND  >$003D,X
      ROL  $403F,X
      ROL  >$003E,X
      BBR3 $40,*+68
      BBR3 $3F,*-125
      BBR3 $3F,*
      RTI
      EOR  ($42,X)
      EOR  $46
      LSR  $47
      RMB4 $48
      PHA
      EOR  #$4A
      LSR  A
      JMP  $4E4D
      JMP  >$004C
      EOR  $4F4E
      EOR  >$004D
      LSR  $504F
      LSR  >$004E
      BBR4 $50,*+84
      BBR4 $4F,*-125
      BBR4 $4F,*
      BVC  *+83
      BVC  *-126
      BVC  *
      EOR  ($52),Y
      EOR  ($53)
      EOR  $56,X
      LSR  $57,X
      RMB5 $58
      CLI
      EOR  $5B5A,Y
      EOR  >$0059,Y
      PHY
      EOR  $5F5E,X
      EOR  >$005D,X
      LSR  $605F,X
      LSR  >$005E,X
      BBR5 $60,*+100
      BBR5 $5F,*-125
      BBR5 $5F,*
      RTS
      ADC  ($62,X)
      STZ  $65
      ADC  $66
      ROR  $67
      RMB6 $68
      PLA
      ADC  #$6A
      ROR  A
      JMP  ($6E6D)
      JMP  (>$006C)
      ADC  $6F6E
      ADC  >$006D
      ROR  $706F
      ROR  >$006E
      BBR6 $70,*+116
      BBR6 $6F,*-125
      BBR6 $6F,*
      BVS  *+115
      BVS  *-126
      BVS  *
      ADC  ($72),Y
      ADC  ($73)
      STZ  $75,X
      ADC  $76,X
      ROR  $77,X
      RMB7 $78
      SEI
      ADC  $7B7A,Y
      ADC  >$0079,Y
      PLY
      JMP  ($7E7D,X)
      JMP  (>$007C,X)
      ADC  $7F7E,X
      ADC  >$007D,X
      ROR  $807F,X
      ROR  >$007E,X
      BBR7 $80,*-124
      BBR7 $7F,*
      BBR7 $7F,*+1
      BRA  *-125
      BRA  *
      BRA  *+1
      STA  ($82,X)
      STY  $85
      STA  $86
      STX  $87
      SMB0 $88
      DEY
      BIT  #$8A
      TXA
      STY  $8E8D
      STY  >$008C
      STA  $8F8E
      STA  >$008D
      STX  $908F
      STX  >$008E
      BBS0 $90,*-108
      BBS0 $8F,*
      BBS0 $8F,*+1
      BCC  *-109
      BCC  *
      BCC  *+1
      STA  ($92),Y
      STA  ($93)
      STY  $95,X
      STA  $96,X
      STX  $97,Y
      SMB1 $98
      TYA
      STA  $9B9A,Y
      STA  >$0099,Y
      TXS
      STZ  $9E9D
      STZ  >$009C
      STA  $9F9E,X
      STA  >$009D,X
      STZ  $A09F,X
      STZ  >$009E,X
      BBS1 $A0,*-92
      BBS1 $9F,*
      BBS1 $9F,*+1
      LDY  #$A1
      LDA  ($A2,X)
      LDX  #$A3
      LDY  $A5
      LDA  $A6
      LDX  $A7
      SMB2 $A8
      TAY
      LDA  #$AA
      TAX
      LDY  $AEAD
      LDY  >$00AC
      LDA  $AFAE
      LDA  >$00AD
      LDX  $B0AF
      LDX  >$00AE
      BBS2 $B0,*-76
      BBS2 $AF,*
      BBS2 $AF,*+1
      BCS  *-77
      BCS  *
      BCS  *+1
      LDA  ($B2),Y
      LDA  ($B3)
      LDY  $B5,X
      LDA  $B6,X
      LDX  $B7,Y
      SMB3 $B8
      CLV
      LDA  $BBBA,Y
      LDA  >$00B9,Y
      TSX
      LDY  $BEBD,X
      LDY  >$00BC,X
      LDA  $BFBE,X
      LDA  >$00BD,X
      LDX  $C0BF,Y
      LDX  >$00BE,Y
      BBS3 $C0,*-60
      BBS3 $BF,*
      BBS3 $BF,*+1
      CPY  #$C1
      CMP  ($C2,X)
      CPY  $C5
      CMP  $C6
      DEC  $C7
      SMB4 $C8
      INY
      CMP  #$CA
      DEX
      WAI
      CPY  $CECD
      CPY  >$00CC
      CMP  $CFCE
      CMP  >$00CD
      DEC  $D0CF
      DEC  >$00CE
      BBS4 $D0,*-44
      BBS4 $CF,*
      BBS4 $CF,*+1
      BNE  *-45
      BNE  *
      BNE  *+1
      CMP  ($D2),Y
      CMP  ($D3)
      CMP  $D6,X
      DEC  $D7,X
      SMB5 $D8
      CLD
      CMP  $DBDA,Y
      CMP  >$00D9,Y
      PHX
      STP
      CMP  $DFDE,X
      CMP  >$00DD,X
      DEC  $E0DF,X
      DEC  >$00DE,X
      BBS5 $E0,*-28
      BBS5 $DF,*
      BBS5 $DF,*+1
      CPX  #$E1
      SBC  ($E2,X)
      CPX  $E5
      SBC  $E6
      INC  $E7
      SMB6 $E8
      INX
      SBC  #$EA
      NOP
      CPX  $EEED
      CPX  >$00EC
      SBC  $EFEE
      SBC  >$00ED
      INC  $F0EF
      INC  >$00EE
      BBS6 $F0,*-12
      BBS6 $EF,*
      BBS6 $EF,*+1
      BEQ  *-13
      BEQ  *
      BEQ  *+1
      SBC  ($F2),Y
      SBC  ($F3)
      SBC  $F6,X
      INC  $F7,X
      SMB7 $F8
      SED
      SBC  $FBFA,Y
      SBC  >$00F9,Y
      PLX
      SBC  $FFFE,X
      SBC  >$00FD,X
      INC  >$00FF,X
      INC  $FFFE,X
      BBS7 $00,*+4
      BBS7 $FF,*-125
      BBS7 $FF,*
