;;; AUTO GENERATED FILE
;;; generated by: gen_mc6800 -u -C 6800 -o gen_mc6800.asm
      CPU 6800
      NOP
      TAP
      TPA
      INX
      DEX
      CLV
      SEV
      CLC
      SEC
      CLI
      SEI
      SBA
      CBA
      TAB
      TBA
      DAA
      ABA
      BRA   *+$0023
      BRA   *-$007E
      BRA   *
      BHI   *+$0025
      BHI   *-$007E
      BHI   *
      BLS   *+$0026
      BLS   *-$007E
      BLS   *
      BHS   *+$0027
      BHS   *-$007E
      BHS   *
      BLO   *+$0028
      BLO   *-$007E
      BLO   *
      BNE   *+$0029
      BNE   *-$007E
      BNE   *
      BEQ   *+$002A
      BEQ   *-$007E
      BEQ   *
      BVC   *+$002B
      BVC   *-$007E
      BVC   *
      BVS   *+$002C
      BVS   *-$007E
      BVS   *
      BPL   *+$002D
      BPL   *-$007E
      BPL   *
      BMI   *+$002E
      BMI   *-$007E
      BMI   *
      BGE   *+$002F
      BGE   *-$007E
      BGE   *
      BLT   *+$0030
      BLT   *-$007E
      BLT   *
      BGT   *+$0031
      BGT   *-$007E
      BGT   *
      BLE   *+$0032
      BLE   *-$007E
      BLE   *
      TSX
      INS
      PULA
      PULB
      DES
      TXS
      PSHA
      PSHB
      RTS
      RTI
      WAI
      SWI
      NEGA
      COMA
      LSRA
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      INCA
      TSTA
      CLRA
      NEGB
      COMB
      LSRB
      RORB
      ASRB
      ASLB
      ROLB
      DECB
      INCB
      TSTB
      CLRB
      NEG   97,X
      COM   100,X
      LSR   101,X
      ROR   103,X
      ASR   104,X
      ASL   105,X
      ROL   106,X
      DEC   107,X
      INC   109,X
      TST   110,X
      JMP   111,X
      CLR   112,X
      NEG   >$0071
      NEG   $0100
      COM   >$0074
      COM   $0100
      LSR   >$0075
      LSR   $0100
      ROR   >$0077
      ROR   $0100
      ASR   >$0078
      ASR   $0100
      ASL   >$0079
      ASL   $0100
      ROL   >$007A
      ROL   $0100
      DEC   >$007B
      DEC   $0100
      INC   >$007D
      INC   $0100
      TST   >$007E
      TST   $0100
      JMP   >$007F
      JMP   $0100
      CLR   >$0080
      CLR   $0100
      SUBA  #$81
      CMPA  #$82
      SBCA  #$83
      ANDA  #$85
      BITA  #$86
      LDAA  #$87
      EORA  #$89
      ADCA  #$8A
      ORAA  #$8B
      ADDA  #$8C
      CPX   #$008D
      BSR   *-$0070
      BSR   *
      BSR   *+1
      LDS   #$008F
      SUBA  $91
      CMPA  $92
      SBCA  $93
      ANDA  $95
      BITA  $96
      LDAA  $97
      STAA  $98
      EORA  $99
      ADCA  $9A
      ORAA  $9B
      ADDA  $9C
      CPX   $9D
      LDS   $9F
      STS   $A0
      SUBA  161,X
      CMPA  162,X
      SBCA  163,X
      ANDA  165,X
      BITA  166,X
      LDAA  167,X
      STAA  168,X
      EORA  169,X
      ADCA  170,X
      ORAA  171,X
      ADDA  172,X
      CPX   173,X
      JSR   174,X
      LDS   175,X
      STS   176,X
      SUBA  >$00B1
      CMPA  >$00B2
      SBCA  >$00B3
      ANDA  >$00B5
      BITA  >$00B6
      LDAA  >$00B7
      STAA  >$00B8
      EORA  >$00B9
      ADCA  >$00BA
      ORAA  >$00BB
      ADDA  >$00BC
      CPX   >$00BD
      JSR   >$00BE
      JSR   $0100
      LDS   >$00BF
      STS   >$00C0
      SUBB  #$C1
      CMPB  #$C2
      SBCB  #$C3
      ANDB  #$C5
      BITB  #$C6
      LDAB  #$C7
      EORB  #$C9
      ADCB  #$CA
      ORAB  #$CB
      ADDB  #$CC
      LDX   #$00CF
      SUBB  $D1
      CMPB  $D2
      SBCB  $D3
      ANDB  $D5
      BITB  $D6
      LDAB  $D7
      STAB  $D8
      EORB  $D9
      ADCB  $DA
      ORAB  $DB
      ADDB  $DC
      LDX   $DF
      STX   $E0
      SUBB  225,X
      CMPB  226,X
      SBCB  227,X
      ANDB  229,X
      BITB  230,X
      LDAB  231,X
      STAB  232,X
      EORB  233,X
      ADCB  234,X
      ORAB  235,X
      ADDB  236,X
      LDX   239,X
      STX   240,X
      SUBB  >$00F1
      CMPB  >$00F2
      SBCB  >$00F3
      ANDB  >$00F5
      BITB  >$00F6
      LDAB  >$00F7
      STAB  >$00F8
      EORB  >$00F9
      ADCB  >$00FA
      ORAB  >$00FB
      ADDB  >$00FC
      LDX   >$00FF
