;;; AUTO GENERATED FILE
;;; generated by: gen_mos6502 -u -C 6502 -o gen_mos6502.asm -l gen_mos6502.lst
      CPU  6502
      ORG  $0200
      BRK
      ORA  ($02,X)
      ORA  $06
      ASL  $07
      PHP
      ORA  #10
      ASL  A
      ORA  $0F0E
      ORA  >$000D
      ASL  $100F
      ASL  >$000E
      BPL  *+19
      BPL  *-126
      BPL  *
      ORA  ($12),Y
      ORA  $16,X
      ASL  $17,X
      CLC
      ORA  $1B1A,Y
      ORA  >$0019,Y
      ORA  $1F1E,X
      ORA  >$001D,X
      ASL  $201F,X
      ASL  >$001E,X
      JSR  $2221
      JSR  >$0020
      AND  ($22,X)
      BIT  $25
      AND  $26
      ROL  $27
      PLP
      AND  #$2A
      ROL  A
      BIT  $2E2D
      BIT  >$002C
      AND  $2F2E
      AND  >$002D
      ROL  $302F
      ROL  >$002E
      BMI  *+51
      BMI  *-126
      BMI  *
      AND  ($32),Y
      AND  $36,X
      ROL  $37,X
      SEC
      AND  $3B3A,Y
      AND  >$0039,Y
      AND  $3F3E,X
      AND  >$003D,X
      ROL  $403F,X
      ROL  >$003E,X
      RTI
      EOR  ($42,X)
      EOR  $46
      LSR  $47
      PHA
      EOR  #$4A
      LSR  A
      JMP  $4E4D
      JMP  >$004C
      EOR  $4F4E
      EOR  >$004D
      LSR  $504F
      LSR  >$004E
      BVC  *+83
      BVC  *-126
      BVC  *
      EOR  ($52),Y
      EOR  $56,X
      LSR  $57,X
      CLI
      EOR  $5B5A,Y
      EOR  >$0059,Y
      EOR  $5F5E,X
      EOR  >$005D,X
      LSR  $605F,X
      LSR  >$005E,X
      RTS
      ADC  ($62,X)
      ADC  $66
      ROR  $67
      PLA
      ADC  #$6A
      ROR  A
      JMP  ($6E6D)
      JMP  (>$006C)
      ADC  $6F6E
      ADC  >$006D
      ROR  $706F
      ROR  >$006E
      BVS  *+115
      BVS  *-126
      BVS  *
      ADC  ($72),Y
      ADC  $76,X
      ROR  $77,X
      SEI
      ADC  $7B7A,Y
      ADC  >$0079,Y
      ADC  $7F7E,X
      ADC  >$007D,X
      ROR  $807F,X
      ROR  >$007E,X
      STA  ($82,X)
      STY  $85
      STA  $86
      STX  $87
      DEY
      TXA
      STY  $8E8D
      STY  >$008C
      STA  $8F8E
      STA  >$008D
      STX  $908F
      STX  >$008E
      BCC  *-109
      BCC  *
      BCC  *+1
      STA  ($92),Y
      STY  $95,X
      STA  $96,X
      STX  $97,Y
      TYA
      STA  $9B9A,Y
      STA  >$0099,Y
      TXS
      STA  $9F9E,X
      STA  >$009D,X
      LDY  #$A1
      LDA  ($A2,X)
      LDX  #$A3
      LDY  $A5
      LDA  $A6
      LDX  $A7
      TAY
      LDA  #$AA
      TAX
      LDY  $AEAD
      LDY  >$00AC
      LDA  $AFAE
      LDA  >$00AD
      LDX  $B0AF
      LDX  >$00AE
      BCS  *-77
      BCS  *
      BCS  *+1
      LDA  ($B2),Y
      LDY  $B5,X
      LDA  $B6,X
      LDX  $B7,Y
      CLV
      LDA  $BBBA,Y
      LDA  >$00B9,Y
      TSX
      LDY  $BEBD,X
      LDY  >$00BC,X
      LDA  $BFBE,X
      LDA  >$00BD,X
      LDX  $C0BF,Y
      LDX  >$00BE,Y
      CPY  #$C1
      CMP  ($C2,X)
      CPY  $C5
      CMP  $C6
      DEC  $C7
      INY
      CMP  #$CA
      DEX
      CPY  $CECD
      CPY  >$00CC
      CMP  $CFCE
      CMP  >$00CD
      DEC  $D0CF
      DEC  >$00CE
      BNE  *-45
      BNE  *
      BNE  *+1
      CMP  ($D2),Y
      CMP  $D6,X
      DEC  $D7,X
      CLD
      CMP  $DBDA,Y
      CMP  >$00D9,Y
      CMP  $DFDE,X
      CMP  >$00DD,X
      DEC  $E0DF,X
      DEC  >$00DE,X
      CPX  #$E1
      SBC  ($E2,X)
      CPX  $E5
      SBC  $E6
      INC  $E7
      INX
      SBC  #$EA
      NOP
      CPX  $EEED
      CPX  >$00EC
      SBC  $EFEE
      SBC  >$00ED
      INC  $F0EF
      INC  >$00EE
      BEQ  *-13
      BEQ  *
      BEQ  *+1
      SBC  ($F2),Y
      SBC  $F6,X
      INC  $F7,X
      SED
      SBC  $FBFA,Y
      SBC  >$00F9,Y
      SBC  $FFFE,X
      SBC  >$00FD,X
      INC  >$00FF,X
      INC  $FFFE,X
