;;; AUTO GENERATED FILE
;;; generated by: gen_cdp1802 -u -C 1802 -o gen_cdp1802.asm -l gen_cdp1802.lst
      CPU  1802
      ORG  0100H
      IDL
      LDN  1
      INC  0
      DEC  0
      BR   0131H
      BQ   0132H
      BZ   0133H
      BDF  0134H
      B1   0135H
      B2   0136H
      B3   0137H
      B4   0138H
      SKP
      BNQ  013AH
      BNZ  013BH
      BNF  013CH
      BN1  013DH
      BN2  013EH
      BN3  013FH
      BN4  0140H
      LDA  0
      STR  0
      IRX
      OUT  1
      INP  1
      RET
      DIS
      LDXA
      STXD
      ADC
      SDB
      SHRC
      SMB
      SAV
      MARK
      REQ
      SEQ
      ADCI 7DH
      SDBI 7EH
      SHLC
      SMBI 80H
      GLO  0
      GHI  0
      PLO  0
      PHI  0
      LBR  00C1H
      LBQ  00C2H
      LBZ  00C3H
      LBDF 00C4H
      NOP
      LSNQ
      LSNZ
      LSNF
      LSKP
      LBNQ 00CAH
      LBNZ 00CBH
      LBNF 00CCH
      LSIE
      LSQ
      LSZ
      LSDF
      SEP  0
      SEX  0
      LDX
      OR
      AND
      XOR
      ADD
      SD
      SHR
      SM
      LDI  0F9H
      ORI  0FAH
      ANI  0FBH
      XRI  0FCH
      ADI  0FDH
      SDI  0FEH
      SHL
      SMI  0
