;;; AUTO GENERATED FILE
;;; generated by: gen_mc6800 -u -C 6301 -o gen_hd6301.asm -l gen_hd6301.lst
      CPU   6301
      ORG   $0100
      NOP
      LSRD
      ASLD
      TAP
      TPA
      INX
      DEX
      CLV
      SEV
      CLC
      SEC
      CLI
      SEI
      SBA
      CBA
      TAB
      TBA
      XGDX
      DAA
      SLP
      ABA
      BRA   *+35
      BRA   *-126
      BRA   *
      BRN   *+36
      BRN   *-126
      BRN   *
      BHI   *+37
      BHI   *-126
      BHI   *
      BLS   *+38
      BLS   *-126
      BLS   *
      BHS   *+39
      BHS   *-126
      BHS   *
      BLO   *+40
      BLO   *-126
      BLO   *
      BNE   *+41
      BNE   *-126
      BNE   *
      BEQ   *+42
      BEQ   *-126
      BEQ   *
      BVC   *+43
      BVC   *-126
      BVC   *
      BVS   *+44
      BVS   *-126
      BVS   *
      BPL   *+45
      BPL   *-126
      BPL   *
      BMI   *+46
      BMI   *-126
      BMI   *
      BGE   *+47
      BGE   *-126
      BGE   *
      BLT   *+48
      BLT   *-126
      BLT   *
      BGT   *+49
      BGT   *-126
      BGT   *
      BLE   *+50
      BLE   *-126
      BLE   *
      TSX
      INS
      PULA
      PULB
      DES
      TXS
      PSHA
      PSHB
      PULX
      RTS
      ABX
      RTI
      PSHX
      MUL
      WAI
      SWI
      NEGA
      COMA
      LSRA
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      INCA
      TSTA
      CLRA
      NEGB
      COMB
      LSRB
      RORB
      ASRB
      ASLB
      ROLB
      DECB
      INCB
      TSTB
      CLRB
      NEG   97,X
      AIM   #$62,99,X
      BCLR  7,0,X
      OIM   #$63,100,X
      BSET  7,0,X
      COM   100,X
      LSR   101,X
      EIM   #$66,103,X
      BTGL  7,0,X
      ROR   103,X
      ASR   104,X
      ASL   105,X
      ROL   106,X
      DEC   107,X
      TIM   #$6C,109,X
      BTST  7,0,X
      INC   109,X
      TST   110,X
      JMP   111,X
      CLR   112,X
      NEG   $7172
      NEG   >$0000
      AIM   #$72,$73
      BCLR  7,$00
      OIM   #$73,$74
      BSET  7,$00
      COM   $7475
      COM   >$0000
      LSR   $7576
      LSR   >$0000
      EIM   #$76,$77
      BTGL  7,$00
      ROR   $7778
      ROR   >$0000
      ASR   $7879
      ASR   >$0000
      ASL   $797A
      ASL   >$0000
      ROL   $7A7B
      ROL   >$0000
      DEC   $7B7C
      DEC   >$0000
      TIM   #$7C,$7D
      BTST  7,$00
      INC   $7D7E
      INC   >$0000
      TST   $7E7F
      TST   >$0000
      JMP   $7F80
      JMP   >$0000
      CLR   $8081
      CLR   >$0000
      SUBA  #$81
      CMPA  #$82
      SBCA  #$83
      SUBD  #$8485
      ANDA  #$85
      BITA  #$86
      LDAA  #$87
      EORA  #$89
      ADCA  #$8A
      ORAA  #$8B
      ADDA  #$8C
      CPX   #$8D8E
      BSR   *-112
      BSR   *
      BSR   *+1
      LDS   #$8F90
      SUBA  $91
      CMPA  $92
      SBCA  $93
      SUBD  $94
      ANDA  $95
      BITA  $96
      LDAA  $97
      STAA  $98
      EORA  $99
      ADCA  $9A
      ORAA  $9B
      ADDA  $9C
      CPX   $9D
      JSR   $9E
      LDS   $9F
      STS   $A0
      SUBA  161,X
      CMPA  162,X
      SBCA  163,X
      SUBD  164,X
      ANDA  165,X
      BITA  166,X
      LDAA  167,X
      STAA  168,X
      EORA  169,X
      ADCA  170,X
      ORAA  171,X
      ADDA  172,X
      CPX   173,X
      JSR   174,X
      LDS   175,X
      STS   176,X
      SUBA  $B1B2
      SUBA  >$0000
      CMPA  $B2B3
      CMPA  >$0000
      SBCA  $B3B4
      SBCA  >$0000
      SUBD  $B4B5
      SUBD  >$0000
      ANDA  $B5B6
      ANDA  >$0000
      BITA  $B6B7
      BITA  >$0000
      LDAA  $B7B8
      LDAA  >$0000
      STAA  $B8B9
      STAA  >$0000
      EORA  $B9BA
      EORA  >$0000
      ADCA  $BABB
      ADCA  >$0000
      ORAA  $BBBC
      ORAA  >$0000
      ADDA  $BCBD
      ADDA  >$0000
      CPX   $BDBE
      CPX   >$0000
      JSR   $BEBF
      JSR   >$0000
      LDS   $BFC0
      LDS   >$0000
      STS   $C0C1
      STS   >$0000
      SUBB  #$C1
      CMPB  #$C2
      SBCB  #$C3
      ADDD  #$C4C5
      ANDB  #$C5
      BITB  #$C6
      LDAB  #$C7
      EORB  #$C9
      ADCB  #$CA
      ORAB  #$CB
      ADDB  #$CC
      LDD   #$CDCE
      LDX   #$CFD0
      SUBB  $D1
      CMPB  $D2
      SBCB  $D3
      ADDD  $D4
      ANDB  $D5
      BITB  $D6
      LDAB  $D7
      STAB  $D8
      EORB  $D9
      ADCB  $DA
      ORAB  $DB
      ADDB  $DC
      LDD   $DD
      STD   $DE
      LDX   $DF
      STX   $E0
      SUBB  225,X
      CMPB  226,X
      SBCB  227,X
      ADDD  228,X
      ANDB  229,X
      BITB  230,X
      LDAB  231,X
      STAB  232,X
      EORB  233,X
      ADCB  234,X
      ORAB  235,X
      ADDB  236,X
      LDD   237,X
      STD   238,X
      LDX   239,X
      STX   240,X
      SUBB  $F1F2
      SUBB  >$0000
      CMPB  $F2F3
      CMPB  >$0000
      SBCB  $F3F4
      SBCB  >$0000
      ADDD  $F4F5
      ADDD  >$0000
      ANDB  $F5F6
      ANDB  >$0000
      BITB  $F6F7
      BITB  >$0000
      LDAB  $F7F8
      LDAB  >$0000
      STAB  $F8F9
      STAB  >$0000
      EORB  $F9FA
      EORB  >$0000
      ADCB  $FAFB
      ADCB  >$0000
      ORAB  $FBFC
      ORAB  >$0000
      ADDB  $FCFD
      ADDB  >$0000
      LDD   $FDFE
      LDD   >$0000
      STD   $FEFF
      STD   >$0000
      LDX   $FF00
      LDX   >$0000
      STX   $0101
      STX   >$0000
