;;; AUTO GENERATED FILE
;;; generated by: gen_cdp1802 -u -C cdp1802 -o gen_cdp1802.asm
      CPU 1802
      IDL
      LDN  1
      INC  0
      DEC  0
      BR   0031H
      BQ   0032H
      BZ   0033H
      BDF  0034H
      B1   0035H
      B2   0036H
      B3   0037H
      B4   0038H
      SKP
      BNQ  003AH
      BNZ  003BH
      BNF  003CH
      BN1  003DH
      BN2  003EH
      BN3  003FH
      BN4  0040H
      LDA  0
      STR  0
      IRX
      OUT  1
      INP  1
      RET
      DIS
      LDXA
      STXD
      ADC
      SDB
      SHRC
      SMB
      SAV
      MARK
      REQ
      SEQ
      ADCI 7DH
      SDBI 7EH
      SHLC
      SMBI 80H
      GLO  0
      GHI  0
      PLO  0
      PHI  0
      LBR  00C1H
      LBQ  00C2H
      LBZ  00C3H
      LBDF 00C4H
      NOP
      LSNQ
      LSNZ
      LSNF
      LSKP
      LBNQ 00CAH
      LBNZ 00CBH
      LBNF 00CCH
      LSIE
      LSQ
      LSZ
      LSDF
      SEP  0
      SEX  0
      LDX
      OR
      AND
      XOR
      ADD
      SD
      SHR
      SM
      LDI  0F9H
      ORI  0FAH
      ANI  0FBH
      XRI  0FCH
      ADI  0FDH
      SDI  0FEH
      SHL
      SMI  0
