# Copyright 2020 Tadashi G. Takaoka
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# GNU assembler rules

# PDP-11 targets.
#
# binutils 2.46.1's --target-help advertises -mt11/-mj11, but the option
# table in this build only contains the kd11/ka11/kb11 entries, so those
# flags are rejected. Pass each instruction-set extension explicitly per
# the J-11 / T-11 architecture handbooks until upstream lands the CPU
# aliases:
#   T-11: limited EIS (incl. RTT), MTPS/MFPS, MFPT
#   J-11: full EIS,  MTPS/MFPS, MFPT, SPL, CSM, TSTSET/WRTLCK
#          (-mmultiproc), and FP-11 floating point.
T11_FLAGS = -mno-extensions -mlimited-eis -mmxps -mmfpt
J11_FLAGS = -mno-extensions -meis -mmxps -mmfpt -mspl -mcsm -mmultiproc -mfpp

gas-%_t11.hex: %_t11.gas
	pdp11-aout-as $(T11_FLAGS) --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	pdp11-aout-ld --entry=0 -section-start=.text=0 -o $(^:.gas=.o) $(^:.gas=.p)
	pdp11-aout-objcopy -I a.out-pdp11 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	pdp11-aout-objdump -m pdp11 -D $(^:.gas=.hex) > $(^:.gas=.dis)

gas-%_j11.hex: %_j11.gas
	pdp11-aout-as $(J11_FLAGS) --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	pdp11-aout-ld --entry=0 -section-start=.text=0 -o $(^:.gas=.o) $(^:.gas=.p)
	pdp11-aout-objcopy -I a.out-pdp11 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	pdp11-aout-objdump -m pdp11 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# Z8001 target
gas-%_z8001.hex: %_z8001.gas
	z8k-coff-as --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	z8k-coff-ld -m z8001 --entry=0 -o $(^:.gas=.o) $(^:.gas=.p) \
		--section-start=text=0x010000 \
		--section-start=bss1=0x0A1234 \
		--section-start=bss2=0x0B5678
	z8k-coff-objcopy -I coff-z8k -O ihex $(^:.gas=.o) /dev/stdout \
		--adjust-section-vma .text=0x010000 \
	| tr -d '\015' > $(^:.gas=.hex)
	z8k-coff-objdump -m z8001 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# Z8002 target
gas-%_z8002.hex: %_z8002.gas
	z8k-coff-as --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	z8k-coff-ld -m z8002 --entry=0 -o $(^:.gas=.o) $(^:.gas=.p) \
		--section-start=text=0x1000 \
		--section-start=bss1=0x1234 \
		--section-start=bss2=0x5678
	z8k-coff-objcopy -I coff-z8k -O ihex $(^:.gas=.o) /dev/stdout \
		--adjust-section-vma .text=0x1000 \
	| tr -d '\015' > $(^:.gas=.hex)
	z8k-coff-objdump -m z8002 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# NS32032 target
gas-%_ns32032.hex: %_ns32032.gas
	ns32k-openbsd-as -m32032 --warn -o $(^:.gas=.o) -al=$(^:.gas=.lst) $^
	ns32k-openbsd-objcopy -I a.out-ns32k-netbsd -O ihex -j .text \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	ns32k-openbsd-objdump -m ns32k:32032 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8/300 target
gas-%_h8300.hex: %_h8300.gas
	h8300-elf-as --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8/300H target
gas-%_h8300h.hex: %_h8300h.gas
	h8300-elf-as -mach=h8300h --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300helf --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300h -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8/300H normal mode target
gas-%_h8300hn.hex: %_h8300hn.gas
	h8300-elf-as -mach=h8300hn --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300hnelf --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300h -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8/300H advanced mode target
gas-%_h8s2000.hex: %_h8s2000.gas
	h8300-elf-as -mach=h8300s --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300self --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300s -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8S/2000 normal mode target
gas-%_h8s2000n.hex: %_h8s2000n.gas
	h8300-elf-as -mach=h8300sn --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300snelf --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300s -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8S/2000 advanced mode target
gas-%_h8s2000.hex: %_h8s2000.gas
	h8300-elf-as -mach=h8300s --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300self --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300s -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8S/2600 normal mode target
gas-%_h8s2600n.hex: %_h8s2600n.gas
	h8300-elf-as -mach=h8300sn --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300snelf --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300s -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8S/2600 advanced mode target
gas-%_h8s2600.hex: %_h8s2600.gas
	h8300-elf-as -mach=h8300s --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	h8300-elf-ld -mh8300self --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	h8300-elf-objcopy -I elf32-h8300 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	h8300-elf-objdump -m h8300s -D $(^:.gas=.hex) > $(^:.gas=.dis)

# H8/500 family targets (h8500, h8520)
# h8500-hms-as (binutils 2.16.1) supports .include but rejects ';' as a
# comment character. The .gas wrapper uses cpp-style #include directives
# so that cpp can inline the .inc files into a single source; sed then
# strips ';...' comments and substitutes 'rte' with '.byte 0x0a' (RTE is
# missing from h8500-hms-as). See ~/gas_bugs_h8500.md.
define gas-h8500-rule
gas-%_$(1).hex: %_$(1).gas
	cpp -E -P -nostdinc -traditional -I . $$^ \
	  | sed -e 's/;.*$$$$//' -e 's/^\(\s*\)rte\s*$$$$/\1.byte 0x0a/' \
	    > $$(^:.gas=.s)
	h8500-hms-as --warn -o $$(^:.gas=.p) -als=$$(^:.gas=.lst) $$(^:.gas=.s)
	h8500-hms-ld --entry=0 -Ttext 0x0100 -o $$(^:.gas=.o) $$(^:.gas=.p)
	h8500-hms-objcopy -O ihex $$(^:.gas=.o) /dev/stdout \
	  | tr -d '\015' > $$(^:.gas=.hex)
	h8500-hms-objdump -m h8500 -D $$(^:.gas=.hex) > $$(^:.gas=.dis)
endef
$(eval $(call gas-h8500-rule,h8500))
$(eval $(call gas-h8500-rule,h8520))

# i8086 target
gas-%_i8086.hex: %_i8086.gas
	i386-elf-as -mtune=i8086 --warn -mnaked-reg -msyntax=intel \
		-mmnemonic=intel -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	i386-elf-ld --entry=0 -section-start=.text=0x1000 -o $(^:.gas=.o) $(^:.gas=.p)
	i386-elf-objcopy -I elf32-i386 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	i386-elf-objdump -m i8086 -M intel -D $(^:.gas=.hex) > $(^:.gas=.dis)

# i80186 target
gas-%_i80186.hex: %_i80186.gas
	i386-elf-as -mtune=i186 --warn -mnaked-reg -msyntax=intel \
		-mmnemonic=intel -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	i386-elf-ld --entry=0 -section-start=.text=0x1000 -o $(^:.gas=.o) $(^:.gas=.p)
	i386-elf-objcopy -I elf32-i386 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	i386-elf-objdump -m i8086 -M intel -D $(^:.gas=.hex) > $(^:.gas=.dis)

# i80286 target
gas-%_i80286.hex: %_i80286.gas
	i386-elf-as -mtune=i286 --warn -mnaked-reg -msyntax=intel \
		-mmnemonic=intel -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	i386-elf-ld --entry=0 -section-start=.text=0x1000 -o $(^:.gas=.o) $(^:.gas=.p)
	i386-elf-objcopy -I elf32-i386 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	i386-elf-objdump -m i8086 -M intel -D $(^:.gas=.hex) > $(^:.gas=.dis)

# MC68000 target
gas-%_mc68000.s28: %_mc68000.gas
	m68k-elf-as -m68000 -m68881 --warn --register-prefix-optional \
		--base-size-default-16 -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m68k-elf-ld --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m68k-elf-objcopy -I elf32-m68k -O srec --srec-len=16 \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s28)
	m68k-elf-objdump -m 68000 -D $(^:.gas=.s28) > $(^:.gas=.dis)

# MC68010 target
gas-%_mc68010.s28: %_mc68010.gas
	m68k-elf-as -m68010 -m68881 --warn --register-prefix-optional \
		--base-size-default-16 -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m68k-elf-ld --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m68k-elf-objcopy -I elf32-m68k -O srec --srec-len=16 \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s28)
	m68k-elf-objdump -m 68010 -D $(^:.gas=.s28) > $(^:.gas=.dis)

# MC68020 target
gas-%_mc68020.s37: %_mc68020.gas
	m68k-elf-as -m68020 -m68881 --warn --register-prefix-optional \
		--base-size-default-16 -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m68k-elf-ld --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m68k-elf-objcopy -I elf32-m68k -O srec --srec-len=16 \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	m68k-elf-objdump -m 68020 -D $(^:.gas=.s37) > $(^:.gas=.dis)

# MC68030 target
gas-%_mc68030.s37: %_mc68030.gas
	m68k-elf-as -m68030 -m68881 --warn --register-prefix-optional \
		--base-size-default-16 -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m68k-elf-ld --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m68k-elf-objcopy -I elf32-m68k -O srec --srec-len=16 \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	m68k-elf-objdump -m 68030 -D $(^:.gas=.s37) > $(^:.gas=.dis)

# MC68040 target
gas-%_mc68040.s37: %_mc68040.gas
	m68k-elf-as -m68040 --warn --register-prefix-optional \
		--base-size-default-16 -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m68k-elf-ld --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m68k-elf-objcopy -I elf32-m68k -O srec --srec-len=16 \
		--adjust-section-vma .text=0x10000 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	m68k-elf-objdump -m 68040 -D $(^:.gas=.s37) > $(^:.gas=.dis)

# MC68HC11 target
gas-%_mc68hc11.s19: %_mc68hc11.gas
	m6811-elf-as -m68hc11 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m6811-elf-ld -m m68hc11elf --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m6811-elf-objcopy -I elf32-m68hc11 -O srec --srec-len=16 \
	        --change-section-lma .text=0x0100 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s19)
	m6811-elf-objdump -m m68hc11 -D $(^:.gas=.s19) > $(^:.gas=.dis)

# MC68HC12 target
gas-%_mc68hc12.s19: %_mc68hc12.gas
	m6811-elf-as -m68hc12 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	m6811-elf-ld -m m68hc12elf --entry=0 -o $(^:.gas=.o) $(^:.gas=.p)
	m6811-elf-objcopy -I elf32-m68hc12 -O srec --srec-len=16 \
	        --change-section-lma .text=0x0100 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s19)
	m6811-elf-objdump -m m68hc12 -D $(^:.gas=.s19) > $(^:.gas=.dis)

# TMS320C30 target
gas-%_tms320c30.hex: %_tms320c30.gas
	tic4x-coff-as -mcpu=30 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	tic4x-coff-ld --entry=0 -section-start=.text=0x300 -o $(^:.gas=.o) $(^:.gas=.p)
	tic4x-coff-objcopy -I coff1-tic4x -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	tic4x-coff-objdump -m c30 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# TMS320C31 target
gas-%_tms320c31.hex: %_tms320c31.gas
	tic4x-coff-as -mcpu=31 --mrev=5 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	tic4x-coff-ld --entry=0 -section-start=.text=0x300 -o $(^:.gas=.o) $(^:.gas=.p)
	tic4x-coff-objcopy -I coff1-tic4x -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	tic4x-coff-objdump -m c31 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# TMS320C32 target
gas-%_tms320c32.hex: %_tms320c32.gas
	tic4x-coff-as -mcpu=32 --mrev=2 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	tic4x-coff-ld --entry=0 -section-start=.text=0x300 -o $(^:.gas=.o) $(^:.gas=.p)
	tic4x-coff-objcopy -I coff1-tic4x -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	tic4x-coff-objdump -m c32 -D $(^:.gas=.hex) > $(^:.gas=.dis)

# Z80 target
gas-%_z80.hex: %_z80.gas
	z80-elf-as -march=z80 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	z80-elf-ld --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	z80-elf-objcopy -I elf32-z80 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	z80-elf-objdump -mz80 -D $(^:.gas=.o) > $(^:.gas=.dis)

# Z180 target
gas-%_z180.hex: %_z180.gas
	z80-elf-as -march=z180 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	z80-elf-ld --entry=0 -section-start=.text=0x0100 -o $(^:.gas=.o) $(^:.gas=.p)
	z80-elf-objcopy -I elf32-z80 -O ihex $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.hex)
	z80-elf-objdump -mz180 -D $(^:.gas=.o) > $(^:.gas=.dis)

# SH-1 target
gas-%_sh1.s37: %_sh1.gas
	sh-elf-as --isa=sh --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	sh-elf-ld --entry=0 -section-start=.text=0x0000 -o $(^:.gas=.o) $(^:.gas=.p)
	sh-elf-objcopy -I elf32-sh -O srec --srec-len=16 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	sh-elf-objdump -m sh -D $(^:.gas=.s37) > $(^:.gas=.dis)

# SH-2 target
gas-%_sh2.s37: %_sh2.gas
	sh-elf-as --isa=sh2 --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	sh-elf-ld --entry=0 -section-start=.text=0x0000 -o $(^:.gas=.o) $(^:.gas=.p)
	sh-elf-objcopy -I elf32-sh -O srec --srec-len=16 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	sh-elf-objdump -m sh2 -D $(^:.gas=.s37) > $(^:.gas=.dis)

# SH-DSP target (SH-2 + DSP)
gas-%_shdsp.s37: %_shdsp.gas
	sh-elf-as --isa=sh-dsp --warn -o $(^:.gas=.p) -al=$(^:.gas=.lst) $^
	sh-elf-ld --entry=0 -section-start=.text=0x0000 -o $(^:.gas=.o) $(^:.gas=.p)
	sh-elf-objcopy -I elf32-sh -O srec --srec-len=16 $(^:.gas=.o) /dev/stdout \
	| tr -d '\015' > $(^:.gas=.s37)
	sh-elf-objdump -m sh-dsp -D $(^:.gas=.s37) > $(^:.gas=.dis)

# Local Variables:
# mode: makefile-gmake
# End:
# vim: set ft=make:
