;;; AUTO GENERATED FILE
;;; generated by: gen_tms9900 -u -C TMS9995 -o gen_tms9995.asm -l gen_tms9995.lst
      CPU   TMS9995
      ORG   0100H
      LST   R0
      LWP   R0
      DIVS  R0
      DIVS  *R0
      DIVS  @02A2H
      DIVS  @02A2H(R1)
      DIVS  *R0+
      MPYS  R0
      MPYS  *R0
      MPYS  @02E2H
      MPYS  @02E2H(R1)
      MPYS  *R0+
      LI    R0, 0301H
      AI    R0, 0321H
      ANDI  R0, 0341H
      ORI   R0, 0361H
      CI    R0, 0381H
      STWP  R0
      STST  R0
      LWPI  03E1H
      LIMI  0401H
      IDLE
      RSET
      RTWP
      CKON
      CKOF
      LREX
      BLWP  R0
      BLWP  *R0
      BLWP  @0522H
      BLWP  @0522H(R1)
      BLWP  *R0+
      B     R0
      B     *R0
      RT
      B     @0562H
      B     @0562H(R1)
      B     *R0+
      X     R0
      X     *R0
      X     @05A2H
      X     @05A2H(R1)
      X     *R0+
      CLR   R0
      CLR   *R0
      CLR   @05E2H
      CLR   @05E2H(R1)
      CLR   *R0+
      NEG   R0
      NEG   *R0
      NEG   @0622H
      NEG   @0622H(R1)
      NEG   *R0+
      INV   R0
      INV   *R0
      INV   @0662H
      INV   @0662H(R1)
      INV   *R0+
      INC   R0
      INC   *R0
      INC   @06A2H
      INC   @06A2H(R1)
      INC   *R0+
      INCT  R0
      INCT  *R0
      INCT  @06E2H
      INCT  @06E2H(R1)
      INCT  *R0+
      DEC   R0
      DEC   *R0
      DEC   @0722H
      DEC   @0722H(R1)
      DEC   *R0+
      DECT  R0
      DECT  *R0
      DECT  @0762H
      DECT  @0762H(R1)
      DECT  *R0+
      BL    R0
      BL    *R0
      BL    @07A2H
      BL    @07A2H(R1)
      BL    *R0+
      SWPB  R0
      SWPB  *R0
      SWPB  @07E2H
      SWPB  @07E2H(R1)
      SWPB  *R0+
      SETO  R0
      SETO  *R0
      SETO  @0822H
      SETO  @0822H(R1)
      SETO  *R0+
      ABS   R0
      ABS   *R0
      ABS   @0862H
      ABS   @0862H(R1)
      ABS   *R0+
      SRA   R0, R0
      SRA   R0, 1
      SRL   R0, R0
      SRL   R0, 1
      SLA   R0, R0
      SLA   R0, 1
      SRC   R0, R0
      SRC   R0, 1
      NOP
      JMP   $+4
      JLT   $+2
      JLE   $+2
      JEQ   $+2
      JHE   $+2
      JGT   $+2
      JNE   $+2
      JNC   $+2
      JOC   $+2
      JNO   $+2
      JL    $+2
      JH    $+2
      JOP   $+2
      SBO   0
      SBO   -128
      SBZ   0
      SBZ   -128
      TB    0
      TB    -128
      COC   R0, R0
      COC   *R0, R0
      COC   @2122H, R0
      COC   @2122H(R1), R0
      COC   *R0+, R0
      CZC   R0, R0
      CZC   *R0, R0
      CZC   @2522H, R0
      CZC   @2522H(R1), R0
      CZC   *R0+, R0
      XOR   R0, R0
      XOR   *R0, R0
      XOR   @2922H, R0
      XOR   @2922H(R1), R0
      XOR   *R0+, R0
      XOP   R0, 0
      XOP   *R0, 0
      XOP   @2D22H, 0
      XOP   @2D22H(R1), 0
      XOP   *R0+, 0
      LDCR  R0, 16
      LDCR  *R0, 16
      LDCR  @3122H, 16
      LDCR  @3122H(R1), 16
      LDCR  *R0+, 16
      STCR  R0, 16
      STCR  *R0, 16
      STCR  @3522H, 16
      STCR  @3522H(R1), 16
      STCR  *R0+, 16
      MPY   R0, R0
      MPY   *R0, R0
      MPY   @3922H, R0
      MPY   @3922H(R1), R0
      MPY   *R0+, R0
      DIV   R0, R0
      DIV   *R0, R0
      DIV   @3D22H, R0
      DIV   @3D22H(R1), R0
      DIV   *R0+, R0
      SZC   R0, R0
      SZC   *R0, R0
      SZC   @4122H, R0
      SZC   @4122H(R1), R0
      SZC   *R0+, R0
      SZC   R0, *R0
      SZC   *R0, *R0
      SZC   @4522H, *R0
      SZC   @4522H(R1), *R0
      SZC   *R0+, *R0
      SZC   R0, @4902H
      SZC   *R0, @4912H
      SZC   @4922H, @4A24H
      SZC   @4922H(R1), @4A24H
      SZC   *R0+, @4932H
      SZC   R0, @4941H(R1)
      SZC   *R0, @4951H(R1)
      SZC   @4962H, @4A63H(R1)
      SZC   @4962H(R1), @4A63H(R1)
      SZC   *R0+, @4971H(R1)
      SZC   R0, *R0+
      SZC   *R0, *R0+
      SZC   @4D22H, *R0+
      SZC   @4D22H(R1), *R0+
      SZC   *R0+, *R0+
      SZCB  R0, R0
      SZCB  *R0, R0
      SZCB  @5121H, R0
      SZCB  @5122H(R1), R0
      SZCB  *R0+, R0
      SZCB  R0, *R0
      SZCB  *R0, *R0
      SZCB  @5521H, *R0
      SZCB  @5522H(R1), *R0
      SZCB  *R0+, *R0
      SZCB  R0, @5901H
      SZCB  *R0, @5911H
      SZCB  @5921H, @5A22H
      SZCB  @5922H(R1), @5A23H
      SZCB  *R0+, @5931H
      SZCB  R0, @5941H(R1)
      SZCB  *R0, @5951H(R1)
      SZCB  @5961H, @5A62H(R1)
      SZCB  @5962H(R1), @5A63H(R1)
      SZCB  *R0+, @5971H(R1)
      SZCB  R0, *R0+
      SZCB  *R0, *R0+
      SZCB  @5D21H, *R0+
      SZCB  @5D22H(R1), *R0+
      SZCB  *R0+, *R0+
      S     R0, R0
      S     *R0, R0
      S     @6122H, R0
      S     @6122H(R1), R0
      S     *R0+, R0
      S     R0, *R0
      S     *R0, *R0
      S     @6522H, *R0
      S     @6522H(R1), *R0
      S     *R0+, *R0
      S     R0, @6902H
      S     *R0, @6912H
      S     @6922H, @6A24H
      S     @6922H(R1), @6A24H
      S     *R0+, @6932H
      S     R0, @6941H(R1)
      S     *R0, @6951H(R1)
      S     @6962H, @6A63H(R1)
      S     @6962H(R1), @6A63H(R1)
      S     *R0+, @6971H(R1)
      S     R0, *R0+
      S     *R0, *R0+
      S     @6D22H, *R0+
      S     @6D22H(R1), *R0+
      S     *R0+, *R0+
      SB    R0, R0
      SB    *R0, R0
      SB    @7121H, R0
      SB    @7122H(R1), R0
      SB    *R0+, R0
      SB    R0, *R0
      SB    *R0, *R0
      SB    @7521H, *R0
      SB    @7522H(R1), *R0
      SB    *R0+, *R0
      SB    R0, @7901H
      SB    *R0, @7911H
      SB    @7921H, @7A22H
      SB    @7922H(R1), @7A23H
      SB    *R0+, @7931H
      SB    R0, @7941H(R1)
      SB    *R0, @7951H(R1)
      SB    @7961H, @7A62H(R1)
      SB    @7962H(R1), @7A63H(R1)
      SB    *R0+, @7971H(R1)
      SB    R0, *R0+
      SB    *R0, *R0+
      SB    @7D21H, *R0+
      SB    @7D22H(R1), *R0+
      SB    *R0+, *R0+
      C     R0, R0
      C     *R0, R0
      C     @8122H, R0
      C     @8122H(R1), R0
      C     *R0+, R0
      C     R0, *R0
      C     *R0, *R0
      C     @8522H, *R0
      C     @8522H(R1), *R0
      C     *R0+, *R0
      C     R0, @8902H
      C     *R0, @8912H
      C     @8922H, @8A24H
      C     @8922H(R1), @8A24H
      C     *R0+, @8932H
      C     R0, @8941H(R1)
      C     *R0, @8951H(R1)
      C     @8962H, @8A63H(R1)
      C     @8962H(R1), @8A63H(R1)
      C     *R0+, @8971H(R1)
      C     R0, *R0+
      C     *R0, *R0+
      C     @8D22H, *R0+
      C     @8D22H(R1), *R0+
      C     *R0+, *R0+
      CB    R0, R0
      CB    *R0, R0
      CB    @9121H, R0
      CB    @9122H(R1), R0
      CB    *R0+, R0
      CB    R0, *R0
      CB    *R0, *R0
      CB    @9521H, *R0
      CB    @9522H(R1), *R0
      CB    *R0+, *R0
      CB    R0, @9901H
      CB    *R0, @9911H
      CB    @9921H, @9A22H
      CB    @9922H(R1), @9A23H
      CB    *R0+, @9931H
      CB    R0, @9941H(R1)
      CB    *R0, @9951H(R1)
      CB    @9961H, @9A62H(R1)
      CB    @9962H(R1), @9A63H(R1)
      CB    *R0+, @9971H(R1)
      CB    R0, *R0+
      CB    *R0, *R0+
      CB    @9D21H, *R0+
      CB    @9D22H(R1), *R0+
      CB    *R0+, *R0+
      A     R0, R0
      A     *R0, R0
      A     @0A122H, R0
      A     @0A122H(R1), R0
      A     *R0+, R0
      A     R0, *R0
      A     *R0, *R0
      A     @0A522H, *R0
      A     @0A522H(R1), *R0
      A     *R0+, *R0
      A     R0, @0A902H
      A     *R0, @0A912H
      A     @0A922H, @0AA24H
      A     @0A922H(R1), @0AA24H
      A     *R0+, @0A932H
      A     R0, @0A941H(R1)
      A     *R0, @0A951H(R1)
      A     @0A962H, @0AA63H(R1)
      A     @0A962H(R1), @0AA63H(R1)
      A     *R0+, @0A971H(R1)
      A     R0, *R0+
      A     *R0, *R0+
      A     @0AD22H, *R0+
      A     @0AD22H(R1), *R0+
      A     *R0+, *R0+
      AB    R0, R0
      AB    *R0, R0
      AB    @0B121H, R0
      AB    @0B122H(R1), R0
      AB    *R0+, R0
      AB    R0, *R0
      AB    *R0, *R0
      AB    @0B521H, *R0
      AB    @0B522H(R1), *R0
      AB    *R0+, *R0
      AB    R0, @0B901H
      AB    *R0, @0B911H
      AB    @0B921H, @0BA22H
      AB    @0B922H(R1), @0BA23H
      AB    *R0+, @0B931H
      AB    R0, @0B941H(R1)
      AB    *R0, @0B951H(R1)
      AB    @0B961H, @0BA62H(R1)
      AB    @0B962H(R1), @0BA63H(R1)
      AB    *R0+, @0B971H(R1)
      AB    R0, *R0+
      AB    *R0, *R0+
      AB    @0BD21H, *R0+
      AB    @0BD22H(R1), *R0+
      AB    *R0+, *R0+
      MOV   R0, R0
      MOV   *R0, R0
      MOV   @0C122H, R0
      MOV   @0C122H(R1), R0
      MOV   *R0+, R0
      MOV   R0, *R0
      MOV   *R0, *R0
      MOV   @0C522H, *R0
      MOV   @0C522H(R1), *R0
      MOV   *R0+, *R0
      MOV   R0, @0C902H
      MOV   *R0, @0C912H
      MOV   @0C922H, @0CA24H
      MOV   @0C922H(R1), @0CA24H
      MOV   *R0+, @0C932H
      MOV   R0, @0C941H(R1)
      MOV   *R0, @0C951H(R1)
      MOV   @0C962H, @0CA63H(R1)
      MOV   @0C962H(R1), @0CA63H(R1)
      MOV   *R0+, @0C971H(R1)
      MOV   R0, *R0+
      MOV   *R0, *R0+
      MOV   @0CD22H, *R0+
      MOV   @0CD22H(R1), *R0+
      MOV   *R0+, *R0+
      MOVB  R0, R0
      MOVB  *R0, R0
      MOVB  @0D121H, R0
      MOVB  @0D122H(R1), R0
      MOVB  *R0+, R0
      MOVB  R0, *R0
      MOVB  *R0, *R0
      MOVB  @0D521H, *R0
      MOVB  @0D522H(R1), *R0
      MOVB  *R0+, *R0
      MOVB  R0, @0D901H
      MOVB  *R0, @0D911H
      MOVB  @0D921H, @0DA22H
      MOVB  @0D922H(R1), @0DA23H
      MOVB  *R0+, @0D931H
      MOVB  R0, @0D941H(R1)
      MOVB  *R0, @0D951H(R1)
      MOVB  @0D961H, @0DA62H(R1)
      MOVB  @0D962H(R1), @0DA63H(R1)
      MOVB  *R0+, @0D971H(R1)
      MOVB  R0, *R0+
      MOVB  *R0, *R0+
      MOVB  @0DD21H, *R0+
      MOVB  @0DD22H(R1), *R0+
      MOVB  *R0+, *R0+
      SOC   R0, R0
      SOC   *R0, R0
      SOC   @0E122H, R0
      SOC   @0E122H(R1), R0
      SOC   *R0+, R0
      SOC   R0, *R0
      SOC   *R0, *R0
      SOC   @0E522H, *R0
      SOC   @0E522H(R1), *R0
      SOC   *R0+, *R0
      SOC   R0, @0E902H
      SOC   *R0, @0E912H
      SOC   @0E922H, @0EA24H
      SOC   @0E922H(R1), @0EA24H
      SOC   *R0+, @0E932H
      SOC   R0, @0E941H(R1)
      SOC   *R0, @0E951H(R1)
      SOC   @0E962H, @0EA63H(R1)
      SOC   @0E962H(R1), @0EA63H(R1)
      SOC   *R0+, @0E971H(R1)
      SOC   R0, *R0+
      SOC   *R0, *R0+
      SOC   @0ED22H, *R0+
      SOC   @0ED22H(R1), *R0+
      SOC   *R0+, *R0+
      SOCB  R0, R0
      SOCB  *R0, R0
      SOCB  @0F121H, R0
      SOCB  @0F122H(R1), R0
      SOCB  *R0+, R0
      SOCB  R0, *R0
      SOCB  *R0, *R0
      SOCB  @0F521H, *R0
      SOCB  @0F522H(R1), *R0
      SOCB  *R0+, *R0
      SOCB  R0, @0F901H
      SOCB  *R0, @0F911H
      SOCB  @0F921H, @0FA22H
      SOCB  @0F922H(R1), @0FA23H
      SOCB  *R0+, @0F931H
      SOCB  R0, @0F941H(R1)
      SOCB  *R0, @0F951H(R1)
      SOCB  @0F961H, @0FA62H(R1)
      SOCB  @0F962H(R1), @0FA63H(R1)
      SOCB  *R0+, @0F971H(R1)
      SOCB  R0, *R0+
      SOCB  *R0, *R0+
      SOCB  @0FD21H, *R0+
      SOCB  @0FD22H(R1), *R0+
      SOCB  *R0+, *R0+
