;;; AUTO GENERATED FILE
;;; generated by: gen_mos6502 -u -C 65C02 -o gen_r65c02.asm -l gen_r65c02.lst
      CPU   65C02
      ORG   $0200
      BRK
      ORA   ($02,X)
      TSB   $05
      ORA   $06
      ASL   $07
      RMB0  $08
      PHP
      ORA   #10
      ASL   A
      TSB   $0E0D
      TSB   >$000D
      ORA   $0F0E
      ORA   >$000E
      ASL   $100F
      ASL   >$000F
      BBR0  $10,*+20
      BBR0  $10,*-125
      BBR0  $10,*
      BPL   *+19
      BPL   *-126
      BPL   *
      ORA   ($12),Y
      ORA   ($13)
      TRB   $15
      ORA   $16,X
      ASL   $17,X
      RMB1  $18
      CLC
      ORA   $1B1A,Y
      ORA   >$001A,Y
      INC   A
      TRB   $1E1D
      TRB   >$001D
      ORA   $1F1E,X
      ORA   >$001E,X
      ASL   $201F,X
      ASL   >$001F,X
      BBR1  $20,*+36
      BBR1  $20,*-125
      BBR1  $20,*
      JSR   $2221
      JSR   >$0021
      AND   ($22,X)
      BIT   $25
      AND   $26
      ROL   $27
      RMB2  $28
      PLP
      AND   #$2A
      ROL   A
      BIT   $2E2D
      BIT   >$002D
      AND   $2F2E
      AND   >$002E
      ROL   $302F
      ROL   >$002F
      BBR2  $30,*+52
      BBR2  $30,*-125
      BBR2  $30,*
      BMI   *+51
      BMI   *-126
      BMI   *
      AND   ($32),Y
      AND   ($33)
      BIT   $35,X
      AND   $36,X
      ROL   $37,X
      RMB3  $38
      SEC
      AND   $3B3A,Y
      AND   >$003A,Y
      DEC   A
      BIT   $3E3D,X
      BIT   >$003D,X
      AND   $3F3E,X
      AND   >$003E,X
      ROL   $403F,X
      ROL   >$003F,X
      BBR3  $40,*+68
      BBR3  $40,*-125
      BBR3  $40,*
      RTI
      EOR   ($42,X)
      EOR   $46
      LSR   $47
      RMB4  $48
      PHA
      EOR   #$4A
      LSR   A
      JMP   $4E4D
      JMP   >$004D
      EOR   $4F4E
      EOR   >$004E
      LSR   $504F
      LSR   >$004F
      BBR4  $50,*+84
      BBR4  $50,*-125
      BBR4  $50,*
      BVC   *+83
      BVC   *-126
      BVC   *
      EOR   ($52),Y
      EOR   ($53)
      EOR   $56,X
      LSR   $57,X
      RMB5  $58
      CLI
      EOR   $5B5A,Y
      EOR   >$005A,Y
      PHY
      EOR   $5F5E,X
      EOR   >$005E,X
      LSR   $605F,X
      LSR   >$005F,X
      BBR5  $60,*+100
      BBR5  $60,*-125
      BBR5  $60,*
      RTS
      ADC   ($62,X)
      STZ   $65
      ADC   $66
      ROR   $67
      RMB6  $68
      PLA
      ADC   #$6A
      ROR   A
      JMP   ($6E6D)
      JMP   (>$006D)
      ADC   $6F6E
      ADC   >$006E
      ROR   $706F
      ROR   >$006F
      BBR6  $70,*+116
      BBR6  $70,*-125
      BBR6  $70,*
      BVS   *+115
      BVS   *-126
      BVS   *
      ADC   ($72),Y
      ADC   ($73)
      STZ   $75,X
      ADC   $76,X
      ROR   $77,X
      RMB7  $78
      SEI
      ADC   $7B7A,Y
      ADC   >$007A,Y
      PLY
      JMP   ($7E7D,X)
      JMP   (>$007D,X)
      ADC   $7F7E,X
      ADC   >$007E,X
      ROR   $807F,X
      ROR   >$007F,X
      BBR7  $80,*-124
      BBR7  $80,*
      BBR7  $80,*+1
      BRA   *-125
      BRA   *
      BRA   *+1
      STA   ($82,X)
      STY   $85
      STA   $86
      STX   $87
      SMB0  $88
      DEY
      BIT   #$8A
      TXA
      STY   $8E8D
      STY   >$008D
      STA   $8F8E
      STA   >$008E
      STX   $908F
      STX   >$008F
      BBS0  $90,*-108
      BBS0  $90,*
      BBS0  $90,*+1
      BCC   *-109
      BCC   *
      BCC   *+1
      STA   ($92),Y
      STA   ($93)
      STY   $95,X
      STA   $96,X
      STX   $97,Y
      SMB1  $98
      TYA
      STA   $9B9A,Y
      STA   >$009A,Y
      TXS
      STZ   $9E9D
      STZ   >$009D
      STA   $9F9E,X
      STA   >$009E,X
      STZ   $A09F,X
      STZ   >$009F,X
      BBS1  $A0,*-92
      BBS1  $A0,*
      BBS1  $A0,*+1
      LDY   #$A1
      LDA   ($A2,X)
      LDX   #$A3
      LDY   $A5
      LDA   $A6
      LDX   $A7
      SMB2  $A8
      TAY
      LDA   #$AA
      TAX
      LDY   $AEAD
      LDY   >$00AD
      LDA   $AFAE
      LDA   >$00AE
      LDX   $B0AF
      LDX   >$00AF
      BBS2  $B0,*-76
      BBS2  $B0,*
      BBS2  $B0,*+1
      BCS   *-77
      BCS   *
      BCS   *+1
      LDA   ($B2),Y
      LDA   ($B3)
      LDY   $B5,X
      LDA   $B6,X
      LDX   $B7,Y
      SMB3  $B8
      CLV
      LDA   $BBBA,Y
      LDA   >$00BA,Y
      TSX
      LDY   $BEBD,X
      LDY   >$00BD,X
      LDA   $BFBE,X
      LDA   >$00BE,X
      LDX   $C0BF,Y
      LDX   >$00BF,Y
      BBS3  $C0,*-60
      BBS3  $C0,*
      BBS3  $C0,*+1
      CPY   #$C1
      CMP   ($C2,X)
      CPY   $C5
      CMP   $C6
      DEC   $C7
      SMB4  $C8
      INY
      CMP   #$CA
      DEX
      CPY   $CECD
      CPY   >$00CD
      CMP   $CFCE
      CMP   >$00CE
      DEC   $D0CF
      DEC   >$00CF
      BBS4  $D0,*-44
      BBS4  $D0,*
      BBS4  $D0,*+1
      BNE   *-45
      BNE   *
      BNE   *+1
      CMP   ($D2),Y
      CMP   ($D3)
      CMP   $D6,X
      DEC   $D7,X
      SMB5  $D8
      CLD
      CMP   $DBDA,Y
      CMP   >$00DA,Y
      PHX
      CMP   $DFDE,X
      CMP   >$00DE,X
      DEC   $E0DF,X
      DEC   >$00DF,X
      BBS5  $E0,*-28
      BBS5  $E0,*
      BBS5  $E0,*+1
      CPX   #$E1
      SBC   ($E2,X)
      CPX   $E5
      SBC   $E6
      INC   $E7
      SMB6  $E8
      INX
      SBC   #$EA
      NOP
      CPX   $EEED
      CPX   >$00ED
      SBC   $EFEE
      SBC   >$00EE
      INC   $F0EF
      INC   >$00EF
      BBS6  $F0,*-12
      BBS6  $F0,*
      BBS6  $F0,*+1
      BEQ   *-13
      BEQ   *
      BEQ   *+1
      SBC   ($F2),Y
      SBC   ($F3)
      SBC   $F6,X
      INC   $F7,X
      SMB7  $F8
      SED
      SBC   $FBFA,Y
      SBC   >$00FA,Y
      PLX
      SBC   $FFFE,X
      SBC   >$00FE,X
      INC   >$00FF,X
      INC   $01FF,X
      BBS7  $00,*+4
      BBS7  $00,*-125
      BBS7  $00,*
