;;; AUTO GENERATED FILE
;;; generated by: gen_f3850 -u -C F3850 -o gen_f3850.asm -l gen_f3850.lst
      CPU   F3850
      ORG   0100H
      LR    A, KU
      LR    A, KL
      LR    A, QU
      LR    A, QL
      LR    KU, A
      LR    KL, A
      LR    QU, A
      LR    QL, A
      LR    K, P
      LR    P, K
      LR    A, IS
      LR    IS, A
      PK
      LR    P0, Q
      LR    Q, DC
      LR    DC, Q
      LR    DC, H
      LR    H, DC
      SR    1
      SL    1
      LM
      ST
      COM
      LNK
      DI
      EI
      POP
      LR    W, J
      LR    J, W
      INC
      LI    21H
      NI    22H
      OI    23H
      XI    24H
      AI    25H
      CI    26H
      IN    27H
      OUT   28H
      PI    292AH
      JMP   2A2BH
      DCI   2B2CH
      NOP
      XDC
      DS    0
      DS    J
      DS    HU
      DS    HL
      DS    S
      DS    I
      DS    D
      LR    A, 0
      LR    A, J
      LR    A, HU
      LR    A, HL
      LR    A, S
      LR    A, I
      LR    A, D
      LR    0, A
      LR    J, A
      LR    HU, A
      LR    HL, A
      LR    S, A
      LR    I, A
      LR    D, A
      LISU  0
      LISL  0
      CLR
      LIS   1
      BT    0, $-126
      BT    0, $
      BT    0, $+1
      BP    $-125
      BP    $
      BP    $+1
      BC    $-124
      BC    $
      BC    $+1
      BZ    $-122
      BZ    $
      BZ    $+1
      AM
      AMD
      NM
      OM
      XM
      CM
      ADC
      BR7   $-111
      BR7   $
      BR7   $+1
      BR    $-110
      BR    $
      BR    $+1
      BM    $-109
      BM    $
      BM    $+1
      BNC   $-108
      BNC   $
      BNC   $+1
      BF    3, $-107
      BF    3, $
      BF    3, $+1
      BNZ   $-106
      BNZ   $
      BNZ   $+1
      BNO   $-102
      BNO   $
      BNO   $+1
      INS   0
      OUTS  0
      AS    0
      AS    J
      AS    HU
      AS    HL
      AS    S
      AS    I
      AS    D
      ASD   0
      ASD   J
      ASD   HU
      ASD   HL
      ASD   S
      ASD   I
      ASD   D
      XS    0
      XS    J
      XS    HU
      XS    HL
      XS    S
      XS    I
      XS    D
      NS    0
      NS    J
      NS    HU
      NS    HL
      NS    S
      NS    I
      NS    D
