;;; AUTO GENERATED FILE
;;; generated by: gen_cdp1802 -u -C 1804A -o gen_cdp1804a.asm -l gen_cdp1804a.lst
      CPU  1804A
      ORG  0100H
      IDL
      LDN  1
      INC  0
      DEC  0
      BR   0131H
      BQ   0132H
      BZ   0133H
      BDF  0134H
      B1   0135H
      B2   0136H
      B3   0137H
      B4   0138H
      SKP
      BNQ  013AH
      BNZ  013BH
      BNF  013CH
      BN1  013DH
      BN2  013EH
      BN3  013FH
      BN4  0140H
      LDA  0
      STR  0
      IRX
      OUT  1
      RLXA 9
      DADC
      DSAV
      DSMB
      DACI 7DH
      DSBI 80H
      SCAL 0,8182H
      INP  1
      RET
      DIS
      LDXA
      STXD
      ADC
      SDB
      SHRC
      SMB
      SAV
      MARK
      REQ
      SEQ
      ADCI 7DH
      SDBI 7EH
      SHLC
      SMBI 80H
      GLO  0
      GHI  0
      PLO  0
      PHI  0
      LBR  0C1C2H
      LBQ  0C2C3H
      LBZ  0C3C4H
      LBDF 0C4C5H
      NOP
      LSNQ
      LSNZ
      LSNF
      LSKP
      LBNQ 0CACBH
      LBNZ 0CBCCH
      LBNF 0CCCDH
      LSIE
      LSQ
      LSZ
      LSDF
      SEP  0
      SEX  0
      LDX
      OR
      AND
      XOR
      ADD
      SD
      SHR
      SM
      LDI  0F9H
      ORI  0FAH
      ANI  0FBH
      XRI  0FCH
      ADI  0FDH
      SDI  0FEH
      SHL
      SMI  0
      SRET 0
      RSXD 0
      RNX  0
      RLDI 0,0C1C2H
      DADD
      DSM
      DADI 0FDH
      DSMI 0
      STPC
      DTC
      SPM2
      SCM2
      SPM1
      SCM1
      LDC
      STM
      GEC
      ETQ
      XIE
      XID
      CIE
      CID
      DBNZ 0,2122H
      BCI  013FH
      BXI  0140H
