;;; AUTO GENERATED FILE
;;; generated by: gen_ins8060 -u -C SC/MP -o gen_ins8060.asm -l gen_ins8060.lst
      CPU   SC/MP
      ORG   0100H
      HALT
      XAE
      CCL
      SCL
      DINT
      IEN
      CSA
      CAS
      NOP
      SIO
      SR
      SRL
      RR
      RRL
      XPAL  PC
      XPAL  P1
      XPAH  PC
      XPAH  P1
      XPPC  PC
      XPPC  P1
      LDE
      ANE
      ORE
      XRE
      DAE
      ADE
      CAE
      DLY   90H
      JMP   $-109
      JMP   $
      JMP   $+1
      JMP   -110(P1)
      JMP   E(P1)
      JP    $-105
      JP    $
      JP    $+1
      JP    -106(P1)
      JP    E(P1)
      JZ    $-101
      JZ    $
      JZ    $+1
      JZ    -102(P1)
      JZ    E(P1)
      JNZ   $-97
      JNZ   $
      JNZ   $+1
      JNZ   -98(P1)
      JNZ   E(P1)
      ILD   $-86
      ILD   $
      ILD   $+1
      ILD   -86(P1)
      ILD   E(P1)
      DLD   $-70
      DLD   $
      DLD   $+1
      DLD   -70(P1)
      DLD   E(P1)
      LD    $-62
      LD    $
      LD    $+1
      LD    -62(P1)
      LD    E(P1)
      LDI   0C5H
      LD    @-58(P1)
      LD    @E(P1)
      ST    $-54
      ST    $
      ST    $+1
      ST    -54(P1)
      ST    E(P1)
      ST    @-50(P1)
      ST    @E(P1)
      AND   $-46
      AND   $
      AND   $+1
      AND   -46(P1)
      AND   E(P1)
      ANI   0D5H
      AND   @-42(P1)
      AND   @E(P1)
      OR    $-38
      OR    $
      OR    $+1
      OR    -38(P1)
      OR    E(P1)
      ORI   0DDH
      OR    @-34(P1)
      OR    @E(P1)
      XOR   $-30
      XOR   $
      XOR   $+1
      XOR   -30(P1)
      XOR   E(P1)
      XRI   0E5H
      XOR   @-26(P1)
      XOR   @E(P1)
      DAD   $-22
      DAD   $
      DAD   $+1
      DAD   -22(P1)
      DAD   E(P1)
      DAI   0EDH
      DAD   @-18(P1)
      DAD   @E(P1)
      ADD   $-14
      ADD   $
      ADD   $+1
      ADD   -14(P1)
      ADD   E(P1)
      ADI   0F5H
      ADD   @-10(P1)
      ADD   @E(P1)
      CAD   $-6
      CAD   $
      CAD   $+1
      CAD   -6(P1)
      CAD   E(P1)
      CAI   0FDH
      CAD   @-2(P1)
      CAD   @E(P1)
