;;; AUTO GENERATED FILE
;;; generated by: gen_i8080 -u -C 8080 -o gen_i8080.asm -l gen_i8080.lst
      CPU  8080
      ORG  0100H
      NOP
      LXI  B,0302H
      STAX B
      INX  B
      INR  B
      DCR  B
      MVI  B,7
      RLC
      DAD  B
      LDAX B
      DCX  B
      INR  C
      DCR  C
      MVI  C,15
      RRC
      LXI  D,1312H
      STAX D
      INX  D
      INR  D
      DCR  D
      MVI  D,23
      RAL
      DAD  D
      LDAX D
      DCX  D
      INR  E
      DCR  E
      MVI  E,31
      RAR
      LXI  H,2322H
      SHLD 2423H
      INX  H
      INR  H
      DCR  H
      MVI  H,27H
      DAA
      DAD  H
      LHLD 2C2BH
      DCX  H
      INR  L
      DCR  L
      MVI  L,2FH
      CMA
      LXI  SP,3332H
      STA  3433H
      INX  SP
      INR  M
      DCR  M
      MVI  M,37H
      STC
      DAD  SP
      LDA  3C3BH
      DCX  SP
      INR  A
      DCR  A
      MVI  A,3FH
      CMC
      MOV  B,B
      MOV  B,C
      MOV  B,D
      MOV  B,E
      MOV  B,H
      MOV  B,L
      MOV  B,M
      MOV  B,A
      MOV  C,B
      MOV  C,C
      MOV  C,D
      MOV  C,E
      MOV  C,H
      MOV  C,L
      MOV  C,M
      MOV  C,A
      MOV  D,B
      MOV  D,C
      MOV  D,D
      MOV  D,E
      MOV  D,H
      MOV  D,L
      MOV  D,M
      MOV  D,A
      MOV  E,B
      MOV  E,C
      MOV  E,D
      MOV  E,E
      MOV  E,H
      MOV  E,L
      MOV  E,M
      MOV  E,A
      MOV  H,B
      MOV  H,C
      MOV  H,D
      MOV  H,E
      MOV  H,H
      MOV  H,L
      MOV  H,M
      MOV  H,A
      MOV  L,B
      MOV  L,C
      MOV  L,D
      MOV  L,E
      MOV  L,H
      MOV  L,L
      MOV  L,M
      MOV  L,A
      MOV  M,B
      MOV  M,C
      MOV  M,D
      MOV  M,E
      MOV  M,H
      MOV  M,L
      HLT
      MOV  M,A
      MOV  A,B
      MOV  A,C
      MOV  A,D
      MOV  A,E
      MOV  A,H
      MOV  A,L
      MOV  A,M
      MOV  A,A
      ADD  B
      ADD  C
      ADD  D
      ADD  E
      ADD  H
      ADD  L
      ADD  M
      ADD  A
      ADC  B
      ADC  C
      ADC  D
      ADC  E
      ADC  H
      ADC  L
      ADC  M
      ADC  A
      SUB  B
      SUB  C
      SUB  D
      SUB  E
      SUB  H
      SUB  L
      SUB  M
      SUB  A
      SBB  B
      SBB  C
      SBB  D
      SBB  E
      SBB  H
      SBB  L
      SBB  M
      SBB  A
      ANA  B
      ANA  C
      ANA  D
      ANA  E
      ANA  H
      ANA  L
      ANA  M
      ANA  A
      XRA  B
      XRA  C
      XRA  D
      XRA  E
      XRA  H
      XRA  L
      XRA  M
      XRA  A
      ORA  B
      ORA  C
      ORA  D
      ORA  E
      ORA  H
      ORA  L
      ORA  M
      ORA  A
      CMP  B
      CMP  C
      CMP  D
      CMP  E
      CMP  H
      CMP  L
      CMP  M
      CMP  A
      RNZ
      POP  B
      JNZ  0C4C3H
      JMP  0C5C4H
      CNZ  0C6C5H
      PUSH B
      ADI  0C7H
      RST  0
      RZ
      RET
      JZ   0CCCBH
      CZ   0CECDH
      CALL 0CFCEH
      ACI  0CFH
      RNC
      POP  D
      JNC  0D4D3H
      OUT  0D4H
      CNC  0D6D5H
      PUSH D
      SUI  0D7H
      RC
      JC   0DCDBH
      IN   0DCH
      CC   0DEDDH
      SBI  0DFH
      RPO
      POP  H
      JPO  0E4E3H
      XTHL
      CPO  0E6E5H
      PUSH H
      ANI  0E7H
      RPE
      PCHL
      JPE  0ECEBH
      XCHG
      CPE  0EEEDH
      XRI  0EFH
      RP
      POP  PSW
      JP   0F4F3H
      DI
      CP   0F6F5H
      PUSH PSW
      ORI  0F7H
      RM
      SPHL
      JM   0FCFBH
      EI
      CM   0FEFDH
      CPI  0FFH
