;;; AUTO GENERATED FILE
;;; generated by: gen_z8 -u -C Z88C00 -o gen_z88.asm -l gen_z88.lst
      CPU     Z88C00
      ORG     0100H
      DEC     >01H
      DEC     10H
      DEC     @02H
      ADD     R0, R3
      ADD     R0, @R4
      ADD     >06H, >05H
      ADD     10H, >05H
      ADD     11H, 10H
      ADD     >00H, 10H
      ADD     >07H, @06H
      ADD     10H, @06H
      ADD     >07H, #8
      ADD     10H, #17
      BOR     R0, >09H, #4
      BOR     R0, 10H, #4
      BOR     >0AH, #4, R0
      BOR     10H, #4, R0
      LD      R0, >09H
      LD      R0, 10H
      LD      >0AH, R0
      LD      10H, R0
      DJNZ    R0, $+13
      DJNZ    R0, $-126
      DJNZ    R0, $
      JR      F, $+14
      JR      F, $-126
      JR      F, $
      LD      R0, #13
      JP      F, 0E0FH
      INC     R0
      NEXT
      RLC     11H
      RLC     >00H
      RLC     @12H
      ADC     R1, R3
      ADC     R1, @R4
      ADC     16H, 15H
      ADC     >00H, 15H
      ADC     >01H, >00H
      ADC     10H, >00H
      ADC     17H, @16H
      ADC     >00H, @16H
      ADC     17H, #24
      ADC     >00H, #1
      BCP     R1, 19H, #4
      BCP     R1, >00H, #4
      JR      LT, $+30
      JR      LT, $-126
      JR      LT, $
      JP      LT, 1E1FH
      ENTER
      INC     21H
      INC     >00H
      INC     @22H
      SUB     R2, R3
      SUB     R2, @R4
      SUB     26H, 25H
      SUB     >00H, 25H
      SUB     >01H, >00H
      SUB     10H, >00H
      SUB     27H, @26H
      SUB     >00H, @26H
      SUB     27H, #28H
      SUB     >00H, #1
      BXOR    R2, 29H, #4
      BXOR    R2, >00H, #4
      BXOR    2AH, #4, R2
      BXOR    >00H, #4, R2
      JR      LE, $+46
      JR      LE, $-126
      JR      LE, $
      JP      LE, 2E2FH
      EXIT
      JP      @32H
      SRP0    #30H
      SRP1    #38H
      SRP     #40H
      SBC     R3, R3
      SBC     R3, @R4
      SBC     36H, 35H
      SBC     >00H, 35H
      SBC     >01H, >00H
      SBC     10H, >00H
      SBC     37H, @36H
      SBC     >00H, @36H
      SBC     37H, #38H
      SBC     >00H, #1
      BTJRF   $+60, R3, #4
      BTJRF   $-125, R3, #4
      BTJRF   $, R3, #4
      BTJRT   $+61, R3, #4
      BTJRT   $-125, R3, #4
      BTJRT   $, R3, #4
      JR      ULE, $+62
      JR      ULE, $-126
      JR      ULE, $
      JP      ULE, 3E3FH
      WFI
      DA      41H
      DA      >00H
      DA      @42H
      OR      R4, R3
      OR      R4, @R4
      OR      46H, 45H
      OR      >00H, 45H
      OR      >01H, >00H
      OR      10H, >00H
      OR      47H, @46H
      OR      >00H, @46H
      OR      47H, #48H
      OR      >00H, #1
      LDB     R4, 49H, #4
      LDB     R4, >00H, #4
      LDB     4AH, #4, R4
      LDB     >00H, #4, R4
      JR      OV, $+78
      JR      OV, $-126
      JR      OV, $
      JP      OV, 4E4FH
      SB0
      POP     51H
      POP     >00H
      POP     @52H
      AND     R5, R3
      AND     R5, @R4
      AND     56H, 55H
      AND     >00H, 55H
      AND     >01H, >00H
      AND     10H, >00H
      AND     57H, @56H
      AND     >00H, @56H
      AND     57H, #58H
      AND     >00H, #1
      BITC    R5, #4
      JR      MI, $+94
      JR      MI, $-126
      JR      MI, $
      JP      MI, 5E5FH
      SB1
      COM     61H
      COM     >00H
      COM     @62H
      TCM     R6, R3
      TCM     R6, @R4
      TCM     66H, 65H
      TCM     >00H, 65H
      TCM     >01H, >00H
      TCM     10H, >00H
      TCM     67H, @66H
      TCM     >00H, @66H
      TCM     67H, #68H
      TCM     >00H, #1
      BAND    R6, 69H, #4
      BAND    R6, >00H, #4
      BAND    6AH, #4, R6
      BAND    >00H, #4, R6
      JR      Z, $+110
      JR      Z, $-126
      JR      Z, $
      JP      Z, 6E6FH
      PUSH    71H
      PUSH    >00H
      PUSH    @72H
      TM      R7, R3
      TM      R7, @R4
      TM      76H, 75H
      TM      >00H, 75H
      TM      >01H, >00H
      TM      10H, >00H
      TM      77H, @76H
      TM      >00H, @76H
      TM      77H, #78H
      TM      >00H, #1
      BITR    R7, #4
      BITS    R7, #4
      JR      C, $+126
      JR      C, $-126
      JR      C, $
      JP      C, 7E7FH
      DECW    82H
      DECW    >00H
      DECW    @82H
      PUSHUD  @83H, 84H
      PUSHUD  @83H, >00H
      PUSHUI  @84H, 85H
      PUSHUI  @84H, >00H
      MULT    86H, 85H
      MULT    >00H, 85H
      MULT    >02H, >00H
      MULT    10H, >00H
      MULT    88H, @86H
      MULT    >00H, @86H
      MULT    88H, #87H
      MULT    >00H, #87H
      LD      R8, 89H(R8)
      JR      $-114
      JR      $
      JR      $+1
      JP      8E8FH
      DI
      RL      91H
      RL      >00H
      RL      @92H
      POPUD   94H, @93H
      POPUD   >00H, @93H
      POPUI   95H, @94H
      POPUI   >00H, @94H
      DIV     96H, 95H
      DIV     >00H, 95H
      DIV     >02H, >00H
      DIV     10H, >00H
      DIV     98H, @96H
      DIV     >00H, @96H
      DIV     98H, #97H
      DIV     >00H, #97H
      LD      99H(R8), R9
      JR      GE, $-98
      JR      GE, $
      JR      GE, $+1
      JP      GE, 9E9FH
      EI
      INCW    0A2H
      INCW    >00H
      INCW    @0A2H
      CP      R10, R3
      CP      R10, @R4
      CP      0A6H, 0A5H
      CP      >00H, 0A5H
      CP      >01H, >00H
      CP      10H, >00H
      CP      0A7H, @0A6H
      CP      >00H, @0A6H
      CP      0A7H, #0A8H
      CP      >00H, #1
      LDC     R10, 0AAA9H(RR8)
      LDE     R10, 0ABAAH(RR8)
      LDC     R11, 0B2B1H
      LDE     R11, 0B3B2H
      JR      GT, $-82
      JR      GT, $
      JR      GT, $+1
      JP      GT, 0AEAFH
      RET
      CLR     0B1H
      CLR     >00H
      CLR     @0B2H
      XOR     R11, R3
      XOR     R11, @R4
      XOR     0B6H, 0B5H
      XOR     >00H, 0B5H
      XOR     >01H, >00H
      XOR     10H, >00H
      XOR     0B7H, @0B6H
      XOR     >00H, @0B6H
      XOR     0B7H, #0B8H
      XOR     >00H, #1
      LDC     0BAB9H(RR8), R11
      LDE     0BBBAH(RR8), R11
      LDC     0C2C1H, R12
      LDE     0C3C2H, R12
      JR      UGT, $-66
      JR      UGT, $
      JR      UGT, $+1
      JP      UGT, 0BEBFH
      IRET
      RRC     0C1H
      RRC     >00H
      RRC     @0C2H
      CPIJE   R3, @R12, $-57
      CPIJE   R3, @R12, $
      CPIJE   R3, @R12, $+1
      LDC     R12, @RR4
      LDE     R12, @RR4
      LDW     0C8H, 0C6H
      LDW     >00H, 0C6H
      LDW     >02H, >00H
      LDW     10H, >00H
      LDW     0C8H, @0C6H
      LDW     >00H, @0C6H
      LDW     0C8H, #0C9CAH
      LDW     >00H, #0102H
      LD      R12, @R8
      JR      NOV, $-50
      JR      NOV, $
      JR      NOV, $+1
      JP      NOV, 0CECFH
      RCF
      SRA     0D1H
      SRA     >00H
      SRA     @0D2H
      CPIJNE  R3, @R13, $-41
      CPIJNE  R3, @R13, $
      CPIJNE  R3, @R13, $+1
      LDC     @RR4, R13
      LDE     @RR4, R13
      CALL    #0D6H
      LD      @0D7H, #0D8H
      LD      @R13, R8
      JR      PL, $-34
      JR      PL, $
      JR      PL, $+1
      JP      PL, 0DEDFH
      SCF
      RR      0E1H
      RR      >00H
      RR      @0E2H
      LDED    R14, @RR2
      LDCD    R14, @RR4
      LDCI    R14, @RR4
      LDEI    R14, @RR4
      LD      0E6H, 0E5H
      LD      >00H, 0E5H
      LD      >01H, >00H
      LD      10H, >00H
      LD      0E7H, @0E6H
      LD      >00H, @0E6H
      LD      0E7H, #0E8H
      LD      >00H, #1
      LDC     R14, -23(RR8)
      LDC     R14, +1(RR8)
      LDE     R14, -22(RR8)
      LDE     R14, +1(RR8)
      JR      NZ, $-18
      JR      NZ, $
      JR      NZ, $+1
      JP      NZ, 0EEEFH
      CCF
      SWAP    0F1H
      SWAP    >00H
      SWAP    @0F2H
      LDEPD   @RR2, R15
      LDCPD   @RR4, R15
      LDCPI   @RR4, R15
      LDEPI   @RR4, R15
      CALL    @0F6H
      LD      @0F7H, 0F6H
      LD      @01H, >00H
      CALL    0F7F8H
      LDC     -7(RR8), R15
      LDC     +1(RR8), R15
      LDE     -6(RR8), R15
      LDE     +1(RR8), R15
      JR      NC, $-2
      JR      NC, $
      JR      NC, $+1
      JP      NC, 0FEFFH
      NOP
