;;; AUTO GENERATED FILE
;;; generated by: gen_mc6805 -u -C 68HC08 -o gen_mc68hc08.asm -l gen_mc68hc08.lst
      CPU   68HC08
      ORG   $0100
      BRSET 0, $01, *+5
      BRSET 0, $01, *-125
      BRSET 0, $01, *
      BRCLR 0, $02, *+6
      BRCLR 0, $02, *-125
      BRCLR 0, $02, *
      BSET  0, $11
      BCLR  0, $12
      BRA   *+35
      BRA   *-126
      BRA   *
      BRN   *+36
      BRN   *-126
      BRN   *
      BHI   *+37
      BHI   *-126
      BHI   *
      BLS   *+38
      BLS   *-126
      BLS   *
      BHS   *+39
      BHS   *-126
      BHS   *
      BLO   *+40
      BLO   *-126
      BLO   *
      BNE   *+41
      BNE   *-126
      BNE   *
      BEQ   *+42
      BEQ   *-126
      BEQ   *
      BHCC  *+43
      BHCC  *-126
      BHCC  *
      BHCS  *+44
      BHCS  *-126
      BHCS  *
      BPL   *+45
      BPL   *-126
      BPL   *
      BMI   *+46
      BMI   *-126
      BMI   *
      BMC   *+47
      BMC   *-126
      BMC   *
      BMS   *+48
      BMS   *-126
      BMS   *
      BIL   *+49
      BIL   *-126
      BIL   *
      BIH   *+50
      BIH   *-126
      BIH   *
      NEG   $31
      CBEQ  $32, *+54
      CBEQ  $32, *-125
      CBEQ  $32, *
      COM   $34
      LSR   $35
      STHX  $36
      ROR   $37
      ASR   $38
      ASL   $39
      ROL   $3A
      DEC   $3B
      DBNZ  $3C, *+64
      DBNZ  $3C, *-125
      DBNZ  $3C, *
      INC   $3D
      TST   $3E
      CLR   $40
      NEGA
      CBEQA #$42, *+70
      CBEQA #$42, *-125
      CBEQA #$42, *
      MUL
      COMA
      LSRA
      LDHX  #$4647
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      DBNZA *+78
      DBNZA *-126
      DBNZA *
      INCA
      TSTA
      MOV   $4F, $50
      CLRA
      NEGX
      CBEQX #$52, *+86
      CBEQX #$52, *-125
      CBEQX #$52, *
      DIV
      COMX
      LSRX
      LDHX  $56
      RORX
      ASRX
      ASLX
      ROLX
      DECX
      DBNZX *+94
      DBNZX *-126
      DBNZX *
      INCX
      TSTX
      MOV   $5F, X+
      CLRX
      NEG   97,X
      NEG   <0,X
      CBEQ  98,X+, *+102
      CBEQ  98,X+, *-125
      CBEQ  98,X+, *
      CBEQ  <0,X+, *+4
      CBEQ  <0,X+, *-125
      CBEQ  <0,X+, *
      NSA
      COM   100,X
      COM   <0,X
      LSR   101,X
      LSR   <0,X
      CPHX  #$6667
      ROR   103,X
      ROR   <0,X
      ASR   104,X
      ASR   <0,X
      ASL   105,X
      ASL   <0,X
      ROL   106,X
      ROL   <0,X
      DEC   107,X
      DEC   <0,X
      DBNZ  108,X, *+112
      DBNZ  108,X, *-125
      DBNZ  108,X, *
      DBNZ  <0,X, *+4
      DBNZ  <0,X, *-125
      DBNZ  <0,X, *
      INC   109,X
      INC   <0,X
      TST   110,X
      TST   <0,X
      MOV   #$6F, $70
      CLR   112,X
      CLR   <0,X
      NEG   ,X
      CBEQ  X+, *+116
      CBEQ  X+, *-126
      CBEQ  X+, *
      DAA
      COM   ,X
      LSR   ,X
      CPHX  $76
      ROR   ,X
      ASR   ,X
      ASL   ,X
      ROL   ,X
      DEC   ,X
      DBNZ  ,X, *+126
      DBNZ  ,X, *-126
      DBNZ  ,X, *
      INC   ,X
      TST   ,X
      MOV   X+, $7F
      CLR   ,X
      RTI
      RTS
      SWI
      TAP
      TPA
      PULA
      PSHA
      PULX
      PSHX
      PULH
      PSHH
      CLRH
      STOP
      WAIT
      BGE   *-109
      BGE   *
      BGE   *+1
      BLT   *-108
      BLT   *
      BLT   *+1
      BGT   *-107
      BGT   *
      BGT   *+1
      BLE   *-106
      BLE   *
      BLE   *+1
      TXS
      TSX
      TAX
      CLC
      SEC
      CLI
      SEI
      RSP
      NOP
      SUB   $D1D2,SP
      SUB   >$0001,SP
      CMP   $D2D3,SP
      CMP   >$0001,SP
      SBC   $D3D4,SP
      SBC   >$0001,SP
      CPX   $D4D5,SP
      CPX   >$0001,SP
      AND   $D5D6,SP
      AND   >$0001,SP
      BIT   $D6D7,SP
      BIT   >$0001,SP
      LDA   $D7D8,SP
      LDA   >$0001,SP
      STA   $D8D9,SP
      STA   >$0001,SP
      EOR   $D9DA,SP
      EOR   >$0001,SP
      ADC   $DADB,SP
      ADC   >$0001,SP
      ORA   $DBDC,SP
      ORA   >$0001,SP
      ADD   $DCDD,SP
      ADD   >$0001,SP
      LDX   $DFE0,SP
      LDX   >$0001,SP
      STX   $E0E1,SP
      STX   >$0001,SP
      SUB   225,SP
      SUB   <0,SP
      CMP   226,SP
      CMP   <0,SP
      SBC   227,SP
      SBC   <0,SP
      CPX   228,SP
      CPX   <0,SP
      AND   229,SP
      AND   <0,SP
      BIT   230,SP
      BIT   <0,SP
      LDA   231,SP
      LDA   <0,SP
      STA   232,SP
      STA   <0,SP
      EOR   233,SP
      EOR   <0,SP
      ADC   234,SP
      ADC   <0,SP
      ORA   235,SP
      ORA   <0,SP
      ADD   236,SP
      ADD   <0,SP
      LDX   239,SP
      LDX   <0,SP
      STX   240,SP
      STX   <0,SP
      NEG   97,SP
      NEG   <0,SP
      CBEQ  98,SP, *+103
      CBEQ  98,SP, *-124
      CBEQ  98,SP, *
      CBEQ  <0,SP, *+5
      CBEQ  <0,SP, *-124
      CBEQ  <0,SP, *
      COM   100,SP
      COM   <0,SP
      LSR   101,SP
      LSR   <0,SP
      ROR   103,SP
      ROR   <0,SP
      ASR   104,SP
      ASR   <0,SP
      ASL   105,SP
      ASL   <0,SP
      ROL   106,SP
      ROL   <0,SP
      DEC   107,SP
      DEC   <0,SP
      DBNZ  108,SP, *+113
      DBNZ  108,SP, *-124
      DBNZ  108,SP, *
      DBNZ  <0,SP, *+5
      DBNZ  <0,SP, *-124
      DBNZ  <0,SP, *
      INC   109,SP
      INC   <0,SP
      TST   110,SP
      TST   <0,SP
      CLR   112,SP
      CLR   <0,SP
      TXA
      SUB   #$A1
      CMP   #$A2
      SBC   #$A3
      CPX   #$A4
      AND   #$A5
      BIT   #$A6
      LDA   #$A7
      AIS   #-$58
      AIS   #0
      EOR   #$A9
      ADC   #$AA
      ORA   #$AB
      ADD   #$AC
      BSR   *-80
      BSR   *
      BSR   *+1
      LDX   #$AF
      AIX   #-$50
      AIX   #0
      SUB   $B1
      CMP   $B2
      SBC   $B3
      CPX   $B4
      AND   $B5
      BIT   $B6
      LDA   $B7
      STA   $B8
      EOR   $B9
      ADC   $BA
      ORA   $BB
      ADD   $BC
      JMP   $BD
      JSR   $BE
      LDX   $BF
      STX   $C0
      SUB   >$0001
      SUB   $0102
      CMP   >$0001
      CMP   $0102
      SBC   >$0001
      SBC   $0102
      CPX   >$0001
      CPX   $0102
      AND   >$0001
      AND   $0102
      BIT   >$0001
      BIT   $0102
      LDA   >$0001
      LDA   $0102
      STA   >$0001
      STA   $0102
      EOR   >$0001
      EOR   $0102
      ADC   >$0001
      ADC   $0102
      ORA   >$0001
      ORA   $0102
      ADD   >$0001
      ADD   $0102
      JMP   >$0001
      JMP   $0102
      JSR   >$0001
      JSR   $0102
      LDX   >$0001
      LDX   $0102
      STX   >$0001
      STX   $0102
      SUB   $D1D2,X
      SUB   >$0001,X
      CMP   $D2D3,X
      CMP   >$0001,X
      SBC   $D3D4,X
      SBC   >$0001,X
      CPX   $D4D5,X
      CPX   >$0001,X
      AND   $D5D6,X
      AND   >$0001,X
      BIT   $D6D7,X
      BIT   >$0001,X
      LDA   $D7D8,X
      LDA   >$0001,X
      STA   $D8D9,X
      STA   >$0001,X
      EOR   $D9DA,X
      EOR   >$0001,X
      ADC   $DADB,X
      ADC   >$0001,X
      ORA   $DBDC,X
      ORA   >$0001,X
      ADD   $DCDD,X
      ADD   >$0001,X
      JMP   $DDDE,X
      JMP   >$0001,X
      JSR   $DEDF,X
      JSR   >$0001,X
      LDX   $DFE0,X
      LDX   >$0001,X
      STX   $E0E1,X
      STX   >$0001,X
      SUB   225,X
      SUB   <0,X
      CMP   226,X
      CMP   <0,X
      SBC   227,X
      SBC   <0,X
      CPX   228,X
      CPX   <0,X
      AND   229,X
      AND   <0,X
      BIT   230,X
      BIT   <0,X
      LDA   231,X
      LDA   <0,X
      STA   232,X
      STA   <0,X
      EOR   233,X
      EOR   <0,X
      ADC   234,X
      ADC   <0,X
      ORA   235,X
      ORA   <0,X
      ADD   236,X
      ADD   <0,X
      JMP   237,X
      JMP   <0,X
      JSR   238,X
      JSR   <0,X
      LDX   239,X
      LDX   <0,X
      STX   240,X
      STX   <0,X
      SUB   ,X
      CMP   ,X
      SBC   ,X
      CPX   ,X
      AND   ,X
      BIT   ,X
      LDA   ,X
      STA   ,X
      EOR   ,X
      ADC   ,X
      ORA   ,X
      ADD   ,X
      JMP   ,X
      JSR   ,X
      LDX   ,X
      STX   ,X
