;;; AUTO GENERATED FILE
;;; generated by: gen_mc6800 -u -C 6800 -o gen_mc6800.asm -l gen_mc6800.lst
      CPU   6800
      ORG   $0100
      NOP
      TAP
      TPA
      INX
      DEX
      CLV
      SEV
      CLC
      SEC
      CLI
      SEI
      SBA
      CBA
      TAB
      TBA
      DAA
      ABA
      BRA   *+35
      BHI   *+37
      BLS   *+38
      BHS   *+39
      BLO   *+40
      BNE   *+41
      BEQ   *+42
      BVC   *+43
      BVS   *+44
      BPL   *+45
      BMI   *+46
      BGE   *+47
      BLT   *+48
      BGT   *+49
      BLE   *+50
      TSX
      INS
      PULA
      PULB
      DES
      TXS
      PSHA
      PSHB
      RTS
      RTI
      WAI
      SWI
      NEGA
      COMA
      LSRA
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      INCA
      TSTA
      CLRA
      NEGB
      COMB
      LSRB
      RORB
      ASRB
      ASLB
      ROLB
      DECB
      INCB
      TSTB
      CLRB
      NEG   97,X
      COM   100,X
      LSR   101,X
      ROR   103,X
      ASR   104,X
      ASL   105,X
      ROL   106,X
      DEC   107,X
      INC   109,X
      TST   110,X
      JMP   111,X
      CLR   112,X
      NEG   $7172
      NEG   >$0001
      COM   $7475
      COM   >$0001
      LSR   $7576
      LSR   >$0001
      ROR   $7778
      ROR   >$0001
      ASR   $7879
      ASR   >$0001
      ASL   $797A
      ASL   >$0001
      ROL   $7A7B
      ROL   >$0001
      DEC   $7B7C
      DEC   >$0001
      INC   $7D7E
      INC   >$0001
      TST   $7E7F
      TST   >$0001
      JMP   $7F80
      JMP   >$0001
      CLR   $8081
      CLR   >$0001
      SUBA  #$81
      CMPA  #$82
      SBCA  #$83
      ANDA  #$85
      BITA  #$86
      LDAA  #$87
      EORA  #$89
      ADCA  #$8A
      ORAA  #$8B
      ADDA  #$8C
      CPX   #$8D8E
      BSR   *-112
      LDS   #$8F90
      SUBA  $91
      CMPA  $92
      SBCA  $93
      ANDA  $95
      BITA  $96
      LDAA  $97
      STAA  $98
      EORA  $99
      ADCA  $9A
      ORAA  $9B
      ADDA  $9C
      CPX   $9D
      LDS   $9F
      STS   $A0
      SUBA  161,X
      CMPA  162,X
      SBCA  163,X
      ANDA  165,X
      BITA  166,X
      LDAA  167,X
      STAA  168,X
      EORA  169,X
      ADCA  170,X
      ORAA  171,X
      ADDA  172,X
      CPX   173,X
      JSR   174,X
      LDS   175,X
      STS   176,X
      SUBA  $B1B2
      SUBA  >$0001
      CMPA  $B2B3
      CMPA  >$0001
      SBCA  $B3B4
      SBCA  >$0001
      ANDA  $B5B6
      ANDA  >$0001
      BITA  $B6B7
      BITA  >$0001
      LDAA  $B7B8
      LDAA  >$0001
      STAA  $B8B9
      STAA  >$0001
      EORA  $B9BA
      EORA  >$0001
      ADCA  $BABB
      ADCA  >$0001
      ORAA  $BBBC
      ORAA  >$0001
      ADDA  $BCBD
      ADDA  >$0001
      CPX   $BDBE
      CPX   >$0001
      JSR   $BEBF
      JSR   >$0001
      LDS   $BFC0
      LDS   >$0001
      STS   $C0C1
      STS   >$0001
      SUBB  #$C1
      CMPB  #$C2
      SBCB  #$C3
      ANDB  #$C5
      BITB  #$C6
      LDAB  #$C7
      EORB  #$C9
      ADCB  #$CA
      ORAB  #$CB
      ADDB  #$CC
      LDX   #$CFD0
      SUBB  $D1
      CMPB  $D2
      SBCB  $D3
      ANDB  $D5
      BITB  $D6
      LDAB  $D7
      STAB  $D8
      EORB  $D9
      ADCB  $DA
      ORAB  $DB
      ADDB  $DC
      LDX   $DF
      STX   $E0
      SUBB  225,X
      CMPB  226,X
      SBCB  227,X
      ANDB  229,X
      BITB  230,X
      LDAB  231,X
      STAB  232,X
      EORB  233,X
      ADCB  234,X
      ORAB  235,X
      ADDB  236,X
      LDX   239,X
      STX   240,X
      SUBB  $F1F2
      SUBB  >$0001
      CMPB  $F2F3
      CMPB  >$0001
      SBCB  $F3F4
      SBCB  >$0001
      ANDB  $F5F6
      ANDB  >$0001
      BITB  $F6F7
      BITB  >$0001
      LDAB  $F7F8
      LDAB  >$0001
      STAB  $F8F9
      STAB  >$0001
      EORB  $F9FA
      EORB  >$0001
      ADCB  $FAFB
      ADCB  >$0001
      ORAB  $FBFC
      ORAB  >$0001
      ADDB  $FCFD
      ADDB  >$0001
      LDX   $FF00
      LDX   >$0001
      STX   >$0001
      STX   $0102
