;;; AUTO GENERATED FILE
;;; generated by: gen_i960 -g -i -C 80960
;;;
;;; The generated source is shared with the GNU as build: the two assemblers
;;; differ only in the comment marker, which test/Makefile.gas rewrites.
        .cpu    80960
        .fpu    on
        .org    0x00800000
        .include "gen_i960.ginc"
        .end
