;;; AUTO GENERATED FILE
;;; generated by: gen_z80 -u -C Z380 -o gen_z380.asm -l gen_z380.lst
      CPU    Z380
      ORG    0100H
      NOP
      LD     BC, 0302H
      LD     (BC), A
      INC    BC
      INC    B
      DEC    B
      LD     B, 7
      RLCA
      EX     AF, AF'
      ADD    HL, BC
      LD     A, (BC)
      DEC    BC
      INC    C
      DEC    C
      LD     C, 15
      RRCA
      DJNZ   $+19
      LD     DE, 1312H
      LD     (DE), A
      INC    DE
      INC    D
      DEC    D
      LD     D, 23
      RLA
      JR     $+27
      ADD    HL, DE
      LD     A, (DE)
      DEC    DE
      INC    E
      DEC    E
      LD     E, 31
      RRA
      JR     NZ, $+35
      LD     HL, 2322H
      LD     (2423H), HL
      INC    HL
      INC    H
      DEC    H
      LD     H, 27H
      DAA
      JR     Z, $+43
      ADD    HL, HL
      LD     HL, (2C2BH)
      DEC    HL
      INC    L
      DEC    L
      LD     L, 2FH
      CPL
      JR     NC, $+51
      LD     SP, 3332H
      LD     (3433H), A
      INC    SP
      INC    (HL)
      DEC    (HL)
      LD     (HL), 37H
      SCF
      JR     C, $+59
      ADD    HL, SP
      LD     A, (3C3BH)
      DEC    SP
      INC    A
      DEC    A
      LD     A, 3FH
      CCF
      LD     B, B
      LD     B, C
      LD     B, D
      LD     B, E
      LD     B, H
      LD     B, L
      LD     B, (HL)
      LD     B, A
      LD     C, B
      LD     C, C
      LD     C, D
      LD     C, E
      LD     C, H
      LD     C, L
      LD     C, (HL)
      LD     C, A
      LD     D, B
      LD     D, C
      LD     D, D
      LD     D, E
      LD     D, H
      LD     D, L
      LD     D, (HL)
      LD     D, A
      LD     E, B
      LD     E, C
      LD     E, D
      LD     E, E
      LD     E, H
      LD     E, L
      LD     E, (HL)
      LD     E, A
      LD     H, B
      LD     H, C
      LD     H, D
      LD     H, E
      LD     H, H
      LD     H, L
      LD     H, (HL)
      LD     H, A
      LD     L, B
      LD     L, C
      LD     L, D
      LD     L, E
      LD     L, H
      LD     L, L
      LD     L, (HL)
      LD     L, A
      LD     (HL), B
      LD     (HL), C
      LD     (HL), D
      LD     (HL), E
      LD     (HL), H
      LD     (HL), L
      HALT
      LD     (HL), A
      LD     A, B
      LD     A, C
      LD     A, D
      LD     A, E
      LD     A, H
      LD     A, L
      LD     A, (HL)
      LD     A, A
      ADD    A, B
      ADD    A, C
      ADD    A, D
      ADD    A, E
      ADD    A, H
      ADD    A, L
      ADD    A, (HL)
      ADD    A, A
      ADC    A, B
      ADC    A, C
      ADC    A, D
      ADC    A, E
      ADC    A, H
      ADC    A, L
      ADC    A, (HL)
      ADC    A, A
      SUB    B
      SUB    C
      SUB    D
      SUB    E
      SUB    H
      SUB    L
      SUB    (HL)
      SUB    A
      SBC    A, B
      SBC    A, C
      SBC    A, D
      SBC    A, E
      SBC    A, H
      SBC    A, L
      SBC    A, (HL)
      SBC    A, A
      AND    B
      AND    C
      AND    D
      AND    E
      AND    H
      AND    L
      AND    (HL)
      AND    A
      XOR    B
      XOR    C
      XOR    D
      XOR    E
      XOR    H
      XOR    L
      XOR    (HL)
      XOR    A
      OR     B
      OR     C
      OR     D
      OR     E
      OR     H
      OR     L
      OR     (HL)
      OR     A
      CP     B
      CP     C
      CP     D
      CP     E
      CP     H
      CP     L
      CP     (HL)
      CP     A
      RET    NZ
      POP    BC
      JP     NZ, 0C4C3H
      JP     0C5C4H
      CALL   NZ, 0C6C5H
      PUSH   BC
      ADD    A, 0C7H
      RST    0
      RET    Z
      RET
      JP     Z, 0CCCBH
      SET    1, H
      SET    1, L
      SET    1, (HL)
      SET    1, A
      SET    2, B
      SET    2, C
      SET    2, D
      SET    2, E
      RLC    B
      RLC    C
      RLC    D
      RLC    E
      RLC    H
      RLC    L
      RLC    (HL)
      RLC    A
      RRC    B
      RRC    C
      RRC    D
      RRC    E
      RRC    H
      RRC    L
      RRC    (HL)
      RRC    A
      RL     B
      RL     C
      RL     D
      RL     E
      RL     H
      RL     L
      RL     (HL)
      RL     A
      RR     B
      RR     C
      RR     D
      RR     E
      RR     H
      RR     L
      RR     (HL)
      RR     A
      SLA    B
      SLA    C
      SLA    D
      SLA    E
      SLA    H
      SLA    L
      SLA    (HL)
      SLA    A
      SRA    B
      SRA    C
      SRA    D
      SRA    E
      SRA    H
      SRA    L
      SRA    (HL)
      SRA    A
      EX     B, B'
      EX     C, C'
      EX     D, D'
      EX     E, E'
      EX     H, H'
      EX     L, L'
      EX     A, A'
      SRL    B
      SRL    C
      SRL    D
      SRL    E
      SRL    H
      SRL    L
      SRL    (HL)
      SRL    A
      BIT    0, B
      BIT    0, C
      BIT    0, D
      BIT    0, E
      BIT    0, H
      BIT    0, L
      BIT    0, (HL)
      BIT    0, A
      RES    0, B
      RES    0, C
      RES    0, D
      RES    0, E
      RES    0, H
      RES    0, L
      RES    0, (HL)
      RES    0, A
      CALL   Z, 0CECDH
      CALL   0CFCEH
      ADC    A, 0CFH
      RET    NC
      POP    DE
      JP     NC, 0D4D3H
      OUT    (0D4H), A
      CALL   NC, 0D6D5H
      PUSH   DE
      SUB    0D7H
      RET    C
      EXX
      JP     C, 0DCDBH
      IN     A, (0DCH)
      CALL   C, 0DEDDH
      SBCW   HL, (IX-33)
      SBCW   HL, (IX+0)
      POP    IX
      EX     (SP), IX
      CALR   PO, $-0217H
      PUSH   IX
      ANDW   HL, (IX-25)
      ANDW   HL, (IX+0)
      JP     (IX)
      CALR   PE, $-020FH
      XORW   HL, (IX-17)
      XORW   HL, (IX+0)
      DI     0F4H
      CALR   P, $-0207H
      ORW    HL, (IX-9)
      ORW    HL, (IX+0)
      SETC   LW
      LD     SP, IX
      EI     0FCH
      CALR   M, $-00FFH
      CPW    HL, (IX-1)
      CPW    HL, (IX+0)
      RESC   LW
      LDW    (BC), IX
      LDW    BC, DE
      LDW    IX, (BC)
      LDW    IX, BC
      ADD    IX, BC
      LDW    BC, IX
      LDW    BC, (BC)
      LDW    BC, (DE)
      LDW    BC, (HL)
      DJNZ   $+1215H
      LDW    (DE), IX
      LDW    DE, DE
      LDW    IX, (DE)
      LDW    IX, DE
      JR     $+1A1DH
      ADD    IX, DE
      LDW    DE, IX
      LDW    DE, (BC)
      LDW    DE, (DE)
      LDW    DE, (HL)
      JR     NZ, $+2225H
      LD     IX, 2322H
      LD     (2423H), IX
      INC    IX
      INC    IXU
      DEC    IXU
      LD     IXU, 27H
      LDW    IX, IY
      JR     Z, $+2A2DH
      ADD    IX, IX
      LD     IX, (2C2BH)
      DEC    IX
      INC    IXL
      DEC    IXL
      LD     IXL, 2FH
      CPLW   HL
      JR     NC, $+3235H
      LDW    (HL), IX
      LDW    HL, DE
      LDW    IX, (HL)
      INC    (IX+53)
      INC    (IX-128)
      DEC    (IX+54)
      DEC    (IX-128)
      LD     (IX+55), 38H
      LD     (IX-128), 81H
      LDW    IX, HL
      JR     C, $+3A3DH
      ADD    IX, SP
      LDW    HL, IX
      LDW    HL, (BC)
      LDW    HL, (DE)
      SWAP   IX
      LDW    HL, (HL)
      INW    BC, (C)
      OUTW   (C), BC
      LD     B, IXU
      LD     B, IXL
      LD     B, (IX+71)
      LD     B, (IX-128)
      LDW    I, HL
      LD     C, IXU
      LD     C, IXL
      LD     C, (IX+79)
      LD     C, (IX-128)
      INW    DE, (C)
      OUTW   (C), DE
      LD     D, IXU
      LD     D, IXL
      LD     D, (IX+87)
      LD     D, (IX-128)
      LDW    HL, I
      LD     E, IXU
      LD     E, IXL
      LD     E, (IX+95)
      LD     E, (IX-128)
      LD     IXU, B
      LD     IXU, C
      LD     IXU, D
      LD     IXU, E
      LD     IXU, IXU
      LD     IXU, IXL
      LD     H, (IX+103)
      LD     H, (IX-128)
      LD     IXU, A
      LD     IXL, B
      LD     IXL, C
      LD     IXL, D
      LD     IXL, E
      LD     IXL, IXU
      LD     IXL, IXL
      LD     L, (IX+111)
      LD     L, (IX-128)
      LD     IXL, A
      LD     (IX+113), B
      LD     (IX-128), B
      LD     (IX+114), C
      LD     (IX-128), C
      LD     (IX+115), D
      LD     (IX-128), D
      LD     (IX+116), E
      LD     (IX-128), E
      LD     (IX+117), H
      LD     (IX-128), H
      LD     (IX+118), L
      LD     (IX-128), L
      LD     (IX+120), A
      LD     (IX-128), A
      INW    HL, (C)
      OUTW   (C), HL
      LD     A, IXU
      LD     A, IXL
      LD     A, (IX+127)
      LD     A, (IX-128)
      ADD    A, IXU
      ADD    A, IXL
      ADD    A, (IX-121)
      ADD    A, (IX+0)
      ADDW   HL, IX
      ADC    A, IXU
      ADC    A, IXL
      ADC    A, (IX-113)
      ADC    A, (IX+0)
      ADCW   HL, IX
      SUB    A, IXU
      SUB    A, IXL
      SUB    (IX-105)
      SUB    (IX+0)
      SUBW   HL, IX
      SBC    A, IXU
      SBC    A, IXL
      SBC    A, (IX-97)
      SBC    A, (IX+0)
      SBCW   HL, IX
      AND    A, IXU
      AND    A, IXL
      AND    (IX-89)
      AND    (IX+0)
      ANDW   HL, IX
      XOR    A, IXU
      XOR    A, IXL
      XOR    (IX-81)
      XOR    (IX+0)
      XORW   HL, IX
      OR     A, IXU
      OR     A, IXL
      OR     (IX-73)
      OR     (IX+0)
      ORW    HL, IX
      CP     A, IXU
      CP     A, IXL
      CP     (IX-65)
      CP     (IX+0)
      CPW    HL, IX
      DDIR
      CALR   NZ, $-0437H
      ADDW   HL, (IX-57)
      ADDW   HL, (IX+0)
      LDCTL  SR, A
      LDCTL  SR, 0CBH
      SET    1, (IX-52)
      LDW    BC, (SP-52)
      RLCW   (IX-52)
      LDW    BC, (IX-52)
      RLC    (IX-52)
      LDW    (SP-52), BC
      RRCW   (IX-52)
      LDW    (IX-52), BC
      RRC    (IX-52)
      LDW    DE, (SP-52)
      RLW    (IX-52)
      LDW    DE, (IX-52)
      RL     (IX-52)
      LDW    (SP-52), DE
      RRW    (IX-52)
      LDW    (IX-52), DE
      RR     (IX-52)
      LDW    IX, (SP-52)
      SLAW   (IX-52)
      LDW    IY, (IX-52)
      SLA    (IX-52)
      LDW    (SP-52), IX
      SRAW   (IX-52)
      LDW    (IX-52), IY
      SRA    (IX-52)
      LDW    HL, (SP-52)
      LDW    HL, (IX-52)
      LDW    (SP-52), HL
      SRLW   (IX-52)
      LDW    (IX-52), HL
      SRL    (IX-52)
      BIT    0, (IX-52)
      RES    0, (IX-52)
      MULTW  HL, (IX-52)
      MULTUW HL, (IX-52)
      DIVUW  HL, (IX-52)
      LDW    BC, (SP+0)
      RLCW   (IX+0)
      LDW    BC, (IX+0)
      RLC    (IX+0)
      LDW    (SP+0), BC
      RRCW   (IX+0)
      LDW    (IX+0), BC
      RRC    (IX+0)
      LDW    DE, (SP+0)
      RLW    (IX+0)
      LDW    DE, (IX+0)
      RL     (IX+0)
      LDW    (SP+0), DE
      RRW    (IX+0)
      LDW    (IX+0), DE
      RR     (IX+0)
      LDW    IX, (SP+0)
      SLAW   (IX+0)
      LDW    IY, (IX+0)
      SLA    (IX+0)
      LDW    (SP+0), IX
      SRAW   (IX+0)
      LDW    (IX+0), IY
      SRA    (IX+0)
      LDW    HL, (SP+0)
      LDW    HL, (IX+0)
      LDW    (SP+0), HL
      SRLW   (IX+0)
      LDW    (IX+0), HL
      SRL    (IX+0)
      BIT    0, (IX+0)
      RES    0, (IX+0)
      MULTW  HL, (IX+0)
      MULTUW HL, (IX+0)
      DIVUW  HL, (IX+0)
      SET    0, (IX+0)
      CALR   Z, $-052FH
      CALR   $-052EH
      ADCW   HL, (IX-49)
      ADCW   HL, (IX+0)
      MTEST
      LDCTL  A, XSR
      CALR   NC, $-0527H
      SUBW   HL, (IX-41)
      SUBW   HL, (IX+0)
      LDCTL  XSR, A
      EXXX
      LDCTL  XSR, 0DBH
      CALR   C, $-051FH
      SBC    A, 0DFH
      RET    PO
      POP    HL
      JP     PO, 0E4E3H
      EX     (SP), HL
      CALL   PO, 0E6E5H
      PUSH   HL
      AND    0E7H
      RET    PE
      JP     (HL)
      JP     PE, 0ECEBH
      EX     DE, HL
      CALL   PE, 0EEEDH
      LDIRW
      INIRW
      OTIRW
      CALR   P, $-8
      SETC   LCK
      LDDRW
      INDRW
      OTDRW
      CALR   M, $
      RESC   LCK
      IN0    B, (1)
      OUT0   (2), B
      LDW    BC, BC
      EX     BC, IX
      TST    B
      EX     BC, DE
      LDW    (BC), 0807H
      EX     A, B
      IN0    C, (9)
      OUT0   (10), C
      EX     BC, IY
      TST    C
      EX     BC, HL
      SWAP   BC
      EX     A, C
      IN0    D, (17)
      OUT0   (18), D
      LDW    DE, BC
      EX     DE, IX
      TST    D
      LDW    (DE), 1817H
      EX     A, D
      IN0    E, (25)
      OUT0   (26), E
      EX     DE, IY
      TST    E
      SWAP   DE
      EX     A, E
      IN0    H, (21H)
      OUT0   (22H), H
      TST    H
      EX     A, H
      IN0    L, (29H)
      OUT0   (2AH), L
      EX     IX, IY
      TST    L
      EX     A, L
      IN0    (31H)
      LDW    HL, BC
      EX     HL, IX
      TST    (HL)
      LDW    (HL), 3837H
      EX     A, (HL)
      IN0    A, (39H)
      OUT0   (3AH), A
      EX     HL, IY
      TST    A
      SWAP   HL
      EX     A, A
      IN     B, (C)
      OUT    (C), B
      SBC    HL, BC
      LD     (4544H), BC
      NEG
      RETN
      IM     0
      LD     I, A
      IN     C, (C)
      OUT    (C), C
      ADC    HL, BC
      LD     BC, (4D4CH)
      MLT    BC
      RETI
      LD     R, A
      IN     D, (C)
      OUT    (C), D
      SBC    HL, DE
      LD     (5554H), DE
      NEGW   HL
      RETB
      LD     A, I
      IN     E, (C)
      OUT    (C), E
      ADC    HL, DE
      LD     DE, (5D5CH)
      MLT    DE
      LD     A, R
      IN     H, (C)
      OUT    (C), H
      SBC    HL, HL
      LDW    (6564H), HL
      TST    65H
      EXTS   A
      RRD
      IN     L, (C)
      OUT    (C), L
      ADC    HL, HL
      LDW    HL, (6D6CH)
      MLT    HL
      RLD
      OUT    (C), 72H
      SBC    HL, SP
      LD     (7574H), SP
      TSTIO  75H
      EXTSW  HL
      SLP
      IN     A, (C)
      OUT    (C), A
      ADC    HL, SP
      LD     SP, (7D7CH)
      MLT    SP
      ADD    SP, 8483H
      OTIM
      ADDW   HL, BC
      ADDW   HL, DE
      ADDW   HL, 8887H
      ADDW   HL, HL
      OTDM
      ADCW   HL, BC
      ADCW   HL, DE
      ADCW   HL, 908FH
      ADCW   HL, HL
      SUB    SP, 9493H
      OTIMR
      SUBW   HL, BC
      SUBW   HL, DE
      SUBW   HL, 9897H
      SUBW   HL, HL
      OTDMR
      SBCW   HL, BC
      SBCW   HL, DE
      SBCW   HL, 0A09FH
      SBCW   HL, HL
      LDI
      CPI
      INI
      OUTI
      ANDW   HL, BC
      ANDW   HL, DE
      ANDW   HL, 0A8A7H
      ANDW   HL, HL
      LDD
      CPD
      IND
      OUTD
      XORW   HL, BC
      XORW   HL, DE
      XORW   HL, 0B0AFH
      XORW   HL, HL
      LDIR
      CPIR
      INIR
      OTIR
      ORW    HL, BC
      ORW    HL, DE
      ORW    HL, 0B8B7H
      ORW    HL, HL
      LDDR
      CPDR
      INDR
      OTDR
      CPW    HL, BC
      CPW    HL, DE
      CPW    HL, 0C0BFH
      CPW    HL, HL
      LDCTL  HL, SR
      POP    SR
      CALR   NZ, $-56
      PUSH   SR
      ADD    HL, (0C8C7H)
      LDCTL  SR, HL
      RLCW   BC
      RLCW   DE
      RLCW   (HL)
      RLCW   HL
      RLCW   IX
      RLCW   IY
      RRCW   BC
      RRCW   DE
      RRCW   (HL)
      RRCW   HL
      RRCW   IX
      RRCW   IY
      RLW    BC
      RLW    DE
      RLW    (HL)
      RLW    HL
      RLW    IX
      RLW    IY
      RRW    BC
      RRW    DE
      RRW    (HL)
      RRW    HL
      RRW    IX
      RRW    IY
      SLAW   BC
      SLAW   DE
      SLAW   (HL)
      SLAW   HL
      SLAW   IX
      SLAW   IY
      SRAW   BC
      SRAW   DE
      SRAW   (HL)
      SRAW   HL
      SRAW   IX
      SRAW   IY
      EX     BC, BC'
      EX     DE, DE'
      EX     HL, HL'
      EX     IX, IX'
      EX     IY, IY'
      SRLW   BC
      SRLW   DE
      SRLW   (HL)
      SRLW   HL
      SRLW   IX
      SRLW   IY
      MULTW  HL, BC
      MULTW  HL, DE
      MULTW  HL, HL
      MULTW  HL, IX
      MULTW  HL, IY
      MULTW  HL, 9998H
      MULTUW HL, BC
      MULTUW HL, DE
      MULTUW HL, HL
      MULTUW HL, IX
      MULTUW HL, IY
      MULTUW HL, 0A1A0H
      DIVUW  HL, BC
      DIVUW  HL, DE
      DIVUW  HL, HL
      DIVUW  HL, IX
      DIVUW  HL, IY
      DIVUW  HL, 0C1C0H
      CALR   Z, $-48
      CALR   $-47
      BTEST
      LDCTL  A, DSR
      OUTA   (0D5D4H), A
      CALR   NC, $-40
      SUB    HL, (0D8D7H)
      LDCTL  DSR, A
      EXALL
      LDCTL  DSR, 0DBH
      INA    A, (0DDDCH)
      CALR   C, $-32
      LDIW
      INIW
      OUTIW
      CALR   PO, $-24
      LDDW
      INDW
      OUTDW
      CALR   PE, $-16
      XOR    0EFH
      RET    P
      POP    AF
      JP     P, 0F4F3H
      DI
      CALL   P, 0F6F5H
      PUSH   AF
      OR     0F7H
      RET    M
      LD     SP, HL
      JP     M, 0FCFBH
      EI
      CALL   M, 0FEFDH
      CPW    HL, (IY-1)
      CPW    HL, (IY+0)
      LDW    (BC), IY
      LDW    BC, HL
      LDW    IY, (BC)
      LDW    IY, BC
      ADD    IY, BC
      LDW    BC, IY
      LDW    (BC), BC
      LDW    (DE), BC
      LDW    (HL), BC
      DJNZ   $+001216H
      LDW    (DE), IY
      LDW    DE, HL
      LDW    IY, (DE)
      LDW    IY, DE
      JR     $+001A1EH
      ADD    IY, DE
      LDW    DE, IY
      LDW    (BC), DE
      LDW    (DE), DE
      LDW    (HL), DE
      JR     NZ, $+002226H
      LD     IY, 2322H
      LD     (2423H), IY
      INC    IY
      INC    IYU
      DEC    IYU
      LD     IYU, 27H
      LDW    IY, IX
      JR     Z, $+002A2EH
      ADD    IY, IY
      LD     IY, (2C2BH)
      DEC    IY
      INC    IYL
      DEC    IYL
      LD     IYL, 2FH
      JR     NC, $+003236H
      LDW    (HL), IY
      LDW    HL, HL
      LDW    IY, (HL)
      INC    (IY+53)
      INC    (IY-128)
      DEC    (IY+54)
      DEC    (IY-128)
      LD     (IY+55), 38H
      LD     (IY-128), 81H
      LDW    IY, HL
      JR     C, $+003A3EH
      ADD    IY, SP
      LDW    HL, IY
      LDW    (BC), HL
      LDW    (DE), HL
      SWAP   IY
      LDW    (HL), HL
      LD     B, IYU
      LD     B, IYL
      LD     B, (IY+71)
      LD     B, (IY-128)
      LD     C, IYU
      LD     C, IYL
      LD     C, (IY+79)
      LD     C, (IY-128)
      LD     D, IYU
      LD     D, IYL
      LD     D, (IY+87)
      LD     D, (IY-128)
      LD     E, IYU
      LD     E, IYL
      LD     E, (IY+95)
      LD     E, (IY-128)
      LD     IYU, B
      LD     IYU, C
      LD     IYU, D
      LD     IYU, E
      LD     IYU, IYU
      LD     IYU, IYL
      LD     H, (IY+103)
      LD     H, (IY-128)
      LD     IYU, A
      LD     IYL, B
      LD     IYL, C
      LD     IYL, D
      LD     IYL, E
      LD     IYL, IYU
      LD     IYL, IYL
      LD     L, (IY+111)
      LD     L, (IY-128)
      LD     IYL, A
      LD     (IY+113), B
      LD     (IY-128), B
      LD     (IY+114), C
      LD     (IY-128), C
      LD     (IY+115), D
      LD     (IY-128), D
      LD     (IY+116), E
      LD     (IY-128), E
      LD     (IY+117), H
      LD     (IY-128), H
      LD     (IY+118), L
      LD     (IY-128), L
      LD     (IY+120), A
      LD     (IY-128), A
      OUTW   (C), 7B7AH
      LD     A, IYU
      LD     A, IYL
      LD     A, (IY+127)
      LD     A, (IY-128)
      ADD    A, IYU
      ADD    A, IYL
      ADD    A, (IY-121)
      ADD    A, (IY+0)
      ADDW   HL, IY
      ADC    A, IYU
      ADC    A, IYL
      ADC    A, (IY-113)
      ADC    A, (IY+0)
      ADCW   HL, IY
      SUB    A, IYU
      SUB    A, IYL
      SUB    (IY-105)
      SUB    (IY+0)
      SUBW   HL, IY
      SBC    A, IYU
      SBC    A, IYL
      SBC    A, (IY-97)
      SBC    A, (IY+0)
      SBCW   HL, IY
      AND    A, IYU
      AND    A, IYL
      AND    (IY-89)
      AND    (IY+0)
      ANDW   HL, IY
      XOR    A, IYU
      XOR    A, IYL
      XOR    (IY-81)
      XOR    (IY+0)
      XORW   HL, IY
      OR     A, IYU
      OR     A, IYL
      OR     (IY-73)
      OR     (IY+0)
      ORW    HL, IY
      CP     A, IYU
      CP     A, IYL
      CP     (IY-65)
      CP     (IY+0)
      CPW    HL, IY
      CALR   NZ, $+00C6CAH
      ADDW   HL, (IY-57)
      ADDW   HL, (IY+0)
      SET    1, (IY-52)
      RLCW   (IY-52)
      LDW    BC, (IY-52)
      RLC    (IY-52)
      RRCW   (IY-52)
      LDW    (IY-52), BC
      RRC    (IY-52)
      RLW    (IY-52)
      LDW    DE, (IY-52)
      RL     (IY-52)
      RRW    (IY-52)
      LDW    (IY-52), DE
      RR     (IY-52)
      LDW    IY, (SP-52)
      SLAW   (IY-52)
      LDW    IX, (IY-52)
      SLA    (IY-52)
      LDW    (SP-52), IY
      SRAW   (IY-52)
      LDW    (IY-52), IX
      SRA    (IY-52)
      LDW    HL, (IY-52)
      SRLW   (IY-52)
      LDW    (IY-52), HL
      SRL    (IY-52)
      BIT    0, (IY-52)
      RES    0, (IY-52)
      MULTW  HL, (IY-52)
      MULTUW HL, (IY-52)
      DIVUW  HL, (IY-52)
      RLCW   (IY+0)
      LDW    BC, (IY+0)
      RLC    (IY+0)
      RRCW   (IY+0)
      LDW    (IY+0), BC
      RRC    (IY+0)
      RLW    (IY+0)
      LDW    DE, (IY+0)
      RL     (IY+0)
      RRW    (IY+0)
      LDW    (IY+0), DE
      RR     (IY+0)
      LDW    IY, (SP+0)
      SLAW   (IY+0)
      LDW    IX, (IY+0)
      SLA    (IY+0)
      LDW    (SP+0), IY
      SRAW   (IY+0)
      LDW    (IY+0), IX
      SRA    (IY+0)
      LDW    HL, (IY+0)
      SRLW   (IY+0)
      LDW    (IY+0), HL
      SRL    (IY+0)
      BIT    0, (IY+0)
      RES    0, (IY+0)
      MULTW  HL, (IY+0)
      MULTUW HL, (IY+0)
      DIVUW  HL, (IY+0)
      SET    0, (IY+0)
      CALR   Z, $+00CED2H
      CALR   $+00CFD3H
      ADCW   HL, (IY-49)
      ADCW   HL, (IY+0)
      LDCTL  A, YSR
      OUTAW  (0D5D4H), HL
      CALR   NC, $+00D6DAH
      SUBW   HL, (IY-41)
      SUBW   HL, (IY+0)
      LDCTL  YSR, A
      EXXY
      LDCTL  YSR, 0DBH
      INAW   HL, (0DDDCH)
      CALR   C, $+00DEE2H
      SBCW   HL, (IY-33)
      SBCW   HL, (IY+0)
      POP    IY
      EX     (SP), IY
      CALR   PO, $+00E6EAH
      PUSH   IY
      ANDW   HL, (IY-25)
      ANDW   HL, (IY+0)
      JP     (IY)
      CALR   PE, $+00EEF2H
      XORW   HL, (IY-17)
      XORW   HL, (IY+0)
      CALR   P, $-000906H
      PUSH   0F7F6H
      ORW    HL, (IY-9)
      ORW    HL, (IY+0)
      SETC   XM
      LD     SP, IY
      CALR   M, $-0000FEH
      CP     0FFH
