;;; AUTO GENERATED FILE
;;; generated by: gen_ins8070 -u -C 8070 -o gen_ins8070.asm -l gen_ins8070.lst
      CPU   8070
      ORG   0100H
      NOP
      XCH   A, E
      LD    A, S
      LD    S, A
      PUSH  EA
      LD    T, EA
      PUSH  A
      LD    EA, T
      SR    EA
      DIV   EA, T
      SL    A
      SL    EA
      CALL  0
      JSR   2222H
      PLI   P2, #2423H
      JMP   2626H
      LD    SP, #2726H
      LD    P2, #2827H
      MPY   EA, T
      BND   $+48
      BND   $-126
      BND   $
      SSM   P2
      LD    EA, PC
      LD    EA, SP
      LD    EA, P2
      POP   A
      AND   S, #3AH
      POP   EA
      OR    S, #3CH
      SR    A
      SRL   A
      RR    A
      RRL   A
      LD    A, E
      LD    PC, EA
      LD    SP, EA
      LD    P2, EA
      LD    E, A
      XCH   EA, PC
      XCH   EA, SP
      XCH   EA, P2
      AND   A, E
      PUSH  PC
      PUSH  P2
      OR    A, E
      RET
      POP   P2
      XOR   A, E
      BP    $+103
      BP    $-126
      BP    $
      BP    103,P2
      BP    -128,P2
      BZ    $+111
      BZ    $-126
      BZ    $
      BZ    111,P2
      BZ    -128,P2
      ADD   A, E
      BRA   $+119
      BRA   $-126
      BRA   $
      BRA   119,P2
      BRA   -128,P2
      SUB   A, E
      BNZ   $+127
      BNZ   $-126
      BNZ   $
      BNZ   127,P2
      BNZ   -128,P2
      LD    EA, $-126
      LD    EA, $
      LD    EA, $+1
      LD    EA, -126,SP
      LD    EA, 0,SP
      LD    EA, -125,P2
      LD    EA, 0,P2
      LD    EA, #8685H
      LD    EA, 0FF86H
      LD    EA, @-121,P2
      LD    EA, @0,P2
      ST    EA, $-118
      ST    EA, $
      ST    EA, $+1
      ST    EA, -118,SP
      ST    EA, 0,SP
      ST    EA, -117,P2
      ST    EA, 0,P2
      ST    EA, 0FF8EH
      ST    EA, @-113,P2
      ST    EA, @0,P2
      ILD   A, $-110
      ILD   A, $
      ILD   A, $+1
      ILD   A, -110,SP
      ILD   A, 0,SP
      ILD   A, -109,P2
      ILD   A, 0,P2
      ILD   A, 0FF96H
      ILD   A, @-105,P2
      ILD   A, @0,P2
      DLD   A, $-102
      DLD   A, $
      DLD   A, $+1
      DLD   A, -102,SP
      DLD   A, 0,SP
      DLD   A, -101,P2
      DLD   A, 0,P2
      DLD   A, 0FF9EH
      DLD   A, @-97,P2
      DLD   A, @0,P2
      LD    T, $-94
      LD    T, $
      LD    T, $+1
      LD    T, -94,SP
      LD    T, 0,SP
      LD    T, -93,P2
      LD    T, 0,P2
      LD    T, #0A6A5H
      LD    T, 0FFA6H
      LD    T, @-89,P2
      LD    T, @0,P2
      ADD   EA, $-78
      ADD   EA, $
      ADD   EA, $+1
      ADD   EA, -78,SP
      ADD   EA, 0,SP
      ADD   EA, -77,P2
      ADD   EA, 0,P2
      ADD   EA, #0B6B5H
      ADD   EA, 0FFB6H
      ADD   EA, @-73,P2
      ADD   EA, @0,P2
      SUB   EA, $-70
      SUB   EA, $
      SUB   EA, $+1
      SUB   EA, -70,SP
      SUB   EA, 0,SP
      SUB   EA, -69,P2
      SUB   EA, 0,P2
      SUB   EA, #0BEBDH
      SUB   EA, 0FFBEH
      SUB   EA, @-65,P2
      SUB   EA, @0,P2
      LD    A, $-62
      LD    A, $
      LD    A, $+1
      LD    A, -62,SP
      LD    A, 0,SP
      LD    A, -61,P2
      LD    A, 0,P2
      LD    A, #0C5H
      LD    A, 0FFC6H
      LD    A, @-57,P2
      LD    A, @0,P2
      ST    A, $-54
      ST    A, $
      ST    A, $+1
      ST    A, -54,SP
      ST    A, 0,SP
      ST    A, -53,P2
      ST    A, 0,P2
      ST    A, 0FFCEH
      ST    A, @-49,P2
      ST    A, @0,P2
      AND   A, $-46
      AND   A, $
      AND   A, $+1
      AND   A, -46,SP
      AND   A, 0,SP
      AND   A, -45,P2
      AND   A, 0,P2
      AND   A, #0D5H
      AND   A, 0FFD6H
      AND   A, @-41,P2
      AND   A, @0,P2
      OR    A, $-38
      OR    A, $
      OR    A, $+1
      OR    A, -38,SP
      OR    A, 0,SP
      OR    A, -37,P2
      OR    A, 0,P2
      OR    A, #0DDH
      OR    A, 0FFDEH
      OR    A, @-33,P2
      OR    A, @0,P2
      XOR   A, $-30
      XOR   A, $
      XOR   A, $+1
      XOR   A, -30,SP
      XOR   A, 0,SP
      XOR   A, -29,P2
      XOR   A, 0,P2
      XOR   A, #0E5H
      XOR   A, 0FFE6H
      XOR   A, @-25,P2
      XOR   A, @0,P2
      ADD   A, $-14
      ADD   A, $
      ADD   A, $+1
      ADD   A, -14,SP
      ADD   A, 0,SP
      ADD   A, -13,P2
      ADD   A, 0,P2
      ADD   A, #0F5H
      ADD   A, 0FFF6H
      ADD   A, @-9,P2
      ADD   A, @0,P2
      SUB   A, $-6
      SUB   A, $
      SUB   A, $+1
      SUB   A, -6,SP
      SUB   A, 0,SP
      SUB   A, -5,P2
      SUB   A, 0,P2
      SUB   A, #0FDH
      SUB   A, 0FFFEH
      SUB   A, @-1,P2
      SUB   A, @0,P2
