;;; AUTO GENERATED FILE
;;; generated by: gen_mc6805 -u -C 68HC05 -o gen_mc68hc05.asm -l gen_mc68hc05.lst
      CPU   68HC05
      ORG   $0100
      BRSET 0, $01, *+5
      BRSET 0, $01, *-125
      BRSET 0, $01, *
      BRCLR 0, $02, *+6
      BRCLR 0, $02, *-125
      BRCLR 0, $02, *
      BSET  0, $11
      BCLR  0, $12
      BRA   *+35
      BRA   *-126
      BRA   *
      BRN   *+36
      BRN   *-126
      BRN   *
      BHI   *+37
      BHI   *-126
      BHI   *
      BLS   *+38
      BLS   *-126
      BLS   *
      BHS   *+39
      BHS   *-126
      BHS   *
      BLO   *+40
      BLO   *-126
      BLO   *
      BNE   *+41
      BNE   *-126
      BNE   *
      BEQ   *+42
      BEQ   *-126
      BEQ   *
      BHCC  *+43
      BHCC  *-126
      BHCC  *
      BHCS  *+44
      BHCS  *-126
      BHCS  *
      BPL   *+45
      BPL   *-126
      BPL   *
      BMI   *+46
      BMI   *-126
      BMI   *
      BMC   *+47
      BMC   *-126
      BMC   *
      BMS   *+48
      BMS   *-126
      BMS   *
      BIL   *+49
      BIL   *-126
      BIL   *
      BIH   *+50
      BIH   *-126
      BIH   *
      NEG   $31
      COM   $34
      LSR   $35
      ROR   $37
      ASR   $38
      ASL   $39
      ROL   $3A
      DEC   $3B
      INC   $3D
      TST   $3E
      CLR   $40
      NEGA
      MUL
      COMA
      LSRA
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      INCA
      TSTA
      CLRA
      NEGX
      COMX
      LSRX
      RORX
      ASRX
      ASLX
      ROLX
      DECX
      INCX
      TSTX
      CLRX
      NEG   97,X
      NEG   <0,X
      COM   100,X
      COM   <0,X
      LSR   101,X
      LSR   <0,X
      ROR   103,X
      ROR   <0,X
      ASR   104,X
      ASR   <0,X
      ASL   105,X
      ASL   <0,X
      ROL   106,X
      ROL   <0,X
      DEC   107,X
      DEC   <0,X
      INC   109,X
      INC   <0,X
      TST   110,X
      TST   <0,X
      CLR   112,X
      CLR   <0,X
      NEG   ,X
      COM   ,X
      LSR   ,X
      ROR   ,X
      ASR   ,X
      ASL   ,X
      ROL   ,X
      DEC   ,X
      INC   ,X
      TST   ,X
      CLR   ,X
      RTI
      RTS
      SWI
      STOP
      WAIT
      TAX
      CLC
      SEC
      CLI
      SEI
      RSP
      NOP
      TXA
      SUB   #$A1
      CMP   #$A2
      SBC   #$A3
      CPX   #$A4
      AND   #$A5
      BIT   #$A6
      LDA   #$A7
      EOR   #$A9
      ADC   #$AA
      ORA   #$AB
      ADD   #$AC
      BSR   *-80
      BSR   *
      BSR   *+1
      LDX   #$AF
      SUB   $B1
      CMP   $B2
      SBC   $B3
      CPX   $B4
      AND   $B5
      BIT   $B6
      LDA   $B7
      STA   $B8
      EOR   $B9
      ADC   $BA
      ORA   $BB
      ADD   $BC
      JMP   $BD
      JSR   $BE
      LDX   $BF
      STX   $C0
      SUB   >$0001
      SUB   $0102
      CMP   >$0001
      CMP   $0102
      SBC   >$0001
      SBC   $0102
      CPX   >$0001
      CPX   $0102
      AND   >$0001
      AND   $0102
      BIT   >$0001
      BIT   $0102
      LDA   >$0001
      LDA   $0102
      STA   >$0001
      STA   $0102
      EOR   >$0001
      EOR   $0102
      ADC   >$0001
      ADC   $0102
      ORA   >$0001
      ORA   $0102
      ADD   >$0001
      ADD   $0102
      JMP   >$0001
      JMP   $0102
      JSR   >$0001
      JSR   $0102
      LDX   >$0001
      LDX   $0102
      STX   >$0001
      STX   $0102
      SUB   $D1D2,X
      SUB   >$0001,X
      CMP   $D2D3,X
      CMP   >$0001,X
      SBC   $D3D4,X
      SBC   >$0001,X
      CPX   $D4D5,X
      CPX   >$0001,X
      AND   $D5D6,X
      AND   >$0001,X
      BIT   $D6D7,X
      BIT   >$0001,X
      LDA   $D7D8,X
      LDA   >$0001,X
      STA   $D8D9,X
      STA   >$0001,X
      EOR   $D9DA,X
      EOR   >$0001,X
      ADC   $DADB,X
      ADC   >$0001,X
      ORA   $DBDC,X
      ORA   >$0001,X
      ADD   $DCDD,X
      ADD   >$0001,X
      JMP   $DDDE,X
      JMP   >$0001,X
      JSR   $DEDF,X
      JSR   >$0001,X
      LDX   $DFE0,X
      LDX   >$0001,X
      STX   $E0E1,X
      STX   >$0001,X
      SUB   225,X
      SUB   <0,X
      CMP   226,X
      CMP   <0,X
      SBC   227,X
      SBC   <0,X
      CPX   228,X
      CPX   <0,X
      AND   229,X
      AND   <0,X
      BIT   230,X
      BIT   <0,X
      LDA   231,X
      LDA   <0,X
      STA   232,X
      STA   <0,X
      EOR   233,X
      EOR   <0,X
      ADC   234,X
      ADC   <0,X
      ORA   235,X
      ORA   <0,X
      ADD   236,X
      ADD   <0,X
      JMP   237,X
      JMP   <0,X
      JSR   238,X
      JSR   <0,X
      LDX   239,X
      LDX   <0,X
      STX   240,X
      STX   <0,X
      SUB   ,X
      CMP   ,X
      SBC   ,X
      CPX   ,X
      AND   ,X
      BIT   ,X
      LDA   ,X
      STA   ,X
      EOR   ,X
      ADC   ,X
      ORA   ,X
      ADD   ,X
      JMP   ,X
      JSR   ,X
      LDX   ,X
      STX   ,X
