;;; AUTO GENERATED FILE
;;; generated by: gen_mc68hc16 -u -C 68HC16 -o gen_mc68hc16.asm -l gen_mc68hc16.lst
      CPU    68HC16
      ORG    $10000
      COM    1,X
      DEC    2,X
      NEG    3,X
      INC    4,X
      ASL    5,X
      CLR    6,X
      TST    7,X
      BCLR   $0A0B,X, #9
      BCLR   >$0001,X, #9
      BSET   $0B0C,X, #10
      BSET   >$0001,X, #10
      BRCLR  $0C0D,X, #11, *+$0E16
      BRCLR  >$0001,X, #11, *+$020A
      BRSET  $0D0E,X, #12, *+$0F16
      BRSET  >$0001,X, #12, *+$020A
      ROL    13,X
      ASR    14,X
      ROR    15,X
      LSR    16,X
      COM    17,Y
      DEC    18,Y
      NEG    19,Y
      INC    20,Y
      ASL    21,Y
      CLR    22,Y
      TST    23,Y
      BCLR   26,Y, #25
      BSET   27,Y, #26
      ROL    $1D1E,Y
      ROL    >$0001,Y
      ASR    $1E1F,Y
      ASR    >$0001,Y
      ROR    $1F20,Y
      ROR    >$0001,Y
      LSR    $2021,Y
      LSR    >$0001,Y
      COM    $2122,Z
      COM    >$0001,Z
      DEC    $2223,Z
      DEC    >$0001,Z
      NEG    $2324,Z
      NEG    >$0001,Z
      INC    $2425,Z
      INC    >$0001,Z
      ASL    $2526,Z
      ASL    >$0001,Z
      CLR    $2627,Z
      CLR    >$0001,Z
      TST    $2728,Z
      TST    >$0001,Z
      BCLR   $2A,Z, #$29
      BSET   $2B,Z, #$2A
      ROL    $2D2E,Z
      ROL    >$0001,Z
      ASR    $2E2F,Z
      ASR    >$0001,Z
      ROR    $2F30,Z
      ROR    >$0001,Z
      LSR    $3031,Z
      LSR    >$0001,Z
      COM    $3132
      DEC    $3233
      NEG    $3334
      INC    $3435
      ASL    $3536
      CLR    $3637
      TST    $3738
      ROL    $3D3E
      ASR    $3E3F
      ROR    $3F40
      LSR    $4041
      SUBA   $4142,X
      SUBA   >$0001,X
      ADDA   $4243,X
      ADDA   >$0001,X
      SBCA   $4344,X
      SBCA   >$0001,X
      ADCA   $4445,X
      ADCA   >$0001,X
      EORA   $4546,X
      EORA   >$0001,X
      LDAA   $4647,X
      LDAA   >$0001,X
      ANDA   $4748,X
      ANDA   >$0001,X
      ORAA   $4849,X
      ORAA   >$0001,X
      CMPA   $494A,X
      CMPA   >$0001,X
      BITA   $4A4B,X
      BITA   >$0001,X
      STAA   $4B4C,X
      STAA   >$0001,X
      CPX    $4D4E,X
      CPX    >$0001,X
      CPY    $4E4F,X
      CPY    >$0001,X
      CPZ    $4F50,X
      CPZ    >$0001,X
      CPS    $5051,X
      CPS    >$0001,X
      SUBA   $5152,Y
      SUBA   >$0001,Y
      ADDA   $5253,Y
      ADDA   >$0001,Y
      SBCA   $5354,Y
      SBCA   >$0001,Y
      ADCA   $5455,Y
      ADCA   >$0001,Y
      EORA   $5556,Y
      EORA   >$0001,Y
      LDAA   $5657,Y
      LDAA   >$0001,Y
      ANDA   $5758,Y
      ANDA   >$0001,Y
      ORAA   $5859,Y
      ORAA   >$0001,Y
      CMPA   $595A,Y
      CMPA   >$0001,Y
      BITA   $5A5B,Y
      BITA   >$0001,Y
      STAA   $5B5C,Y
      STAA   >$0001,Y
      CPX    $5D5E,Y
      CPX    >$0001,Y
      CPY    $5E5F,Y
      CPY    >$0001,Y
      CPZ    $5F60,Y
      CPZ    >$0001,Y
      CPS    $6061,Y
      CPS    >$0001,Y
      SUBA   $6162,Z
      SUBA   >$0001,Z
      ADDA   $6263,Z
      ADDA   >$0001,Z
      SBCA   $6364,Z
      SBCA   >$0001,Z
      ADCA   $6465,Z
      ADCA   >$0001,Z
      EORA   $6566,Z
      EORA   >$0001,Z
      LDAA   $6667,Z
      LDAA   >$0001,Z
      ANDA   $6768,Z
      ANDA   >$0001,Z
      ORAA   $6869,Z
      ORAA   >$0001,Z
      CMPA   $696A,Z
      CMPA   >$0001,Z
      BITA   $6A6B,Z
      BITA   >$0001,Z
      STAA   $6B6C,Z
      STAA   >$0001,Z
      CPX    $6D6E,Z
      CPX    >$0001,Z
      CPY    $6E6F,Z
      CPY    >$0001,Z
      CPZ    $6F70,Z
      CPZ    >$0001,Z
      CPS    $7071,Z
      CPS    >$0001,Z
      SUBA   $7172
      ADDA   $7273
      SBCA   $7374
      ADCA   $7475
      EORA   $7576
      LDAA   $7677
      ANDA   $7778
      ORAA   $7879
      CMPA   $797A
      BITA   $7A7B
      STAA   $7B7C
      CPX    $7D7E
      CPY    $7E7F
      CPZ    $7F80
      CPS    $8081
      STX    -$7272,X
      STX    >$0001,X
      STY    -$7171,X
      STY    >$0001,X
      STZ    -$7070,X
      STZ    >$0001,X
      STS    -$6F6F,X
      STS    >$0001,X
      STX    -$6262,Y
      STX    >$0001,Y
      STY    -$6161,Y
      STY    >$0001,Y
      STZ    -$6060,Y
      STZ    >$0001,Y
      STS    -$5F5F,Y
      STS    >$0001,Y
      STX    -$5252,Z
      STX    >$0001,Z
      STY    -$5151,Z
      STY    >$0001,Z
      STZ    -$5050,Z
      STZ    >$0001,Z
      STS    -$4F4F,Z
      STS    >$0001,Z
      STX    $BDBE
      STY    $BEBF
      STZ    $BFC0
      STS    $C0C1
      SUBB   -$3E3E,X
      SUBB   >$0001,X
      ADDB   -$3D3D,X
      ADDB   >$0001,X
      SBCB   -$3C3C,X
      SBCB   >$0001,X
      ADCB   -$3B3B,X
      ADCB   >$0001,X
      EORB   -$3A3A,X
      EORB   >$0001,X
      LDAB   -$3939,X
      LDAB   >$0001,X
      ANDB   -$3838,X
      ANDB   >$0001,X
      ORAB   -$3737,X
      ORAB   >$0001,X
      CMPB   -$3636,X
      CMPB   >$0001,X
      BITB   -$3535,X
      BITB   >$0001,X
      STAB   -$3434,X
      STAB   >$0001,X
      LDX    -$3232,X
      LDX    >$0001,X
      LDY    -$3131,X
      LDY    >$0001,X
      LDZ    -$3030,X
      LDZ    >$0001,X
      LDS    -$2F2F,X
      LDS    >$0001,X
      SUBB   -$2E2E,Y
      SUBB   >$0001,Y
      ADDB   -$2D2D,Y
      ADDB   >$0001,Y
      SBCB   -$2C2C,Y
      SBCB   >$0001,Y
      ADCB   -$2B2B,Y
      ADCB   >$0001,Y
      EORB   -$2A2A,Y
      EORB   >$0001,Y
      LDAB   -$2929,Y
      LDAB   >$0001,Y
      ANDB   -$2828,Y
      ANDB   >$0001,Y
      ORAB   -$2727,Y
      ORAB   >$0001,Y
      CMPB   -$2626,Y
      CMPB   >$0001,Y
      BITB   -$2525,Y
      BITB   >$0001,Y
      STAB   -$2424,Y
      STAB   >$0001,Y
      LDX    -$2222,Y
      LDX    >$0001,Y
      LDY    -$2121,Y
      LDY    >$0001,Y
      LDZ    -$2020,Y
      LDZ    >$0001,Y
      LDS    -$1F1F,Y
      LDS    >$0001,Y
      SUBB   -$1E1E,Z
      SUBB   >$0001,Z
      ADDB   -$1D1D,Z
      ADDB   >$0001,Z
      SBCB   -$1C1C,Z
      SBCB   >$0001,Z
      ADCB   -$1B1B,Z
      ADCB   >$0001,Z
      EORB   -$1A1A,Z
      EORB   >$0001,Z
      LDAB   -$1919,Z
      LDAB   >$0001,Z
      ANDB   -$1818,Z
      ANDB   >$0001,Z
      ORAB   -$1717,Z
      ORAB   >$0001,Z
      CMPB   -$1616,Z
      CMPB   >$0001,Z
      BITB   -$1515,Z
      BITB   >$0001,Z
      STAB   -$1414,Z
      STAB   >$0001,Z
      LDX    -$1212,Z
      LDX    >$0001,Z
      LDY    -$1111,Z
      LDY    >$0001,Z
      LDZ    -$1010,Z
      LDZ    >$0001,Z
      LDS    -$0F0F,Z
      LDS    >$0001,Z
      SUBB   $F1F2
      ADDB   $F2F3
      SBCB   $F3F4
      ADCB   $F4F5
      EORB   $F5F6
      LDAB   $F6F7
      ANDB   $F7F8
      ORAB   $F8F9
      CMPB   $F9FA
      BITB   $FAFB
      STAB   $FBFC
      LDX    $FDFE
      LDY    $FEFF
      LDZ    $FF00
      LDS    $0001
      COM    $0102,X
      COM    >$0001,X
      DEC    $0203,X
      DEC    >$0001,X
      NEG    $0304,X
      NEG    >$0001,X
      INC    $0405,X
      INC    >$0001,X
      ASL    $0506,X
      ASL    >$0001,X
      CLR    $0607,X
      CLR    >$0001,X
      TST    $0708,X
      TST    >$0001,X
      ROL    $0D0E,X
      ROL    >$0001,X
      ASR    $0E0F,X
      ASR    >$0001,X
      ROR    $0F10,X
      ROR    >$0001,X
      LSR    $1011,X
      LSR    >$0001,X
      COM    $1112,Y
      COM    >$0001,Y
      DEC    $1213,Y
      DEC    >$0001,Y
      NEG    $1314,Y
      NEG    >$0001,Y
      INC    $1415,Y
      INC    >$0001,Y
      ASL    $1516,Y
      ASL    >$0001,Y
      CLR    $1617,Y
      CLR    >$0001,Y
      TST    $1718,Y
      TST    >$0001,Y
      BCLR   >$0001,Y, #$FF
      BSET   >$0001,Y, #$FF
      BRCLR  $1C1D,Y, #27, *+$1E26
      BRCLR  >$0001,Y, #27, *+$020A
      BRSET  $1D1E,Y, #28, *+$1F26
      BRSET  >$0001,Y, #28, *+$020A
      ROL    29,Y
      ASR    30,Y
      ROR    31,Y
      LSR    32,Y
      COM    $21,Z
      DEC    $22,Z
      NEG    $23,Z
      INC    $24,Z
      ASL    $25,Z
      CLR    $26,Z
      TST    $27,Z
      BCLRW  $292A,Z, #$2B2C
      BCLRW  >$0001,Z, #$0203
      BSETW  $2A2B,Z, #$2C2D
      BSETW  >$0001,Z, #$0203
      ROLW   $2D2E,Z
      ROLW   >$0001,Z
      ASRW   $2E2F,Z
      ASRW   >$0001,Z
      RORW   $2F30,Z
      RORW   >$0001,Z
      LSRW   $3031,Z
      LSRW   >$0001,Z
      COMW   $3132
      DECW   $3233
      NEGW   $3334
      INCW   $3435
      ASLW   $3536
      CLRW   $3637
      TSTW   $3738
      BCLRW  $393A, #$3B3C
      BSETW  $3A3B, #$3C3D
      ROLW   $3D3E
      ASRW   $3E3F
      RORW   $3F40
      LSRW   $4041
      SUBA   E,X
      ADDA   E,X
      SBCA   E,X
      ADCA   E,X
      EORA   E,X
      LDAA   E,X
      ANDA   E,X
      ORAA   E,X
      CMPA   E,X
      BITA   E,X
      STAA   E,X
      NOP
      TYX
      TZX
      TSX
      SUBA   E,Y
      ADDA   E,Y
      SBCA   E,Y
      ADCA   E,Y
      EORA   E,Y
      LDAA   E,Y
      ANDA   E,Y
      ORAA   E,Y
      CMPA   E,Y
      BITA   E,Y
      STAA   E,Y
      TXY
      TZY
      TSY
      SUBA   E,Z
      ADDA   E,Z
      SBCA   E,Z
      ADCA   E,Z
      EORA   E,Z
      LDAA   E,Z
      ANDA   E,Z
      ORAA   E,Z
      CMPA   E,Z
      BITA   E,Z
      STAA   E,Z
      TXZ
      TYZ
      TSZ
      COME
      LDED   $7273
      NEGE
      STED   $7475
      ASLE
      CLRE
      TSTE
      RTI
      ADE
      SDE
      XGDE
      TDE
      ROLE
      ASRE
      RORE
      LSRE
      SUBD   E,X
      ADDD   E,X
      SBCD   E,X
      ADCD   E,X
      EORD   E,X
      LDD    E,X
      ANDD   E,X
      ORD    E,X
      CPD    E,X
      STD    E,X
      SUBD   E,Y
      ADDD   E,Y
      SBCD   E,Y
      ADCD   E,Y
      EORD   E,Y
      LDD    E,Y
      ANDD   E,Y
      ORD    E,Y
      CPD    E,Y
      STD    E,Y
      SUBD   E,Z
      ADDD   E,Z
      SBCD   E,Z
      ADCD   E,Z
      EORD   E,Z
      LDD    E,Z
      ANDD   E,Z
      ORD    E,Z
      CPD    E,Z
      STD    E,Z
      LDHI   $B1B2
      TEDM
      TEM
      TMXED
      TMER
      TMET
      ASLM
      CLRM
      PSHMAC
      PULMAC
      ASRM
      TEKB
      SUBB   E,X
      ADDB   E,X
      SBCB   E,X
      ADCB   E,X
      EORB   E,X
      LDAB   E,X
      ANDB   E,X
      ORAB   E,X
      CMPB   E,X
      BITB   E,X
      STAB   E,X
      SUBB   E,Y
      ADDB   E,Y
      SBCB   E,Y
      ADCB   E,Y
      EORB   E,Y
      LDAB   E,Y
      ANDB   E,Y
      ORAB   E,Y
      CMPB   E,Y
      BITB   E,Y
      STAB   E,Y
      SUBB   E,Z
      ADDB   E,Z
      SBCB   E,Z
      ADCB   E,Z
      EORB   E,Z
      LDAB   E,Z
      ANDB   E,Z
      ORAB   E,Z
      CMPB   E,Z
      BITB   E,Z
      STAB   E,Z
      COMD
      LPSTOP
      NEGD
      WAI
      ASLD
      CLRD
      TSTD
      RTS
      SXT
      LBSR   *-$04FE
      TBEK
      TED
      ROLD
      ASRD
      RORD
      LSRD
      COMW   $0102,X
      COMW   >$0001,X
      DECW   $0203,X
      DECW   >$0001,X
      NEGW   $0304,X
      NEGW   >$0001,X
      INCW   $0405,X
      INCW   >$0001,X
      ASLW   $0506,X
      ASLW   >$0001,X
      CLRW   $0607,X
      CLRW   >$0001,X
      TSTW   $0708,X
      TSTW   >$0001,X
      BCLRW  $090A,X, #$0B0C
      BCLRW  >$0001,X, #$0203
      BSETW  $0A0B,X, #$0C0D
      BSETW  >$0001,X, #$0203
      ROLW   $0D0E,X
      ROLW   >$0001,X
      ASRW   $0E0F,X
      ASRW   >$0001,X
      RORW   $0F10,X
      RORW   >$0001,X
      LSRW   $1011,X
      LSRW   >$0001,X
      COMW   $1112,Y
      COMW   >$0001,Y
      DECW   $1213,Y
      DECW   >$0001,Y
      NEGW   $1314,Y
      NEGW   >$0001,Y
      INCW   $1415,Y
      INCW   >$0001,Y
      ASLW   $1516,Y
      ASLW   >$0001,Y
      CLRW   $1617,Y
      CLRW   >$0001,Y
      TSTW   $1718,Y
      TSTW   >$0001,Y
      BCLRW  $191A,Y, #$1B1C
      BCLRW  >$0001,Y, #$0203
      BSETW  $1A1B,Y, #$1C1D
      BSETW  >$0001,Y, #$0203
      ROLW   $1D1E,Y
      ROLW   >$0001,Y
      ASRW   $1E1F,Y
      ASRW   >$0001,Y
      RORW   $1F20,Y
      RORW   >$0001,Y
      LSRW   $2021,Y
      LSRW   >$0001,Y
      COMW   $2122,Z
      COMW   >$0001,Z
      DECW   $2223,Z
      DECW   >$0001,Z
      NEGW   $2324,Z
      NEGW   >$0001,Z
      INCW   $2425,Z
      INCW   >$0001,Z
      ASLW   $2526,Z
      ASLW   >$0001,Z
      CLRW   $2627,Z
      CLRW   >$0001,Z
      TSTW   $2728,Z
      TSTW   >$0001,Z
      BCLR   >$0001,Z, #$FF
      BSET   >$0001,Z, #$FF
      BRCLR  $2C2D,Z, #$2B, *+$2E36
      BRCLR  >$0001,Z, #$2B, *+$020A
      BRSET  $2D2E,Z, #$2C, *+$2F36
      BRSET  >$0001,Z, #$2C, *+$020A
      ROL    $2D,Z
      ASR    $2E,Z
      ROR    $2F,Z
      LSR    $30,Z
      MOVB   $31,X, $3233
      MOVW   $32,X, $3334
      MOVB   $3435, $33,X
      MOVW   $3536, $34,X
      PSHM   D,X,Z,K
      PSHM   E,X,Z,K
      PSHM   D,E,X,Z,K
      PSHM   Y,Z,K
      PSHM   D,Y,Z,K
      PSHM   E,Y,Z,K
      PSHM   D,E,Y,Z,K
      PSHM   X,Y,Z,K
      PSHM   D,X,Y,Z,K
      PSHM   E,X,Y,Z,K
      PSHM   D,E,X,Y,Z,K
      PSHM   CCR
      PSHM   D,CCR
      PSHM   E,CCR
      PSHM   D,E,CCR
      PSHM   X,CCR
      PSHM   D,X,CCR
      PSHM   E,X,CCR
      PSHM   D,E,X,CCR
      PSHM   Y,CCR
      PSHM   D,Y,CCR
      PSHM   E,Y,CCR
      PSHM   D,E,Y,CCR
      PSHM   X,Y,CCR
      PSHM   D,X,Y,CCR
      PSHM   E,X,Y,CCR
      PSHM   D,E,X,Y,CCR
      PSHM   Z,CCR
      PSHM   D,Z,CCR
      PSHM   E,Z,CCR
      PSHM   D,E,Z,CCR
      PSHM   X,Z,CCR
      PSHM   D,X,Z,CCR
      PSHM   E,X,Z,CCR
      PSHM   D,E,X,Z,CCR
      PSHM   Y,Z,CCR
      PSHM   D,Y,Z,CCR
      PSHM   E,Y,Z,CCR
      PSHM   D,E,Y,Z,CCR
      PSHM   X,Y,Z,CCR
      PSHM   D,X,Y,Z,CCR
      PSHM   E,X,Y,Z,CCR
      PSHM   D,E,X,Y,Z,CCR
      PSHM   K,CCR
      PSHM   D,K,CCR
      PSHM   E,K,CCR
      PSHM   D,E,K,CCR
      PSHM   X,K,CCR
      PSHM   D,X,K,CCR
      PSHM   E,X,K,CCR
      PSHM   D,E,X,K,CCR
      PSHM   Y,K,CCR
      PSHM   D,Y,K,CCR
      PSHM   E,Y,K,CCR
      PSHM   D,E,Y,K,CCR
      PSHM   X,Y,K,CCR
      PSHM   D,X,Y,K,CCR
      PSHM   E,X,Y,K,CCR
      PSHM   D,E,X,Y,K,CCR
      PSHM   Z,K,CCR
      PSHM   D,Z,K,CCR
      PSHM   E,Z,K,CCR
      PSHM   D,E,Z,K,CCR
      PSHM   X,Z,K,CCR
      PSHM   D,X,Z,K,CCR
      PSHM   E,X,Z,K,CCR
      PSHM   D,E,X,Z,K,CCR
      PSHM   Y,Z,K,CCR
      PSHM   D,Y,Z,K,CCR
      PSHM   E,Y,Z,K,CCR
      PSHM   D,E,Y,Z,K,CCR
      PSHM   X,Y,Z,K,CCR
      PSHM   D,X,Y,Z,K,CCR
      PSHM   E,X,Y,Z,K,CCR
      PSHM   D,E,X,Y,Z,K,CCR
      PSHM   D
      PSHM   E
      PSHM   D,E
      PSHM   X
      PSHM   D,X
      PSHM   E,X
      PSHM   D,E,X
      PSHM   Y
      PSHM   D,Y
      PSHM   E,Y
      PSHM   D,E,Y
      PSHM   X,Y
      PSHM   D,X,Y
      PSHM   E,X,Y
      PSHM   D,E,X,Y
      PSHM   Z
      PSHM   D,Z
      PSHM   E,Z
      PSHM   D,E,Z
      PSHM   X,Z
      PSHM   D,X,Z
      PSHM   E,X,Z
      PSHM   D,E,X,Z
      PSHM   Y,Z
      PSHM   D,Y,Z
      PSHM   E,Y,Z
      PSHM   D,E,Y,Z
      PSHM   X,Y,Z
      PSHM   D,X,Y,Z
      PSHM   E,X,Y,Z
      PSHM   D,E,X,Y,Z
      PSHM   K
      PSHM   D,K
      PSHM   E,K
      PSHM   D,E,K
      PSHM   X,K
      PSHM   D,X,K
      PSHM   E,X,K
      PSHM   D,E,X,K
      PSHM   Y,K
      PSHM   D,Y,K
      PSHM   E,Y,K
      PSHM   D,E,Y,K
      PSHM   X,Y,K
      PSHM   D,X,Y,K
      PSHM   E,X,Y,K
      PSHM   D,E,X,Y,K
      PSHM   Z,K
      PSHM   D,Z,K
      PSHM   E,Z,K
      PSHM   D,E,Z,K
      PSHM   X,Z,K
      PULM   K,Z,X,E
      PULM   CCR,K,Z,X,E
      PULM   Y,X,E
      PULM   CCR,Y,X,E
      PULM   K,Y,X,E
      PULM   CCR,K,Y,X,E
      PULM   Z,Y,X,E
      PULM   CCR,Z,Y,X,E
      PULM   K,Z,Y,X,E
      PULM   CCR,K,Z,Y,X,E
      PULM   D
      PULM   CCR,D
      PULM   K,D
      PULM   CCR,K,D
      PULM   Z,D
      PULM   CCR,Z,D
      PULM   K,Z,D
      PULM   CCR,K,Z,D
      PULM   Y,D
      PULM   CCR,Y,D
      PULM   K,Y,D
      PULM   CCR,K,Y,D
      PULM   Z,Y,D
      PULM   CCR,Z,Y,D
      PULM   K,Z,Y,D
      PULM   CCR,K,Z,Y,D
      PULM   X,D
      PULM   CCR,X,D
      PULM   K,X,D
      PULM   CCR,K,X,D
      PULM   Z,X,D
      PULM   CCR,Z,X,D
      PULM   K,Z,X,D
      PULM   CCR,K,Z,X,D
      PULM   Y,X,D
      PULM   CCR,Y,X,D
      PULM   K,Y,X,D
      PULM   CCR,K,Y,X,D
      PULM   Z,Y,X,D
      PULM   CCR,Z,Y,X,D
      PULM   K,Z,Y,X,D
      PULM   CCR,K,Z,Y,X,D
      PULM   E,D
      PULM   CCR,E,D
      PULM   K,E,D
      PULM   CCR,K,E,D
      PULM   Z,E,D
      PULM   CCR,Z,E,D
      PULM   K,Z,E,D
      PULM   CCR,K,Z,E,D
      PULM   Y,E,D
      PULM   CCR,Y,E,D
      PULM   K,Y,E,D
      PULM   CCR,K,Y,E,D
      PULM   Z,Y,E,D
      PULM   CCR,Z,Y,E,D
      PULM   K,Z,Y,E,D
      PULM   CCR,K,Z,Y,E,D
      PULM   X,E,D
      PULM   CCR,X,E,D
      PULM   K,X,E,D
      PULM   CCR,K,X,E,D
      PULM   Z,X,E,D
      PULM   CCR,Z,X,E,D
      PULM   K,Z,X,E,D
      PULM   CCR,K,Z,X,E,D
      PULM   Y,X,E,D
      PULM   CCR,Y,X,E,D
      PULM   K,Y,X,E,D
      PULM   CCR,K,Y,X,E,D
      PULM   Z,Y,X,E,D
      PULM   CCR,Z,Y,X,E,D
      PULM   K,Z,Y,X,E,D
      PULM   CCR,K,Z,Y,X,E,D
      PULM   CCR
      PULM   K
      PULM   CCR,K
      PULM   Z
      PULM   CCR,Z
      PULM   K,Z
      PULM   CCR,K,Z
      PULM   Y
      PULM   CCR,Y
      PULM   K,Y
      PULM   CCR,K,Y
      PULM   Z,Y
      PULM   CCR,Z,Y
      PULM   K,Z,Y
      PULM   CCR,K,Z,Y
      PULM   X
      PULM   CCR,X
      PULM   K,X
      PULM   CCR,K,X
      PULM   Z,X
      PULM   CCR,Z,X
      PULM   K,Z,X
      PULM   CCR,K,Z,X
      PULM   Y,X
      PULM   CCR,Y,X
      PULM   K,Y,X
      PULM   CCR,K,Y,X
      PULM   Z,Y,X
      PULM   CCR,Z,Y,X
      PULM   K,Z,Y,X
      PULM   CCR,K,Z,Y,X
      PULM   E
      PULM   CCR,E
      PULM   K,E
      PULM   CCR,K,E
      PULM   Z,E
      PULM   CCR,Z,E
      PULM   K,Z,E
      PULM   CCR,K,Z,E
      PULM   Y,E
      PULM   CCR,Y,E
      PULM   K,Y,E
      PULM   CCR,K,Y,E
      PULM   Z,Y,E
      PULM   CCR,Z,Y,E
      PULM   K,Z,Y,E
      PULM   CCR,K,Z,Y,E
      PULM   X,E
      PULM   CCR,X,E
      PULM   K,X,E
      PULM   CCR,K,X,E
      PULM   Z,X,E
      PULM   CCR,Z,X,E
      BSR    *+62
      CPE    #$393A
      ANDP   #$3B3C
      ORP    #$3C3D
      AIX    #$3D3E
      AIY    #$3E3F
      AIZ    #$3F40
      AIS    #$4041
      SUBE   $4142,X
      SUBE   >$0001,X
      ADDE   $4243,X
      ADDE   >$0001,X
      SBCE   $4344,X
      SBCE   >$0001,X
      ADCE   $4445,X
      ADCE   >$0001,X
      EORE   $4546,X
      EORE   >$0001,X
      LDE    $4647,X
      LDE    >$0001,X
      ANDE   $4748,X
      ANDE   >$0001,X
      ORE    $4849,X
      ORE    >$0001,X
      CPE    $494A,X
      CPE    >$0001,X
      STE    $4B4C,X
      STE    >$0001,X
      XGEX
      AEX
      TXS
      ABX
      SUBE   $5152,Y
      SUBE   >$0001,Y
      ADDE   $5253,Y
      ADDE   >$0001,Y
      SBCE   $5354,Y
      SBCE   >$0001,Y
      ADCE   $5455,Y
      ADCE   >$0001,Y
      EORE   $5556,Y
      EORE   >$0001,Y
      LDE    $5657,Y
      LDE    >$0001,Y
      ANDE   $5758,Y
      ANDE   >$0001,Y
      ORE    $5859,Y
      ORE    >$0001,Y
      CPE    $595A,Y
      CPE    >$0001,Y
      STE    $5B5C,Y
      STE    >$0001,Y
      XGEY
      AEY
      TYS
      ABY
      SUBE   $6162,Z
      SUBE   >$0001,Z
      ADDE   $6263,Z
      ADDE   >$0001,Z
      SBCE   $6364,Z
      SBCE   >$0001,Z
      ADCE   $6465,Z
      ADCE   >$0001,Z
      EORE   $6566,Z
      EORE   >$0001,Z
      LDE    $6667,Z
      LDE    >$0001,Z
      ANDE   $6768,Z
      ANDE   >$0001,Z
      ORE    $6869,Z
      ORE    >$0001,Z
      CPE    $696A,Z
      CPE    >$0001,Z
      STE    $6B6C,Z
      STE    >$0001,Z
      XGEZ
      AEZ
      TZS
      ABZ
      SUBE   $7172
      ADDE   $7273
      SBCE   $7374
      ADCE   $7475
      EORE   $7576
      LDE    $7677
      ANDE   $7778
      ORE    $7879
      CPE    $797A
      STE    $7B7C
      CPX    #$7D7E
      CPY    #$7E7F
      CPZ    #$7F80
      CPS    #$8081
      LBRA   *-$7E78
      LBRN   *-$7D76
      LBHI   *-$7C76
      LBLS   *-$7B74
      LBCC   *-$7A74
      LBCS   *-$7972
      LBNE   *-$7872
      LBEQ   *-$7770
      LBVC   *-$7670
      LBVS   *-$756E
      LBPL   *-$746E
      LBMI   *-$736C
      LBGE   *-$726C
      LBLT   *-$716A
      LBGT   *-$706A
      LBLE   *-$6F68
      LBMV   *-$6E68
      LBEV   *-$6D66
      TBXK
      TBYK
      TBZK
      TBSK
      BGND
      TXKB
      TYKB
      TZKB
      TSKB
      SUBD   #$B1B2
      ADDD   #$B2B3
      SBCD   #$B3B4
      ADCD   #$B4B5
      EORD   #$B5B6
      LDD    #$B6B7
      ANDD   #$B7B8
      ORD    #$B8B9
      CPD    #$B9BA
      LDX    #$BDBE
      LDY    #$BEBF
      LDZ    #$BFC0
      LDS    #$C0C1
      SUBD   -$3E3E,X
      SUBD   >$0001,X
      ADDD   -$3D3D,X
      ADDD   >$0001,X
      SBCD   -$3C3C,X
      SBCD   >$0001,X
      ADCD   -$3B3B,X
      ADCD   >$0001,X
      EORD   -$3A3A,X
      EORD   >$0001,X
      LDD    -$3939,X
      LDD    >$0001,X
      ANDD   -$3838,X
      ANDD   >$0001,X
      ORD    -$3737,X
      ORD    >$0001,X
      CPD    -$3636,X
      CPD    >$0001,X
      STD    -$3434,X
      STD    >$0001,X
      XGDX
      ADX
      SUBD   -$2E2E,Y
      SUBD   >$0001,Y
      ADDD   -$2D2D,Y
      ADDD   >$0001,Y
      SBCD   -$2C2C,Y
      SBCD   >$0001,Y
      ADCD   -$2B2B,Y
      ADCD   >$0001,Y
      EORD   -$2A2A,Y
      EORD   >$0001,Y
      LDD    -$2929,Y
      LDD    >$0001,Y
      ANDD   -$2828,Y
      ANDD   >$0001,Y
      ORD    -$2727,Y
      ORD    >$0001,Y
      CPD    -$2626,Y
      CPD    >$0001,Y
      STD    -$2424,Y
      STD    >$0001,Y
      XGDY
      ADY
      SUBD   -$1E1E,Z
      SUBD   >$0001,Z
      ADDD   -$1D1D,Z
      ADDD   >$0001,Z
      SBCD   -$1C1C,Z
      SBCD   >$0001,Z
      ADCD   -$1B1B,Z
      ADCD   >$0001,Z
      EORD   -$1A1A,Z
      EORD   >$0001,Z
      LDD    -$1919,Z
      LDD    >$0001,Z
      ANDD   -$1818,Z
      ANDD   >$0001,Z
      ORD    -$1717,Z
      ORD    >$0001,Z
      CPD    -$1616,Z
      CPD    >$0001,Z
      STD    -$1414,Z
      STD    >$0001,Z
      XGDZ
      ADZ
      SUBD   $F1F2
      ADDD   $F2F3
      SBCD   $F3F4
      ADCD   $F4F5
      EORD   $F5F6
      LDD    $F6F7
      ANDD   $F7F8
      ORD    $F8F9
      CPD    $F9FA
      STD    $FBFC
      TPA
      TAP
      MOVB   $FF00, $0102
      MOVW   $0001, $0203
      COMA
      DECA
      NEGA
      INCA
      ASLA
      CLRA
      TSTA
      TBA
      PSHA
      PULA
      SBA
      ABA
      ROLA
      ASRA
      RORA
      LSRA
      COMB
      DECB
      NEGB
      INCB
      ASLB
      CLRB
      TSTB
      TAB
      PSHB
      PULB
      XGAB
      CBA
      ROLB
      ASRB
      RORB
      LSRB
      SWI
      DAA
      ACE
      ACED
      MUL
      EMUL
      EMULS
      FMULS
      EDIV
      EDIVS
      IDIV
      FDIV
      TPD
      TDP
      TDMSK
      SUBE   #$3132
      ADDE   #$3233
      SBCE   #$3334
      ADCE   #$3435
      EORE   #$3536
      LDE    #$3637
      ANDE   #$3738
      ORE    #$3839
      BCLR   $3A3B, #$39
      BSET   $3B3C, #$3A
      BRCLR  $3C3D, #$3B, *+$3E46
      BRSET  $3D3E, #$3C, *+$3F46
      AIX    #$3D
      AIY    #$3E
      AIZ    #$3F
      AIS    #$40
      SUBA   $41,X
      ADDA   $42,X
      SBCA   $43,X
      ADCA   $44,X
      EORA   $45,X
      LDAA   $46,X
      ANDA   $47,X
      ORAA   $48,X
      CMPA   $49,X
      BITA   $4A,X
      STAA   $4B,X
      JMP    $00102,X
      CPX    $4D,X
      CPY    $4E,X
      CPZ    $4F,X
      CPS    $50,X
      SUBA   $51,Y
      ADDA   $52,Y
      SBCA   $53,Y
      ADCA   $54,Y
      EORA   $55,Y
      LDAA   $56,Y
      ANDA   $57,Y
      ORAA   $58,Y
      CMPA   $59,Y
      BITA   $5A,Y
      STAA   $5B,Y
      JMP    $00102,Y
      CPX    $5D,Y
      CPY    $5E,Y
      CPZ    $5F,Y
      CPS    $60,Y
      SUBA   $61,Z
      ADDA   $62,Z
      SBCA   $63,Z
      ADCA   $64,Z
      EORA   $65,Z
      LDAA   $66,Z
      ANDA   $67,Z
      ORAA   $68,Z
      CMPA   $69,Z
      BITA   $6A,Z
      STAA   $6B,Z
      JMP    $00102,Z
      CPX    $6D,Z
      CPY    $6E,Z
      CPZ    $6F,Z
      CPS    $70,Z
      SUBA   #$71
      ADDA   #$72
      SBCA   #$73
      ADCA   #$74
      EORA   #$75
      LDAA   #$76
      ANDA   #$77
      ORAA   #$78
      CMPA   #$79
      BITA   #$7A
      JMP    $00102
      MAC    7, -4
      ADDE   #$7D
      SUBD   $81,X
      ADDD   $82,X
      SBCD   $83,X
      ADCD   $84,X
      EORD   $85,X
      LDD    $86,X
      ANDD   $87,X
      ORD    $88,X
      CPD    $89,X
      JSR    $00102,X
      STD    $8B,X
      BRSET  $8D,X, #$8C, *-108
      STX    $8D,X
      STY    $8E,X
      STZ    $8F,X
      STS    $90,X
      SUBD   $91,Y
      ADDD   $92,Y
      SBCD   $93,Y
      ADCD   $94,Y
      EORD   $95,Y
      LDD    $96,Y
      ANDD   $97,Y
      ORD    $98,Y
      CPD    $99,Y
      JSR    $00102,Y
      STD    $9B,Y
      BRSET  $9D,Y, #$9C, *-92
      STX    $9D,Y
      STY    $9E,Y
      STZ    $9F,Y
      STS    $A0,Y
      SUBD   $A1,Z
      ADDD   $A2,Z
      SBCD   $A3,Z
      ADCD   $A4,Z
      EORD   $A5,Z
      LDD    $A6,Z
      ANDD   $A7,Z
      ORD    $A8,Z
      CPD    $A9,Z
      JSR    $00102,Z
      STD    $AB,Z
      BRSET  $AD,Z, #$AC, *-76
      STX    $AD,Z
      STY    $AE,Z
      STZ    $AF,Z
      STS    $B0,Z
      BRA    *-72
      BRN    *-72
      BHI    *-70
      BLS    *-70
      BCC    *-68
      BCS    *-68
      BNE    *-66
      BEQ    *-66
      BVC    *-64
      BVS    *-64
      BPL    *-62
      BMI    *-62
      BGE    *-60
      BLT    *-60
      BGT    *-58
      BLE    *-58
      SUBB   $C1,X
      ADDB   $C2,X
      SBCB   $C3,X
      ADCB   $C4,X
      EORB   $C5,X
      LDAB   $C6,X
      ANDB   $C7,X
      ORAB   $C8,X
      CMPB   $C9,X
      BITB   $CA,X
      STAB   $CB,X
      BRCLR  $CD,X, #$CC, *-44
      LDX    $CD,X
      LDY    $CE,X
      LDZ    $CF,X
      LDS    $D0,X
      SUBB   $D1,Y
      ADDB   $D2,Y
      SBCB   $D3,Y
      ADCB   $D4,Y
      EORB   $D5,Y
      LDAB   $D6,Y
      ANDB   $D7,Y
      ORAB   $D8,Y
      CMPB   $D9,Y
      BITB   $DA,Y
      STAB   $DB,Y
      BRCLR  $DD,Y, #$DC, *-28
      LDX    $DD,Y
      LDY    $DE,Y
      LDZ    $DF,Y
      LDS    $E0,Y
      SUBB   $E1,Z
      ADDB   $E2,Z
      SBCB   $E3,Z
      ADCB   $E4,Z
      EORB   $E5,Z
      LDAB   $E6,Z
      ANDB   $E7,Z
      ORAB   $E8,Z
      CMPB   $E9,Z
      BITB   $EA,Z
      STAB   $EB,Z
      BRCLR  $ED,Z, #$EC, *-12
      LDX    $ED,Z
      LDY    $EE,Z
      LDZ    $EF,Z
      LDS    $F0,Z
      SUBB   #$F1
      ADDB   #$F2
      SBCB   #$F3
      ADCB   #$F4
      EORB   #$F5
      LDAB   #$F6
      ANDB   #$F7
      ORAB   #$F8
      CMPB   #$F9
      BITB   #$FA
      JSR    $00102
      RMAC   -1, -4
      ADDD   #$FD
