;;; AUTO GENERATED FILE
;;; generated by: gen_tms32010 -u -C 320C26 -o gen_tms320c26.asm -l gen_tms320c26.lst
      CPU   320C26
      ORG   0100H
      ADD   00H
      ADD   *
      ADD   *, 0, AR0
      ADD   *-
      ADD   *-, 0, AR0
      ADD   *+
      ADD   *+, 0, AR0
      ADD   *BR0-
      ADD   *BR0-, 0, AR0
      ADD   *0-
      ADD   *0-, 0, AR0
      ADD   *0+
      ADD   *0+, 0, AR0
      ADD   *BR0+
      ADD   *BR0+, 0, AR0
      ADD   00H, 1
      ADD   *, 1
      ADD   *-, 1
      ADD   *+, 1
      ADD   *BR0-, 1
      ADD   *0-, 1
      ADD   *0+, 1
      ADD   *BR0+, 1
      SUB   00H
      SUB   *
      SUB   *, 0, AR0
      SUB   *-
      SUB   *-, 0, AR0
      SUB   *+
      SUB   *+, 0, AR0
      SUB   *BR0-
      SUB   *BR0-, 0, AR0
      SUB   *0-
      SUB   *0-, 0, AR0
      SUB   *0+
      SUB   *0+, 0, AR0
      SUB   *BR0+
      SUB   *BR0+, 0, AR0
      SUB   00H, 1
      SUB   *, 1
      SUB   *-, 1
      SUB   *+, 1
      SUB   *BR0-, 1
      SUB   *0-, 1
      SUB   *0+, 1
      SUB   *BR0+, 1
      LAC   00H
      LAC   *
      LAC   *, 0, AR0
      LAC   *-
      LAC   *-, 0, AR0
      LAC   *+
      LAC   *+, 0, AR0
      LAC   *BR0-
      LAC   *BR0-, 0, AR0
      LAC   *0-
      LAC   *0-, 0, AR0
      LAC   *0+
      LAC   *0+, 0, AR0
      LAC   *BR0+
      LAC   *BR0+, 0, AR0
      LAC   00H, 1
      LAC   *, 1
      LAC   *-, 1
      LAC   *+, 1
      LAC   *BR0-, 1
      LAC   *0-, 1
      LAC   *0+, 1
      LAC   *BR0+, 1
      LAR   AR0, 00H
      LAR   AR0, *
      LAR   AR0, *, AR0
      LAR   AR0, *-
      LAR   AR0, *-, AR0
      LAR   AR0, *+
      LAR   AR0, *+, AR0
      LAR   AR0, *BR0-
      LAR   AR0, *BR0-, AR0
      LAR   AR0, *0-
      LAR   AR0, *0-, AR0
      LAR   AR0, *0+
      LAR   AR0, *0+, AR0
      LAR   AR0, *BR0+
      LAR   AR0, *BR0+, AR0
      MPY   00H
      MPY   *
      MPY   *, AR0
      MPY   *-
      MPY   *-, AR0
      MPY   *+
      MPY   *+, AR0
      MPY   *BR0-
      MPY   *BR0-, AR0
      MPY   *0-
      MPY   *0-, AR0
      MPY   *0+
      MPY   *0+, AR0
      MPY   *BR0+
      MPY   *BR0+, AR0
      SQRA  00H
      SQRA  *
      SQRA  *, AR0
      SQRA  *-
      SQRA  *-, AR0
      SQRA  *+
      SQRA  *+, AR0
      SQRA  *BR0-
      SQRA  *BR0-, AR0
      SQRA  *0-
      SQRA  *0-, AR0
      SQRA  *0+
      SQRA  *0+, AR0
      SQRA  *BR0+
      SQRA  *BR0+, AR0
      MPYA  00H
      MPYA  *
      MPYA  *, AR0
      MPYA  *-
      MPYA  *-, AR0
      MPYA  *+
      MPYA  *+, AR0
      MPYA  *BR0-
      MPYA  *BR0-, AR0
      MPYA  *0-
      MPYA  *0-, AR0
      MPYA  *0+
      MPYA  *0+, AR0
      MPYA  *BR0+
      MPYA  *BR0+, AR0
      MPYS  00H
      MPYS  *
      MPYS  *, AR0
      MPYS  *-
      MPYS  *-, AR0
      MPYS  *+
      MPYS  *+, AR0
      MPYS  *BR0-
      MPYS  *BR0-, AR0
      MPYS  *0-
      MPYS  *0-, AR0
      MPYS  *0+
      MPYS  *0+, AR0
      MPYS  *BR0+
      MPYS  *BR0+, AR0
      LT    00H
      LT    *
      LT    *, AR0
      LT    *-
      LT    *-, AR0
      LT    *+
      LT    *+, AR0
      LT    *BR0-
      LT    *BR0-, AR0
      LT    *0-
      LT    *0-, AR0
      LT    *0+
      LT    *0+, AR0
      LT    *BR0+
      LT    *BR0+, AR0
      LTA   00H
      LTA   *
      LTA   *, AR0
      LTA   *-
      LTA   *-, AR0
      LTA   *+
      LTA   *+, AR0
      LTA   *BR0-
      LTA   *BR0-, AR0
      LTA   *0-
      LTA   *0-, AR0
      LTA   *0+
      LTA   *0+, AR0
      LTA   *BR0+
      LTA   *BR0+, AR0
      LTP   00H
      LTP   *
      LTP   *, AR0
      LTP   *-
      LTP   *-, AR0
      LTP   *+
      LTP   *+, AR0
      LTP   *BR0-
      LTP   *BR0-, AR0
      LTP   *0-
      LTP   *0-, AR0
      LTP   *0+
      LTP   *0+, AR0
      LTP   *BR0+
      LTP   *BR0+, AR0
      LTD   00H
      LTD   *
      LTD   *, AR0
      LTD   *-
      LTD   *-, AR0
      LTD   *+
      LTD   *+, AR0
      LTD   *BR0-
      LTD   *BR0-, AR0
      LTD   *0-
      LTD   *0-, AR0
      LTD   *0+
      LTD   *0+, AR0
      LTD   *BR0+
      LTD   *BR0+, AR0
      ZALH  00H
      ZALH  *
      ZALH  *, AR0
      ZALH  *-
      ZALH  *-, AR0
      ZALH  *+
      ZALH  *+, AR0
      ZALH  *BR0-
      ZALH  *BR0-, AR0
      ZALH  *0-
      ZALH  *0-, AR0
      ZALH  *0+
      ZALH  *0+, AR0
      ZALH  *BR0+
      ZALH  *BR0+, AR0
      ZALS  00H
      ZALS  *
      ZALS  *, AR0
      ZALS  *-
      ZALS  *-, AR0
      ZALS  *+
      ZALS  *+, AR0
      ZALS  *BR0-
      ZALS  *BR0-, AR0
      ZALS  *0-
      ZALS  *0-, AR0
      ZALS  *0+
      ZALS  *0+, AR0
      ZALS  *BR0+
      ZALS  *BR0+, AR0
      LACT  00H
      LACT  *
      LACT  *, AR0
      LACT  *-
      LACT  *-, AR0
      LACT  *+
      LACT  *+, AR0
      LACT  *BR0-
      LACT  *BR0-, AR0
      LACT  *0-
      LACT  *0-, AR0
      LACT  *0+
      LACT  *0+, AR0
      LACT  *BR0+
      LACT  *BR0+, AR0
      ADDC  00H
      ADDC  *
      ADDC  *, AR0
      ADDC  *-
      ADDC  *-, AR0
      ADDC  *+
      ADDC  *+, AR0
      ADDC  *BR0-
      ADDC  *BR0-, AR0
      ADDC  *0-
      ADDC  *0-, AR0
      ADDC  *0+
      ADDC  *0+, AR0
      ADDC  *BR0+
      ADDC  *BR0+, AR0
      SUBH  00H
      SUBH  *
      SUBH  *, AR0
      SUBH  *-
      SUBH  *-, AR0
      SUBH  *+
      SUBH  *+, AR0
      SUBH  *BR0-
      SUBH  *BR0-, AR0
      SUBH  *0-
      SUBH  *0-, AR0
      SUBH  *0+
      SUBH  *0+, AR0
      SUBH  *BR0+
      SUBH  *BR0+, AR0
      SUBS  00H
      SUBS  *
      SUBS  *, AR0
      SUBS  *-
      SUBS  *-, AR0
      SUBS  *+
      SUBS  *+, AR0
      SUBS  *BR0-
      SUBS  *BR0-, AR0
      SUBS  *0-
      SUBS  *0-, AR0
      SUBS  *0+
      SUBS  *0+, AR0
      SUBS  *BR0+
      SUBS  *BR0+, AR0
      SUBT  00H
      SUBT  *
      SUBT  *, AR0
      SUBT  *-
      SUBT  *-, AR0
      SUBT  *+
      SUBT  *+, AR0
      SUBT  *BR0-
      SUBT  *BR0-, AR0
      SUBT  *0-
      SUBT  *0-, AR0
      SUBT  *0+
      SUBT  *0+, AR0
      SUBT  *BR0+
      SUBT  *BR0+, AR0
      SUBC  00H
      SUBC  *
      SUBC  *, AR0
      SUBC  *-
      SUBC  *-, AR0
      SUBC  *+
      SUBC  *+, AR0
      SUBC  *BR0-
      SUBC  *BR0-, AR0
      SUBC  *0-
      SUBC  *0-, AR0
      SUBC  *0+
      SUBC  *0+, AR0
      SUBC  *BR0+
      SUBC  *BR0+, AR0
      ADDH  00H
      ADDH  *
      ADDH  *, AR0
      ADDH  *-
      ADDH  *-, AR0
      ADDH  *+
      ADDH  *+, AR0
      ADDH  *BR0-
      ADDH  *BR0-, AR0
      ADDH  *0-
      ADDH  *0-, AR0
      ADDH  *0+
      ADDH  *0+, AR0
      ADDH  *BR0+
      ADDH  *BR0+, AR0
      ADDS  00H
      ADDS  *
      ADDS  *, AR0
      ADDS  *-
      ADDS  *-, AR0
      ADDS  *+
      ADDS  *+, AR0
      ADDS  *BR0-
      ADDS  *BR0-, AR0
      ADDS  *0-
      ADDS  *0-, AR0
      ADDS  *0+
      ADDS  *0+, AR0
      ADDS  *BR0+
      ADDS  *BR0+, AR0
      ADDT  00H
      ADDT  *
      ADDT  *, AR0
      ADDT  *-
      ADDT  *-, AR0
      ADDT  *+
      ADDT  *+, AR0
      ADDT  *BR0-
      ADDT  *BR0-, AR0
      ADDT  *0-
      ADDT  *0-, AR0
      ADDT  *0+
      ADDT  *0+, AR0
      ADDT  *BR0+
      ADDT  *BR0+, AR0
      RPT   00H
      RPT   *
      RPT   *, AR0
      RPT   *-
      RPT   *-, AR0
      RPT   *+
      RPT   *+, AR0
      RPT   *BR0-
      RPT   *BR0-, AR0
      RPT   *0-
      RPT   *0-, AR0
      RPT   *0+
      RPT   *0+, AR0
      RPT   *BR0+
      RPT   *BR0+, AR0
      XOR   00H
      XOR   *
      XOR   *, AR0
      XOR   *-
      XOR   *-, AR0
      XOR   *+
      XOR   *+, AR0
      XOR   *BR0-
      XOR   *BR0-, AR0
      XOR   *0-
      XOR   *0-, AR0
      XOR   *0+
      XOR   *0+, AR0
      XOR   *BR0+
      XOR   *BR0+, AR0
      OR    00H
      OR    *
      OR    *, AR0
      OR    *-
      OR    *-, AR0
      OR    *+
      OR    *+, AR0
      OR    *BR0-
      OR    *BR0-, AR0
      OR    *0-
      OR    *0-, AR0
      OR    *0+
      OR    *0+, AR0
      OR    *BR0+
      OR    *BR0+, AR0
      AND   00H
      AND   *
      AND   *, AR0
      AND   *-
      AND   *-, AR0
      AND   *+
      AND   *+, AR0
      AND   *BR0-
      AND   *BR0-, AR0
      AND   *0-
      AND   *0-, AR0
      AND   *0+
      AND   *0+, AR0
      AND   *BR0+
      AND   *BR0+, AR0
      SUBB  00H
      SUBB  *
      SUBB  *, AR0
      SUBB  *-
      SUBB  *-, AR0
      SUBB  *+
      SUBB  *+, AR0
      SUBB  *BR0-
      SUBB  *BR0-, AR0
      SUBB  *0-
      SUBB  *0-, AR0
      SUBB  *0+
      SUBB  *0+, AR0
      SUBB  *BR0+
      SUBB  *BR0+, AR0
      LST   00H
      LST   *
      LST   *, AR0
      LST   *-
      LST   *-, AR0
      LST   *+
      LST   *+, AR0
      LST   *BR0-
      LST   *BR0-, AR0
      LST   *0-
      LST   *0-, AR0
      LST   *0+
      LST   *0+, AR0
      LST   *BR0+
      LST   *BR0+, AR0
      LST1  00H
      LST1  *
      LST1  *, AR0
      LST1  *-
      LST1  *-, AR0
      LST1  *+
      LST1  *+, AR0
      LST1  *BR0-
      LST1  *BR0-, AR0
      LST1  *0-
      LST1  *0-, AR0
      LST1  *0+
      LST1  *0+, AR0
      LST1  *BR0+
      LST1  *BR0+, AR0
      LDP   00H
      LDP   *
      LDP   *, AR0
      LDP   *-
      LDP   *-, AR0
      LDP   *+
      LDP   *+, AR0
      LDP   *BR0-
      LDP   *BR0-, AR0
      LDP   *0-
      LDP   *0-, AR0
      LDP   *0+
      LDP   *0+, AR0
      LDP   *BR0+
      LDP   *BR0+, AR0
      LPH   00H
      LPH   *
      LPH   *, AR0
      LPH   *-
      LPH   *-, AR0
      LPH   *+
      LPH   *+, AR0
      LPH   *BR0-
      LPH   *BR0-, AR0
      LPH   *0-
      LPH   *0-, AR0
      LPH   *0+
      LPH   *0+, AR0
      LPH   *BR0+
      LPH   *BR0+, AR0
      PSHD  00H
      PSHD  *
      PSHD  *, AR0
      PSHD  *-
      PSHD  *-, AR0
      PSHD  *+
      PSHD  *+, AR0
      PSHD  *BR0-
      PSHD  *BR0-, AR0
      PSHD  *0-
      PSHD  *0-, AR0
      PSHD  *0+
      PSHD  *0+, AR0
      PSHD  *BR0+
      PSHD  *BR0+, AR0
      NOP
      MAR   01H
      MAR   *
      LARP  AR0
      MAR   *-
      MAR   *-, AR0
      MAR   *+
      MAR   *+, AR0
      MAR   *BR0-
      MAR   *BR0-, AR0
      MAR   *0-
      MAR   *0-, AR0
      MAR   *0+
      MAR   *0+, AR0
      MAR   *BR0+
      MAR   *BR0+, AR0
      DMOV  00H
      DMOV  *
      DMOV  *, AR0
      DMOV  *-
      DMOV  *-, AR0
      DMOV  *+
      DMOV  *+, AR0
      DMOV  *BR0-
      DMOV  *BR0-, AR0
      DMOV  *0-
      DMOV  *0-, AR0
      DMOV  *0+
      DMOV  *0+, AR0
      DMOV  *BR0+
      DMOV  *BR0+, AR0
      BITT  00H
      BITT  *
      BITT  *, AR0
      BITT  *-
      BITT  *-, AR0
      BITT  *+
      BITT  *+, AR0
      BITT  *BR0-
      BITT  *BR0-, AR0
      BITT  *0-
      BITT  *0-, AR0
      BITT  *0+
      BITT  *0+, AR0
      BITT  *BR0+
      BITT  *BR0+, AR0
      TBLR  00H
      TBLR  *
      TBLR  *, AR0
      TBLR  *-
      TBLR  *-, AR0
      TBLR  *+
      TBLR  *+, AR0
      TBLR  *BR0-
      TBLR  *BR0-, AR0
      TBLR  *0-
      TBLR  *0-, AR0
      TBLR  *0+
      TBLR  *0+, AR0
      TBLR  *BR0+
      TBLR  *BR0+, AR0
      TBLW  00H
      TBLW  *
      TBLW  *, AR0
      TBLW  *-
      TBLW  *-, AR0
      TBLW  *+
      TBLW  *+, AR0
      TBLW  *BR0-
      TBLW  *BR0-, AR0
      TBLW  *0-
      TBLW  *0-, AR0
      TBLW  *0+
      TBLW  *0+, AR0
      TBLW  *BR0+
      TBLW  *BR0+, AR0
      SQRS  00H
      SQRS  *
      SQRS  *, AR0
      SQRS  *-
      SQRS  *-, AR0
      SQRS  *+
      SQRS  *+, AR0
      SQRS  *BR0-
      SQRS  *BR0-, AR0
      SQRS  *0-
      SQRS  *0-, AR0
      SQRS  *0+
      SQRS  *0+, AR0
      SQRS  *BR0+
      SQRS  *BR0+, AR0
      LTS   00H
      LTS   *
      LTS   *, AR0
      LTS   *-
      LTS   *-, AR0
      LTS   *+
      LTS   *+, AR0
      LTS   *BR0-
      LTS   *BR0-, AR0
      LTS   *0-
      LTS   *0-, AR0
      LTS   *0+
      LTS   *0+, AR0
      LTS   *BR0+
      LTS   *BR0+, AR0
      MACD  5D01H, 00H
      MACD  5D81H, *
      MACD  5D89H, *, AR0
      MACD  5D91H, *-
      MACD  5D99H, *-, AR0
      MACD  5DA1H, *+
      MACD  5DA9H, *+, AR0
      MACD  5DC1H, *BR0-
      MACD  5DC9H, *BR0-, AR0
      MACD  5DD1H, *0-
      MACD  5DD9H, *0-, AR0
      MACD  5DE1H, *0+
      MACD  5DE9H, *0+, AR0
      MACD  5DF1H, *BR0+
      MACD  5DF9H, *BR0+, AR0
      MAC   5E01H, 00H
      MAC   5E81H, *
      MAC   5E89H, *, AR0
      MAC   5E91H, *-
      MAC   5E99H, *-, AR0
      MAC   5EA1H, *+
      MAC   5EA9H, *+, AR0
      MAC   5EC1H, *BR0-
      MAC   5EC9H, *BR0-, AR0
      MAC   5ED1H, *0-
      MAC   5ED9H, *0-, AR0
      MAC   5EE1H, *0+
      MAC   5EE9H, *0+, AR0
      MAC   5EF1H, *BR0+
      MAC   5EF9H, *BR0+, AR0
      BC    5F81H
      BC    5F89H, *, AR0
      BC    5F91H, *-
      BC    5F99H, *-, AR0
      BC    5FA1H, *+
      BC    5FA9H, *+, AR0
      BC    5FC1H, *BR0-
      BC    5FC9H, *BR0-, AR0
      BC    5FD1H, *0-
      BC    5FD9H, *0-, AR0
      BC    5FE1H, *0+
      BC    5FE9H, *0+, AR0
      BC    5FF1H, *BR0+
      BC    5FF9H, *BR0+, AR0
      BNC   6081H
      BNC   6089H, *, AR0
      BNC   6091H, *-
      BNC   6099H, *-, AR0
      BNC   60A1H, *+
      BNC   60A9H, *+, AR0
      BNC   60C1H, *BR0-
      BNC   60C9H, *BR0-, AR0
      BNC   60D1H, *0-
      BNC   60D9H, *0-, AR0
      BNC   60E1H, *0+
      BNC   60E9H, *0+, AR0
      BNC   60F1H, *BR0+
      BNC   60F9H, *BR0+, AR0
      SACL  00H
      SACL  *
      SACL  *, 0, AR0
      SACL  *-
      SACL  *-, 0, AR0
      SACL  *+
      SACL  *+, 0, AR0
      SACL  *BR0-
      SACL  *BR0-, 0, AR0
      SACL  *0-
      SACL  *0-, 0, AR0
      SACL  *0+
      SACL  *0+, 0, AR0
      SACL  *BR0+
      SACL  *BR0+, 0, AR0
      SACL  00H, 1
      SACL  *, 1
      SACL  *-, 1
      SACL  *+, 1
      SACL  *BR0-, 1
      SACL  *0-, 1
      SACL  *0+, 1
      SACL  *BR0+, 1
      SACH  00H
      SACH  *
      SACH  *, 0, AR0
      SACH  *-
      SACH  *-, 0, AR0
      SACH  *+
      SACH  *+, 0, AR0
      SACH  *BR0-
      SACH  *BR0-, 0, AR0
      SACH  *0-
      SACH  *0-, 0, AR0
      SACH  *0+
      SACH  *0+, 0, AR0
      SACH  *BR0+
      SACH  *BR0+, 0, AR0
      SACH  00H, 1
      SACH  *, 1
      SACH  *-, 1
      SACH  *+, 1
      SACH  *BR0-, 1
      SACH  *0-, 1
      SACH  *0+, 1
      SACH  *BR0+, 1
      SAR   AR0, 00H
      SAR   AR0, *
      SAR   AR0, *, AR0
      SAR   AR0, *-
      SAR   AR0, *-, AR0
      SAR   AR0, *+
      SAR   AR0, *+, AR0
      SAR   AR0, *BR0-
      SAR   AR0, *BR0-, AR0
      SAR   AR0, *0-
      SAR   AR0, *0-, AR0
      SAR   AR0, *0+
      SAR   AR0, *0+, AR0
      SAR   AR0, *BR0+
      SAR   AR0, *BR0+, AR0
      SST   00H
      SST   *
      SST   *, AR0
      SST   *-
      SST   *-, AR0
      SST   *+
      SST   *+, AR0
      SST   *BR0-
      SST   *BR0-, AR0
      SST   *0-
      SST   *0-, AR0
      SST   *0+
      SST   *0+, AR0
      SST   *BR0+
      SST   *BR0+, AR0
      SST1  00H
      SST1  *
      SST1  *, AR0
      SST1  *-
      SST1  *-, AR0
      SST1  *+
      SST1  *+, AR0
      SST1  *BR0-
      SST1  *BR0-, AR0
      SST1  *0-
      SST1  *0-, AR0
      SST1  *0+
      SST1  *0+, AR0
      SST1  *BR0+
      SST1  *BR0+, AR0
      POPD  00H
      POPD  *
      POPD  *, AR0
      POPD  *-
      POPD  *-, AR0
      POPD  *+
      POPD  *+, AR0
      POPD  *BR0-
      POPD  *BR0-, AR0
      POPD  *0-
      POPD  *0-, AR0
      POPD  *0+
      POPD  *0+, AR0
      POPD  *BR0+
      POPD  *BR0+, AR0
      ZALR  00H
      ZALR  *
      ZALR  *, AR0
      ZALR  *-
      ZALR  *-, AR0
      ZALR  *+
      ZALR  *+, AR0
      ZALR  *BR0-
      ZALR  *BR0-, AR0
      ZALR  *0-
      ZALR  *0-, AR0
      ZALR  *0+
      ZALR  *0+, AR0
      ZALR  *BR0+
      ZALR  *BR0+, AR0
      SPL   00H
      SPL   *
      SPL   *, AR0
      SPL   *-
      SPL   *-, AR0
      SPL   *+
      SPL   *+, AR0
      SPL   *BR0-
      SPL   *BR0-, AR0
      SPL   *0-
      SPL   *0-, AR0
      SPL   *0+
      SPL   *0+, AR0
      SPL   *BR0+
      SPL   *BR0+, AR0
      SPH   00H
      SPH   *
      SPH   *, AR0
      SPH   *-
      SPH   *-, AR0
      SPH   *+
      SPH   *+, AR0
      SPH   *BR0-
      SPH   *BR0-, AR0
      SPH   *0-
      SPH   *0-, AR0
      SPH   *0+
      SPH   *0+, AR0
      SPH   *BR0+
      SPH   *BR0+, AR0
      ADRK  0
      SBRK  0
      IN    00H, 0
      IN    *, 0
      IN    *, 0, AR0
      IN    *-, 0
      IN    *-, 0, AR0
      IN    *+, 0
      IN    *+, 0, AR0
      IN    *BR0-, 0
      IN    *BR0-, 0, AR0
      IN    *0-, 0
      IN    *0-, 0, AR0
      IN    *0+, 0
      IN    *0+, 0, AR0
      IN    *BR0+, 0
      IN    *BR0+, 0, AR0
      BIT   00H, 0
      BIT   *, 0
      BIT   *, 0, AR0
      BIT   *-, 0
      BIT   *-, 0, AR0
      BIT   *+, 0
      BIT   *+, 0, AR0
      BIT   *BR0-, 0
      BIT   *BR0-, 0, AR0
      BIT   *0-, 0
      BIT   *0-, 0, AR0
      BIT   *0+, 0
      BIT   *0+, 0, AR0
      BIT   *BR0+, 0
      BIT   *BR0+, 0, AR0
      MPYK  0
      MPYK  -4096
      LARK  AR0, 0
      LDPK  000H
      ZAC
      LACK  1
      RPTK  0
      ADDK  0
      SUBK  0
      EINT
      DINT
      ROVM
      SOVM
      RSXM
      SSXM
      SPM   0
      RXF
      SXF
      FORT  0
      PAC
      APAC
      SPAC
      SFL
      SFR
      ABS
      PUSH
      POP
      TRAP
      IDLE
      RTXM
      STXM
      NEG
      CALA
      BACC
      RET
      CMPL
      RC
      SC
      RTC
      STC
      ROL
      ROR
      RFSM
      SFSM
      RHM
      SHM
      CONF  0
      CMPR  0
      NORM  *
      NORM  *-
      NORM  *+
      NORM  *BR0-
      NORM  *0-
      NORM  *0+
      NORM  *BR0+
      MPYU  00H
      MPYU  *
      MPYU  *, AR0
      MPYU  *-
      MPYU  *-, AR0
      MPYU  *+
      MPYU  *+, AR0
      MPYU  *BR0-
      MPYU  *BR0-, AR0
      MPYU  *0-
      MPYU  *0-, AR0
      MPYU  *0+
      MPYU  *0+, AR0
      MPYU  *BR0+
      MPYU  *BR0+, AR0
      LRLK  AR0, 0D101H
      LALK  0D102H
      ADLK  0D103H
      SBLK  0D104H
      ANDK  0D105H
      ORK   0D106H
      XORK  0D107H
      LALK  0D202H, 1
      ADLK  0D203H, 1
      SBLK  0D204H, 1
      ANDK  0D205H, 1
      ORK   0D206H, 1
      XORK  0D207H, 1
      OUT   00H, 0
      OUT   *, 0
      OUT   *, 0, AR0
      OUT   *-, 0
      OUT   *-, 0, AR0
      OUT   *+, 0
      OUT   *+, 0, AR0
      OUT   *BR0-, 0
      OUT   *BR0-, 0, AR0
      OUT   *0-, 0
      OUT   *0-, 0, AR0
      OUT   *0+, 0
      OUT   *0+, 0, AR0
      OUT   *BR0+, 0
      OUT   *BR0+, 0, AR0
      BV    0F181H
      BV    0F189H, *, AR0
      BV    0F191H, *-
      BV    0F199H, *-, AR0
      BV    0F1A1H, *+
      BV    0F1A9H, *+, AR0
      BV    0F1C1H, *BR0-
      BV    0F1C9H, *BR0-, AR0
      BV    0F1D1H, *0-
      BV    0F1D9H, *0-, AR0
      BV    0F1E1H, *0+
      BV    0F1E9H, *0+, AR0
      BV    0F1F1H, *BR0+
      BV    0F1F9H, *BR0+, AR0
      BGZ   0F281H
      BGZ   0F289H, *, AR0
      BGZ   0F291H, *-
      BGZ   0F299H, *-, AR0
      BGZ   0F2A1H, *+
      BGZ   0F2A9H, *+, AR0
      BGZ   0F2C1H, *BR0-
      BGZ   0F2C9H, *BR0-, AR0
      BGZ   0F2D1H, *0-
      BGZ   0F2D9H, *0-, AR0
      BGZ   0F2E1H, *0+
      BGZ   0F2E9H, *0+, AR0
      BGZ   0F2F1H, *BR0+
      BGZ   0F2F9H, *BR0+, AR0
      BLEZ  0F381H
      BLEZ  0F389H, *, AR0
      BLEZ  0F391H, *-
      BLEZ  0F399H, *-, AR0
      BLEZ  0F3A1H, *+
      BLEZ  0F3A9H, *+, AR0
      BLEZ  0F3C1H, *BR0-
      BLEZ  0F3C9H, *BR0-, AR0
      BLEZ  0F3D1H, *0-
      BLEZ  0F3D9H, *0-, AR0
      BLEZ  0F3E1H, *0+
      BLEZ  0F3E9H, *0+, AR0
      BLEZ  0F3F1H, *BR0+
      BLEZ  0F3F9H, *BR0+, AR0
      BLZ   0F481H
      BLZ   0F489H, *, AR0
      BLZ   0F491H, *-
      BLZ   0F499H, *-, AR0
      BLZ   0F4A1H, *+
      BLZ   0F4A9H, *+, AR0
      BLZ   0F4C1H, *BR0-
      BLZ   0F4C9H, *BR0-, AR0
      BLZ   0F4D1H, *0-
      BLZ   0F4D9H, *0-, AR0
      BLZ   0F4E1H, *0+
      BLZ   0F4E9H, *0+, AR0
      BLZ   0F4F1H, *BR0+
      BLZ   0F4F9H, *BR0+, AR0
      BGEZ  0F581H
      BGEZ  0F589H, *, AR0
      BGEZ  0F591H, *-
      BGEZ  0F599H, *-, AR0
      BGEZ  0F5A1H, *+
      BGEZ  0F5A9H, *+, AR0
      BGEZ  0F5C1H, *BR0-
      BGEZ  0F5C9H, *BR0-, AR0
      BGEZ  0F5D1H, *0-
      BGEZ  0F5D9H, *0-, AR0
      BGEZ  0F5E1H, *0+
      BGEZ  0F5E9H, *0+, AR0
      BGEZ  0F5F1H, *BR0+
      BGEZ  0F5F9H, *BR0+, AR0
      BNZ   0F681H
      BNZ   0F689H, *, AR0
      BNZ   0F691H, *-
      BNZ   0F699H, *-, AR0
      BNZ   0F6A1H, *+
      BNZ   0F6A9H, *+, AR0
      BNZ   0F6C1H, *BR0-
      BNZ   0F6C9H, *BR0-, AR0
      BNZ   0F6D1H, *0-
      BNZ   0F6D9H, *0-, AR0
      BNZ   0F6E1H, *0+
      BNZ   0F6E9H, *0+, AR0
      BNZ   0F6F1H, *BR0+
      BNZ   0F6F9H, *BR0+, AR0
      BZ    0F781H
      BZ    0F789H, *, AR0
      BZ    0F791H, *-
      BZ    0F799H, *-, AR0
      BZ    0F7A1H, *+
      BZ    0F7A9H, *+, AR0
      BZ    0F7C1H, *BR0-
      BZ    0F7C9H, *BR0-, AR0
      BZ    0F7D1H, *0-
      BZ    0F7D9H, *0-, AR0
      BZ    0F7E1H, *0+
      BZ    0F7E9H, *0+, AR0
      BZ    0F7F1H, *BR0+
      BZ    0F7F9H, *BR0+, AR0
      BNV   0F881H
      BNV   0F889H, *, AR0
      BNV   0F891H, *-
      BNV   0F899H, *-, AR0
      BNV   0F8A1H, *+
      BNV   0F8A9H, *+, AR0
      BNV   0F8C1H, *BR0-
      BNV   0F8C9H, *BR0-, AR0
      BNV   0F8D1H, *0-
      BNV   0F8D9H, *0-, AR0
      BNV   0F8E1H, *0+
      BNV   0F8E9H, *0+, AR0
      BNV   0F8F1H, *BR0+
      BNV   0F8F9H, *BR0+, AR0
      BBZ   0F981H
      BBZ   0F989H, *, AR0
      BBZ   0F991H, *-
      BBZ   0F999H, *-, AR0
      BBZ   0F9A1H, *+
      BBZ   0F9A9H, *+, AR0
      BBZ   0F9C1H, *BR0-
      BBZ   0F9C9H, *BR0-, AR0
      BBZ   0F9D1H, *0-
      BBZ   0F9D9H, *0-, AR0
      BBZ   0F9E1H, *0+
      BBZ   0F9E9H, *0+, AR0
      BBZ   0F9F1H, *BR0+
      BBZ   0F9F9H, *BR0+, AR0
      BBNZ  0FA81H
      BBNZ  0FA89H, *, AR0
      BBNZ  0FA91H, *-
      BBNZ  0FA99H, *-, AR0
      BBNZ  0FAA1H, *+
      BBNZ  0FAA9H, *+, AR0
      BBNZ  0FAC1H, *BR0-
      BBNZ  0FAC9H, *BR0-, AR0
      BBNZ  0FAD1H, *0-
      BBNZ  0FAD9H, *0-, AR0
      BBNZ  0FAE1H, *0+
      BBNZ  0FAE9H, *0+, AR0
      BBNZ  0FAF1H, *BR0+
      BBNZ  0FAF9H, *BR0+, AR0
      BIOZ  0FB81H
      BIOZ  0FB89H, *, AR0
      BIOZ  0FB91H, *-
      BIOZ  0FB99H, *-, AR0
      BIOZ  0FBA1H, *+
      BIOZ  0FBA9H, *+, AR0
      BIOZ  0FBC1H, *BR0-
      BIOZ  0FBC9H, *BR0-, AR0
      BIOZ  0FBD1H, *0-
      BIOZ  0FBD9H, *0-, AR0
      BIOZ  0FBE1H, *0+
      BIOZ  0FBE9H, *0+, AR0
      BIOZ  0FBF1H, *BR0+
      BIOZ  0FBF9H, *BR0+, AR0
      BANZ  0FC81H
      BANZ  0FC89H, *, AR0
      BANZ  0FC91H, *-
      BANZ  0FC99H, *-, AR0
      BANZ  0FCA1H, *+
      BANZ  0FCA9H, *+, AR0
      BANZ  0FCC1H, *BR0-
      BANZ  0FCC9H, *BR0-, AR0
      BANZ  0FCD1H, *0-
      BANZ  0FCD9H, *0-, AR0
      BANZ  0FCE1H, *0+
      BANZ  0FCE9H, *0+, AR0
      BANZ  0FCF1H, *BR0+
      BANZ  0FCF9H, *BR0+, AR0
      BLKP  0FD01H, 00H
      BLKP  0FD81H, *
      BLKP  0FD89H, *, AR0
      BLKP  0FD91H, *-
      BLKP  0FD99H, *-, AR0
      BLKP  0FDA1H, *+
      BLKP  0FDA9H, *+, AR0
      BLKP  0FDC1H, *BR0-
      BLKP  0FDC9H, *BR0-, AR0
      BLKP  0FDD1H, *0-
      BLKP  0FDD9H, *0-, AR0
      BLKP  0FDE1H, *0+
      BLKP  0FDE9H, *0+, AR0
      BLKP  0FDF1H, *BR0+
      BLKP  0FDF9H, *BR0+, AR0
      BLKD  0FE01H, 00H
      BLKD  0FE81H, *
      BLKD  0FE89H, *, AR0
      BLKD  0FE91H, *-
      BLKD  0FE99H, *-, AR0
      BLKD  0FEA1H, *+
      BLKD  0FEA9H, *+, AR0
      BLKD  0FEC1H, *BR0-
      BLKD  0FEC9H, *BR0-, AR0
      BLKD  0FED1H, *0-
      BLKD  0FED9H, *0-, AR0
      BLKD  0FEE1H, *0+
      BLKD  0FEE9H, *0+, AR0
      BLKD  0FEF1H, *BR0+
      BLKD  0FEF9H, *BR0+, AR0
      CALL  0FF81H
      CALL  0FF89H, *, AR0
      CALL  0FF91H, *-
      CALL  0FF99H, *-, AR0
      CALL  0FFA1H, *+
      CALL  0FFA9H, *+, AR0
      CALL  0FFC1H, *BR0-
      CALL  0FFC9H, *BR0-, AR0
      CALL  0FFD1H, *0-
      CALL  0FFD9H, *0-, AR0
      CALL  0FFE1H, *0+
      CALL  0FFE9H, *0+, AR0
      CALL  0FFF1H, *BR0+
      CALL  0FFF9H, *BR0+, AR0
      B     0081H
      B     0089H, *, AR0
      B     0091H, *-
      B     0099H, *-, AR0
      B     00A1H, *+
      B     00A9H, *+, AR0
      B     00C1H, *BR0-
      B     00C9H, *BR0-, AR0
      B     00D1H, *0-
      B     00D9H, *0-, AR0
      B     00E1H, *0+
      B     00E9H, *0+, AR0
      B     00F1H, *BR0+
      B     00F9H, *BR0+, AR0
