;;; AUTO GENERATED FILE
;;; generated by: gen_z80 -u -C Z280 -o gen_z280.asm -l gen_z280.lst
      CPU    Z280
      ORG    0100H
      NOP
      LD     BC, 0302H
      LD     (BC), A
      INC    BC
      INC    B
      DEC    B
      LD     B, 7
      RLCA
      EX     AF, AF'
      ADD    HL, BC
      LD     A, (BC)
      DEC    BC
      INC    C
      DEC    C
      LD     C, 15
      RRCA
      DJNZ   $+19
      DJNZ   $-126
      DJNZ   $
      LD     DE, 1312H
      LD     (DE), A
      INC    DE
      INC    D
      DEC    D
      LD     D, 23
      RLA
      JR     $+27
      JR     $-126
      JR     $
      ADD    HL, DE
      LD     A, (DE)
      DEC    DE
      INC    E
      DEC    E
      LD     E, 31
      RRA
      JR     NZ, $+35
      JR     NZ, $-126
      JR     NZ, $
      LD     HL, 2322H
      LD     (2423H), HL
      INC    HL
      INC    H
      DEC    H
      LD     H, 27H
      DAA
      JR     Z, $+43
      JR     Z, $-126
      JR     Z, $
      ADD    HL, HL
      LD     HL, (2C2BH)
      DEC    HL
      INC    L
      DEC    L
      LD     L, 2FH
      CPL
      JR     NC, $+51
      JR     NC, $-126
      JR     NC, $
      LD     SP, 3332H
      LD     (3433H), A
      INC    SP
      INC    (HL)
      DEC    (HL)
      LD     (HL), 37H
      SCF
      JR     C, $+59
      JR     C, $-126
      JR     C, $
      ADD    HL, SP
      LD     A, (3C3BH)
      DEC    SP
      INC    A
      DEC    A
      LD     A, 3FH
      CCF
      LD     B, B
      LD     B, C
      LD     B, D
      LD     B, E
      LD     B, H
      LD     B, L
      LD     B, (HL)
      LD     B, A
      LD     C, B
      LD     C, C
      LD     C, D
      LD     C, E
      LD     C, H
      LD     C, L
      LD     C, (HL)
      LD     C, A
      LD     D, B
      LD     D, C
      LD     D, D
      LD     D, E
      LD     D, H
      LD     D, L
      LD     D, (HL)
      LD     D, A
      LD     E, B
      LD     E, C
      LD     E, D
      LD     E, E
      LD     E, H
      LD     E, L
      LD     E, (HL)
      LD     E, A
      LD     H, B
      LD     H, C
      LD     H, D
      LD     H, E
      LD     H, H
      LD     H, L
      LD     H, (HL)
      LD     H, A
      LD     L, B
      LD     L, C
      LD     L, D
      LD     L, E
      LD     L, H
      LD     L, L
      LD     L, (HL)
      LD     L, A
      LD     (HL), B
      LD     (HL), C
      LD     (HL), D
      LD     (HL), E
      LD     (HL), H
      LD     (HL), L
      HALT
      LD     (HL), A
      LD     A, B
      LD     A, C
      LD     A, D
      LD     A, E
      LD     A, H
      LD     A, L
      LD     A, (HL)
      LD     A, A
      ADD    A, B
      ADD    A, C
      ADD    A, D
      ADD    A, E
      ADD    A, H
      ADD    A, L
      ADD    A, (HL)
      ADD    A, A
      ADC    A, B
      ADC    A, C
      ADC    A, D
      ADC    A, E
      ADC    A, H
      ADC    A, L
      ADC    A, (HL)
      ADC    A, A
      SUB    A, B
      SUB    A, C
      SUB    A, D
      SUB    A, E
      SUB    A, H
      SUB    A, L
      SUB    A, (HL)
      SUB    A, A
      SBC    A, B
      SBC    A, C
      SBC    A, D
      SBC    A, E
      SBC    A, H
      SBC    A, L
      SBC    A, (HL)
      SBC    A, A
      AND    A, B
      AND    A, C
      AND    A, D
      AND    A, E
      AND    A, H
      AND    A, L
      AND    A, (HL)
      AND    A, A
      XOR    A, B
      XOR    A, C
      XOR    A, D
      XOR    A, E
      XOR    A, H
      XOR    A, L
      XOR    A, (HL)
      XOR    A, A
      OR     A, B
      OR     A, C
      OR     A, D
      OR     A, E
      OR     A, H
      OR     A, L
      OR     A, (HL)
      OR     A, A
      CP     A, B
      CP     A, C
      CP     A, D
      CP     A, E
      CP     A, H
      CP     A, L
      CP     A, (HL)
      CP     A, A
      RET    NZ
      POP    BC
      JP     NZ, 0C4C3H
      JP     0C5C4H
      CALL   NZ, 0C6C5H
      PUSH   BC
      ADD    A, 0C7H
      RST    0
      RET    Z
      RET
      JP     Z, 0CCCBH
      SET    1, H
      SET    1, L
      SET    1, (HL)
      SET    1, A
      SET    2, B
      SET    2, C
      SET    2, D
      SET    2, E
      RLC    B
      RLC    C
      RLC    D
      RLC    E
      RLC    H
      RLC    L
      RLC    (HL)
      RLC    A
      RRC    B
      RRC    C
      RRC    D
      RRC    E
      RRC    H
      RRC    L
      RRC    (HL)
      RRC    A
      RL     B
      RL     C
      RL     D
      RL     E
      RL     H
      RL     L
      RL     (HL)
      RL     A
      RR     B
      RR     C
      RR     D
      RR     E
      RR     H
      RR     L
      RR     (HL)
      RR     A
      SLA    B
      SLA    C
      SLA    D
      SLA    E
      SLA    H
      SLA    L
      SLA    (HL)
      SLA    A
      SRA    B
      SRA    C
      SRA    D
      SRA    E
      SRA    H
      SRA    L
      SRA    (HL)
      SRA    A
      TSET   B
      TSET   C
      TSET   D
      TSET   E
      TSET   H
      TSET   L
      TSET   (HL)
      TSET   A
      SRL    B
      SRL    C
      SRL    D
      SRL    E
      SRL    H
      SRL    L
      SRL    (HL)
      SRL    A
      BIT    0, B
      BIT    0, C
      BIT    0, D
      BIT    0, E
      BIT    0, H
      BIT    0, L
      BIT    0, (HL)
      BIT    0, A
      RES    0, B
      RES    0, C
      RES    0, D
      RES    0, E
      RES    0, H
      RES    0, L
      RES    0, (HL)
      RES    0, A
      CALL   Z, 0CECDH
      CALL   0CFCEH
      ADC    A, 0CFH
      RET    NC
      POP    DE
      JP     NC, 0D4D3H
      OUT    (0D4H), A
      CALL   NC, 0D6D5H
      PUSH   DE
      SUB    A, 0D7H
      RET    C
      EXX
      JP     C, 0DCDBH
      IN     A, (0DCH)
      CALL   C, 0DEDDH
      POP    IX
      JP     PO, (HL)
      EX     (SP), IX
      CALL   PO, (HL)
      PUSH   IX
      JP     (IX)
      JP     PE, (HL)
      EX     HL, IX
      CALL   PE, (HL)
      EX     A, IXH
      EX     A, IXL
      IN     IXH, (C)
      OUT    (C), IXH
      LDCTL  IX, (C)
      IN     IXL, (C)
      OUT    (C), IXL
      ADD    IX, A
      LDCTL  (C), IX
      LDCTL  IX, USP
      LDCTL  USP, IX
      MULT   A, IXH
      MULTU  A, IXH
      DIV    HL, IXH
      DIVU   HL, IXH
      MULT   A, IXL
      MULTU  A, IXL
      DIV    HL, IXL
      DIVU   HL, IXL
      JP     P, (HL)
      CALL   P, (HL)
      LD     SP, IX
      JP     M, (HL)
      CALL   M, (HL)
      ADD    IX, BC
      ADD    IX, DE
      JAR    $+36
      JAR    $-125
      JAR    $
      LD     IX, 2322H
      LD     (2423H), IX
      INC    IX
      INC    IXH
      DEC    IXH
      LD     IXH, 27H
      JAF    $+44
      JAF    $-125
      JAF    $
      ADD    IX, IX
      LD     IX, (2C2BH)
      DEC    IX
      INC    IXL
      DEC    IXL
      LD     IXL, 2FH
      INC    (IX+53)
      INC    (IX-128)
      DEC    (IX+54)
      DEC    (IX-128)
      LD     (IX+55), 38H
      LD     (IX-128), 81H
      ADD    IX, SP
      LD     B, IXH
      LD     B, IXL
      LD     B, (IX+71)
      LD     B, (IX-128)
      LD     C, IXH
      LD     C, IXL
      LD     C, (IX+79)
      LD     C, (IX-128)
      LD     D, IXH
      LD     D, IXL
      LD     D, (IX+87)
      LD     D, (IX-128)
      LD     E, IXH
      LD     E, IXL
      LD     E, (IX+95)
      LD     E, (IX-128)
      LD     IXH, B
      LD     IXH, C
      LD     IXH, D
      LD     IXH, E
      LD     IXH, IXH
      LD     IXH, IXL
      LD     H, (IX+103)
      LD     H, (IX-128)
      LD     IXH, A
      LD     IXL, B
      LD     IXL, C
      LD     IXL, D
      LD     IXL, E
      LD     IXL, IXH
      LD     IXL, IXL
      LD     L, (IX+111)
      LD     L, (IX-128)
      LD     IXL, A
      LD     (IX+113), B
      LD     (IX-128), B
      LD     (IX+114), C
      LD     (IX-128), C
      LD     (IX+115), D
      LD     (IX-128), D
      LD     (IX+116), E
      LD     (IX-128), E
      LD     (IX+117), H
      LD     (IX-128), H
      LD     (IX+118), L
      LD     (IX-128), L
      LD     (IX+120), A
      LD     (IX-128), A
      LD     A, IXH
      LD     A, IXL
      LD     A, (IX+127)
      LD     A, (IX-128)
      ADD    A, IXH
      ADD    A, IXL
      ADD    A, (IX-121)
      ADD    A, (IX+0)
      ADC    A, IXH
      ADC    A, IXL
      ADC    A, (IX-113)
      ADC    A, (IX+0)
      SUB    A, IXH
      SUB    A, IXL
      SUB    A, (IX-105)
      SUB    A, (IX+0)
      SBC    A, IXH
      SBC    A, IXL
      SBC    A, (IX-97)
      SBC    A, (IX+0)
      AND    A, IXH
      AND    A, IXL
      AND    A, (IX-89)
      AND    A, (IX+0)
      XOR    A, IXH
      XOR    A, IXL
      XOR    A, (IX-81)
      XOR    A, (IX+0)
      OR     A, IXH
      OR     A, IXL
      OR     A, (IX-73)
      OR     A, (IX+0)
      CP     A, IXH
      CP     A, IXL
      CP     A, (IX-65)
      CP     A, (IX+0)
      JP     NZ, (HL)
      CALL   NZ, (HL)
      JP     Z, (HL)
      SET    1, (IX-52)
      RLC    (IX-52)
      RRC    (IX-52)
      RL     (IX-52)
      RR     (IX-52)
      SLA    (IX-52)
      SRA    (IX-52)
      TSET   (IX-52)
      SRL    (IX-52)
      BIT    0, (IX-52)
      RES    0, (IX-52)
      RLC    (IX+0)
      RRC    (IX+0)
      RL     (IX+0)
      RR     (IX+0)
      SLA    (IX+0)
      SRA    (IX+0)
      TSET   (IX+0)
      SRL    (IX+0)
      BIT    0, (IX+0)
      RES    0, (IX+0)
      SET    0, (IX+0)
      CALL   Z, (HL)
      CALL   (HL)
      JP     NC, (HL)
      CALL   NC, (HL)
      JP     C, (HL)
      CALL   C, (HL)
      SBC    A, 0DFH
      RET    PO
      POP    HL
      JP     PO, 0E4E3H
      EX     (SP), HL
      CALL   PO, 0E6E5H
      PUSH   HL
      AND    A, 0E7H
      RET    PE
      JP     (HL)
      JP     PE, 0ECEBH
      EX     DE, HL
      CALL   PE, 0EEEDH
      SUBW   HL, HL
      EX     H, L
      MULT   A, (HL)
      MULTU  A, (HL)
      MULTW  HL, SP
      MULTUW HL, SP
      DIV    HL, (HL)
      DIVU   HL, (HL)
      ADDW   HL, SP
      CPW    HL, SP
      MULT   A, A
      MULTU  A, A
      DIVW   DEHL, SP
      DIVUW  DEHL, SP
      DIV    HL, A
      DIVU   HL, A
      SUBW   HL, SP
      LDW    BC, (HL)
      EX     A, B
      LDW    (HL), BC
      EX     A, C
      LDW    DE, (HL)
      EX     A, D
      LDW    (HL), DE
      EX     A, E
      LDW    HL, (HL)
      EX     A, H
      LDW    (HL), HL
      EX     A, L
      LDW    SP, (HL)
      EX     A, (HL)
      LDW    (HL), SP
      EX     A, A
      IN     B, (C)
      OUT    (C), B
      SBC    HL, BC
      LD     (4544H), BC
      NEG    A
      RETN
      IM     0
      LD     I, A
      IN     C, (C)
      OUT    (C), C
      ADC    HL, BC
      LD     BC, (4D4CH)
      NEG    HL
      RETI
      LD     R, A
      IN     D, (C)
      OUT    (C), D
      SBC    HL, DE
      LD     (5554H), DE
      RETIL
      LD     A, I
      IN     E, (C)
      OUT    (C), E
      ADC    HL, DE
      LD     DE, (5D5CH)
      LD     A, R
      IN     H, (C)
      OUT    (C), H
      SBC    HL, HL
      EXTS   A
      PCACHE
      LDCTL  HL, (C)
      RRD
      IN     L, (C)
      OUT    (C), L
      ADC    HL, HL
      EXTS   HL
      ADD    HL, A
      LDCTL  (C), HL
      RLD
      TSTI   (C)
      SC     72H
      SBC    HL, SP
      LD     (7574H), SP
      DI     78H
      IN     A, (C)
      OUT    (C), A
      ADC    HL, SP
      LD     SP, (7D7CH)
      EI     80H
      INIW
      OUTIW
      LDUD   A, (HL)
      LDCTL  HL, USP
      INDW
      OUTDW
      LDUD   (HL), A
      LDCTL  USP, HL
      INIRW
      OTIRW
      LDUP   A, (HL)
      EPUF
      INDRW
      OTDRW
      LDUP   (HL), A
      EPUI
      LDI
      CPI
      INI
      OUTI
      EPUM   (HL)
      EPUM   (0A9A8H)
      LDD
      CPD
      IND
      OUTD
      MEPU   (HL)
      MEPU   (0B1B0H)
      LDIR
      CPIR
      INIR
      OTIR
      INW    HL, (C)
      LDDR
      CPDR
      INDR
      OTDR
      OUTW   (C), HL
      MULT   A, B
      MULTU  A, B
      MULTW  HL, BC
      MULTUW HL, BC
      DIV    HL, B
      DIVU   HL, B
      ADDW   HL, BC
      CPW    HL, BC
      MULT   A, C
      MULTU  A, C
      DIVW   DEHL, BC
      DIVUW  DEHL, BC
      DIV    HL, C
      DIVU   HL, C
      SUBW   HL, BC
      MULT   A, D
      MULTU  A, D
      MULTW  HL, DE
      MULTUW HL, DE
      DIV    HL, D
      DIVU   HL, D
      ADDW   HL, DE
      CPW    HL, DE
      MULT   A, E
      MULTU  A, E
      DIVW   DEHL, DE
      DIVUW  DEHL, DE
      DIV    HL, E
      DIVU   HL, E
      SUBW   HL, DE
      MULT   A, H
      MULTU  A, H
      MULTW  HL, HL
      MULTUW HL, HL
      DIV    HL, H
      DIVU   HL, H
      ADDW   HL, HL
      CPW    HL, HL
      MULT   A, L
      MULTU  A, L
      DIVW   DEHL, HL
      DIVUW  DEHL, HL
      DIV    HL, L
      DIVU   HL, L
      XOR    A, 0EFH
      RET    P
      POP    AF
      JP     P, 0F4F3H
      DI
      CALL   P, 0F6F5H
      PUSH   AF
      OR     A, 0F7H
      RET    M
      LD     SP, HL
      JP     M, 0FCFBH
      EI
      CALL   M, 0FEFDH
      ADD    IY, BC
      ADD    IY, DE
      LD     IY, 2322H
      LD     (2423H), IY
      INC    IY
      INC    IYH
      DEC    IYH
      LD     IYH, 27H
      ADD    IY, IY
      LD     IY, (2C2BH)
      DEC    IY
      INC    IYL
      DEC    IYL
      LD     IYL, 2FH
      INC    (IY+53)
      INC    (IY-128)
      DEC    (IY+54)
      DEC    (IY-128)
      LD     (IY+55), 38H
      LD     (IY-128), 81H
      ADD    IY, SP
      LD     B, IYH
      LD     B, IYL
      LD     B, (IY+71)
      LD     B, (IY-128)
      LD     C, IYH
      LD     C, IYL
      LD     C, (IY+79)
      LD     C, (IY-128)
      LD     D, IYH
      LD     D, IYL
      LD     D, (IY+87)
      LD     D, (IY-128)
      LD     E, IYH
      LD     E, IYL
      LD     E, (IY+95)
      LD     E, (IY-128)
      LD     IYH, B
      LD     IYH, C
      LD     IYH, D
      LD     IYH, E
      LD     IYH, IYH
      LD     IYH, IYL
      LD     H, (IY+103)
      LD     H, (IY-128)
      LD     IYH, A
      LD     IYL, B
      LD     IYL, C
      LD     IYL, D
      LD     IYL, E
      LD     IYL, IYH
      LD     IYL, IYL
      LD     L, (IY+111)
      LD     L, (IY-128)
      LD     IYL, A
      LD     (IY+113), B
      LD     (IY-128), B
      LD     (IY+114), C
      LD     (IY-128), C
      LD     (IY+115), D
      LD     (IY-128), D
      LD     (IY+116), E
      LD     (IY-128), E
      LD     (IY+117), H
      LD     (IY-128), H
      LD     (IY+118), L
      LD     (IY-128), L
      LD     (IY+120), A
      LD     (IY-128), A
      LD     A, IYH
      LD     A, IYL
      LD     A, (IY+127)
      LD     A, (IY-128)
      ADD    A, IYH
      ADD    A, IYL
      ADD    A, (IY-121)
      ADD    A, (IY+0)
      ADC    A, IYH
      ADC    A, IYL
      ADC    A, (IY-113)
      ADC    A, (IY+0)
      SUB    A, IYH
      SUB    A, IYL
      SUB    A, (IY-105)
      SUB    A, (IY+0)
      SBC    A, IYH
      SBC    A, IYL
      SBC    A, (IY-97)
      SBC    A, (IY+0)
      AND    A, IYH
      AND    A, IYL
      AND    A, (IY-89)
      AND    A, (IY+0)
      XOR    A, IYH
      XOR    A, IYL
      XOR    A, (IY-81)
      XOR    A, (IY+0)
      OR     A, IYH
      OR     A, IYL
      OR     A, (IY-73)
      OR     A, (IY+0)
      CP     A, IYH
      CP     A, IYL
      CP     A, (IY-65)
      CP     A, (IY+0)
      JP     NZ, <$-0739H>
      JP     NZ, <$+00C7H>
      JP     NZ, <$>
      JP     <$-0738H>
      JP     <$+00C8H>
      JP     <$>
      CALL   NZ, <$-0737H>
      CALL   NZ, <$+00C9H>
      CALL   NZ, <$>
      JP     Z, <$-0731H>
      JP     Z, <$+00CFH>
      JP     Z, <$>
      SET    1, (IY-52)
      RLC    (IY-52)
      RRC    (IY-52)
      RL     (IY-52)
      RR     (IY-52)
      SLA    (IY-52)
      SRA    (IY-52)
      TSET   (IY-52)
      SRL    (IY-52)
      BIT    0, (IY-52)
      RES    0, (IY-52)
      RLC    (IY+0)
      RRC    (IY+0)
      RL     (IY+0)
      RR     (IY+0)
      SLA    (IY+0)
      SRA    (IY+0)
      TSET   (IY+0)
      SRL    (IY+0)
      BIT    0, (IY+0)
      RES    0, (IY+0)
      SET    0, (IY+0)
      CALL   Z, <$-072FH>
      CALL   Z, <$+00D1H>
      CALL   Z, <$>
      CALL   <$-072EH>
      CALL   <$+00D2H>
      CALL   <$>
      JP     NC, <$-0729H>
      JP     NC, <$+00D7H>
      JP     NC, <$>
      CALL   NC, <$-0727H>
      CALL   NC, <$+00D9H>
      CALL   NC, <$>
      JP     C, <$-0721H>
      JP     C, <$+00DFH>
      JP     C, <$>
      CALL   C, <$-071FH>
      CALL   C, <$+00E1H>
      CALL   C, <$>
      POP    IY
      JP     PO, <$-0819H>
      JP     PO, <$+00E7H>
      JP     PO, <$>
      EX     (SP), IY
      CALL   PO, <$-0817H>
      CALL   PO, <$+00E9H>
      CALL   PO, <$>
      PUSH   IY
      JP     (IY)
      JP     PE, <$-0811H>
      JP     PE, <$+00EFH>
      JP     PE, <$>
      EX     HL, IY
      CALL   PE, <$-080FH>
      CALL   PE, <$+00F1H>
      CALL   PE, <$>
      EX     A, IYH
      EX     A, IYL
      IN     IYH, (C)
      OUT    (C), IYH
      LDCTL  IY, (C)
      IN     IYL, (C)
      OUT    (C), IYL
      ADD    IY, A
      LDCTL  (C), IY
      LDCTL  IY, USP
      LDCTL  USP, IY
      MULT   A, IYH
      MULTU  A, IYH
      DIV    HL, IYH
      DIVU   HL, IYH
      MULT   A, IYL
      MULTU  A, IYL
      DIV    HL, IYL
      DIVU   HL, IYL
      JP     P, <$-0809H>
      JP     P, <$+00F7H>
      JP     P, <$>
      CALL   P, <$-0807H>
      CALL   P, <$+00F9H>
      CALL   P, <$>
      PUSH   0F7F6H
      LD     SP, IY
      JP     M, <$-0301H>
      JP     M, <$+00FFH>
      JP     M, <$>
      CALL   M, <$-00FFH>
      CALL   M, <$+1>
      CALL   M, <$>
      CP     A, 0FFH
