;;; AUTO GENERATED FILE
;;; generated by: gen_pdp8 -u -C 6100 -o gen_im6100.asm -l gen_im6100.lst
      CPU   6100
      ORG   080H
      AND   000H
      AND   I 000H
      TAD   000H
      TAD   I 000H
      ISZ   000H
      ISZ   I 000H
      DCA   000H
      DCA   I 000H
      JMS   000H
      JMS   I 000H
      JMP   000H
      JMP   I 000H
      SKON
      ION
      IOF
      SRQ
      GTF
      RTF
      SGT
      CAF
      IOT   1 0
      NOP
      IAC
      BSW
      BSW   IAC
      RAL
      RAL   IAC
      RTL
      RTL   IAC
      RAR
      RAR   IAC
      RTR
      RTR   IAC
      CML
      CML   IAC
      CML   BSW
      CML   BSW IAC
      CML   RAL
      CML   RAL IAC
      CML   RTL
      CML   RTL IAC
      CML   RAR
      CML   RAR IAC
      CML   RTR
      CML   RTR IAC
      CMA
      CIA
      CMA   BSW
      CIA   BSW
      CMA   RAL
      CIA   RAL
      CMA   RTL
      CIA   RTL
      CMA   RAR
      CIA   RAR
      CMA   RTR
      CIA   RTR
      CMA   CML
      CIA   CML
      CMA   CML BSW
      CIA   CML BSW
      CMA   CML RAL
      CIA   CML RAL
      CMA   CML RTL
      CIA   CML RTL
      CMA   CML RAR
      CIA   CML RAR
      CMA   CML RTR
      CIA   CML RTR
      CLL
      CLL   IAC
      CLL   BSW
      CLL   BSW IAC
      CLL   RAL
      CLL   RAL IAC
      CLL   RTL
      CLL   RTL IAC
      CLL   RAR
      CLL   RAR IAC
      CLL   RTR
      CLL   RTR IAC
      STL
      STL   IAC
      STL   BSW
      STL   BSW IAC
      STL   RAL
      STL   RAL IAC
      STL   RTL
      STL   RTL IAC
      STL   RAR
      STL   RAR IAC
      STL   RTR
      STL   RTR IAC
      CLL   CMA
      CLL   CIA
      CLL   CMA BSW
      CLL   CIA BSW
      CLL   CMA RAL
      CLL   CIA RAL
      CLL   CMA RTL
      CLL   CIA RTL
      CLL   CMA RAR
      CLL   CIA RAR
      CLL   CMA RTR
      CLL   CIA RTR
      STL   CMA
      STL   CIA
      STL   CMA BSW
      STL   CIA BSW
      STL   CMA RAL
      STL   CIA RAL
      STL   CMA RTL
      STL   CIA RTL
      STL   CMA RAR
      STL   CIA RAR
      STL   CMA RTR
      STL   CIA RTR
      CLA
      CLA   IAC
      CLA   BSW
      CLA   BSW IAC
      GLK
      GLK   IAC
      CLA   RTL
      CLA   RTL IAC
      CLA   RAR
      CLA   RAR IAC
      CLA   RTR
      CLA   RTR IAC
      CLA   CML
      CLA   CML IAC
      CLA   CML BSW
      CLA   CML BSW IAC
      GLK   CML
      GLK   CML IAC
      CLA   CML RTL
      CLA   CML RTL IAC
      CLA   CML RAR
      CLA   CML RAR IAC
      CLA   CML RTR
      CLA   CML RTR IAC
      STA
      STA   IAC
      STA   BSW
      STA   BSW IAC
      GLK   CMA
      GLK   CIA
      STA   RTL
      STA   RTL IAC
      STA   RAR
      STA   RAR IAC
      STA   RTR
      STA   RTR IAC
      STA   CML
      STA   CML IAC
      STA   CML BSW
      STA   CML BSW IAC
      GLK   CMA CML
      GLK   CIA CML
      STA   CML RTL
      STA   CML RTL IAC
      STA   CML RAR
      STA   CML RAR IAC
      STA   CML RTR
      STA   CML RTR IAC
      CLA   CLL
      CLA   CLL IAC
      CLA   CLL BSW
      CLA   CLL BSW IAC
      GLK   CLL
      GLK   CLL IAC
      CLA   CLL RTL
      CLA   CLL RTL IAC
      CLA   CLL RAR
      CLA   CLL RAR IAC
      CLA   CLL RTR
      CLA   CLL RTR IAC
      STL   CLA
      STL   CLA IAC
      STL   CLA BSW
      STL   CLA BSW IAC
      GLK   STL
      GLK   STL IAC
      STL   CLA RTL
      STL   CLA RTL IAC
      STL   CLA RAR
      STL   CLA RAR IAC
      STL   CLA RTR
      STL   CLA RTR IAC
      STA   CLL
      STA   CLL IAC
      STA   CLL BSW
      STA   CLL BSW IAC
      GLK   CLL CMA
      GLK   CLL CIA
      STA   CLL RTL
      STA   CLL RTL IAC
      STA   CLL RAR
      STA   CLL RAR IAC
      STA   CLL RTR
      STA   CLL RTR IAC
      STL   STA
      STL   STA IAC
      STL   STA BSW
      STL   STA BSW IAC
      GLK   STL CMA
      GLK   STL CIA
      STL   STA RTL
      STL   STA RTL IAC
      STL   STA RAR
      STL   STA RAR IAC
      STL   STA RTR
      STL   STA RTR IAC
      HLT
      OSR
      OSR   HLT
      SKP
      SKP   HLT
      SKP   OSR
      SKP   OSR HLT
      SNL
      MQL
      SNL   HLT
      SNL   OSR
      SNL   OSR HLT
      SZL
      SZL   HLT
      SZL   OSR
      SZL   OSR HLT
      SZA
      SZA   HLT
      SZA   OSR
      SZA   OSR HLT
      SNA
      SNA   HLT
      SNA   OSR
      SNA   OSR HLT
      SZA   SNL
      SZA   SNL HLT
      SZA   SNL OSR
      SZA   SNL OSR HLT
      SNA   SZL
      SNA   SZL HLT
      SNA   SZL OSR
      SNA   SZL OSR HLT
      SMA
      MQA
      SMA   HLT
      SMA   OSR
      SMA   OSR HLT
      SPA
      SPA   HLT
      SPA   OSR
      SPA   OSR HLT
      SMA   SNL
      SWP
      SMA   SNL HLT
      SMA   SNL OSR
      SMA   SNL OSR HLT
      SPA   SZL
      SPA   SZL HLT
      SPA   SZL OSR
      SPA   SZL OSR HLT
      SMA   SZA
      SMA   SZA HLT
      SMA   SZA OSR
      SMA   SZA OSR HLT
      SPA   SNA
      SPA   SNA HLT
      SPA   SNA OSR
      SPA   SNA OSR HLT
      SMA   SZA SNL
      SMA   SZA SNL HLT
      SMA   SZA SNL OSR
      SMA   SZA SNL OSR HLT
      SPA   SNA SZL
      SPA   SNA SZL HLT
      SPA   SNA SZL OSR
      SPA   SNA SZL OSR HLT
      CLA   HLT
      LAS
      LAS   HLT
      SKP   CLA
      SKP   CLA HLT
      SKP   LAS
      SKP   LAS HLT
      SNL   CLA
      CAM
      SNL   CLA HLT
      SNL   LAS
      SNL   LAS HLT
      SZL   CLA
      SZL   CLA HLT
      SZL   LAS
      SZL   LAS HLT
      SZA   CLA
      SZA   CLA HLT
      SZA   LAS
      SZA   LAS HLT
      SNA   CLA
      SNA   CLA HLT
      SNA   LAS
      SNA   LAS HLT
      SZA   SNL CLA
      SZA   SNL CLA HLT
      SZA   SNL LAS
      SZA   SNL LAS HLT
      SNA   SZL CLA
      SNA   SZL CLA HLT
      SNA   SZL LAS
      SNA   SZL LAS HLT
      SMA   CLA
      ACL
      SMA   CLA HLT
      SMA   LAS
      SMA   LAS HLT
      SPA   CLA
      SPA   CLA HLT
      SPA   LAS
      SPA   LAS HLT
      SMA   SNL CLA
      CLA   SWP
      SMA   SNL CLA HLT
      SMA   SNL LAS
      SMA   SNL LAS HLT
      SPA   SZL CLA
      SPA   SZL CLA HLT
      SPA   SZL LAS
      SPA   SZL LAS HLT
      SMA   SZA CLA
      SMA   SZA CLA HLT
      SMA   SZA LAS
      SMA   SZA LAS HLT
      SPA   SNA CLA
      SPA   SNA CLA HLT
      SPA   SNA LAS
      SPA   SNA LAS HLT
      SMA   SZA SNL CLA
      SMA   SZA SNL CLA HLT
      SMA   SZA SNL LAS
      SMA   SZA SNL LAS HLT
      SPA   SNA SZL CLA
      SPA   SNA SZL CLA HLT
      SPA   SNA SZL LAS
      SPA   SNA SZL LAS HLT
