;;; AUTO GENERATED FILE
;;; generated by: gen_mc6805 -u -C 68HCS08 -o gen_mc68hcs08.asm -l gen_mc68hcs08.lst
      CPU   68HCS08
      ORG   $0100
      BRSET 0, $01, *+5
      BRCLR 0, $02, *+6
      BSET  0, $11
      BCLR  0, $12
      BRA   *+35
      BRN   *+36
      BHI   *+37
      BLS   *+38
      BHS   *+39
      BLO   *+40
      BNE   *+41
      BEQ   *+42
      BHCC  *+43
      BHCS  *+44
      BPL   *+45
      BMI   *+46
      BMC   *+47
      BMS   *+48
      BIL   *+49
      BIH   *+50
      NEG   $31
      CBEQ  $32, *+54
      LDHX  >$0001
      LDHX  $0102
      COM   $34
      LSR   $35
      STHX  $36
      ROR   $37
      ASR   $38
      ASL   $39
      ROL   $3A
      DEC   $3B
      DBNZ  $3C, *+64
      INC   $3D
      TST   $3E
      CPHX  >$0001
      CPHX  $0102
      CLR   $40
      NEGA
      CBEQA #$42, *+70
      MUL
      COMA
      LSRA
      LDHX  #$4647
      RORA
      ASRA
      ASLA
      ROLA
      DECA
      DBNZA *+78
      INCA
      TSTA
      MOV   $4F, $50
      CLRA
      NEGX
      CBEQX #$52, *+86
      DIV
      COMX
      LSRX
      LDHX  $56
      RORX
      ASRX
      ASLX
      ROLX
      DECX
      DBNZX *+94
      INCX
      TSTX
      MOV   $5F, X+
      CLRX
      NEG   97,X
      NEG   <0,X
      CBEQ  98,X+, *+102
      CBEQ  <0,X+, *+4
      NSA
      COM   100,X
      COM   <0,X
      LSR   101,X
      LSR   <0,X
      CPHX  #$6667
      ROR   103,X
      ROR   <0,X
      ASR   104,X
      ASR   <0,X
      ASL   105,X
      ASL   <0,X
      ROL   106,X
      ROL   <0,X
      DEC   107,X
      DEC   <0,X
      DBNZ  108,X, *+112
      DBNZ  <0,X, *+4
      INC   109,X
      INC   <0,X
      TST   110,X
      TST   <0,X
      MOV   #$6F, $70
      CLR   112,X
      CLR   <0,X
      NEG   ,X
      CBEQ  X+, *+116
      DAA
      COM   ,X
      LSR   ,X
      CPHX  $76
      ROR   ,X
      ASR   ,X
      ASL   ,X
      ROL   ,X
      DEC   ,X
      DBNZ  ,X, *+126
      INC   ,X
      TST   ,X
      MOV   X+, $7F
      CLR   ,X
      RTI
      RTS
      BGND
      SWI
      TAP
      TPA
      PULA
      PSHA
      PULX
      PSHX
      PULH
      PSHH
      CLRH
      STOP
      WAIT
      BGE   *-109
      BLT   *-108
      BGT   *-107
      BLE   *-106
      TXS
      TSX
      STHX  >$0001
      STHX  $0102
      TAX
      CLC
      SEC
      CLI
      SEI
      RSP
      NOP
      LDHX  ,X
      LDHX  $BFC0,X
      LDHX  >$0001,X
      LDHX  207,X
      LDHX  <0,X
      SUB   $D1D2,SP
      SUB   >$0001,SP
      CMP   $D2D3,SP
      CMP   >$0001,SP
      SBC   $D3D4,SP
      SBC   >$0001,SP
      CPX   $D4D5,SP
      CPX   >$0001,SP
      AND   $D5D6,SP
      AND   >$0001,SP
      BIT   $D6D7,SP
      BIT   >$0001,SP
      LDA   $D7D8,SP
      LDA   >$0001,SP
      STA   $D8D9,SP
      STA   >$0001,SP
      EOR   $D9DA,SP
      EOR   >$0001,SP
      ADC   $DADB,SP
      ADC   >$0001,SP
      ORA   $DBDC,SP
      ORA   >$0001,SP
      ADD   $DCDD,SP
      ADD   >$0001,SP
      LDX   $DFE0,SP
      LDX   >$0001,SP
      STX   $E0E1,SP
      STX   >$0001,SP
      SUB   225,SP
      SUB   <0,SP
      CMP   226,SP
      CMP   <0,SP
      SBC   227,SP
      SBC   <0,SP
      CPX   228,SP
      CPX   <0,SP
      AND   229,SP
      AND   <0,SP
      BIT   230,SP
      BIT   <0,SP
      LDA   231,SP
      LDA   <0,SP
      STA   232,SP
      STA   <0,SP
      EOR   233,SP
      EOR   <0,SP
      ADC   234,SP
      ADC   <0,SP
      ORA   235,SP
      ORA   <0,SP
      ADD   236,SP
      ADD   <0,SP
      LDX   239,SP
      LDX   <0,SP
      STX   240,SP
      STX   <0,SP
      CPHX  244,SP
      CPHX  <0,SP
      LDHX  255,SP
      LDHX  <0,SP
      STHX  <0,SP
      STHX  1,SP
      NEG   97,SP
      NEG   <0,SP
      CBEQ  98,SP, *+103
      CBEQ  <0,SP, *+5
      COM   100,SP
      COM   <0,SP
      LSR   101,SP
      LSR   <0,SP
      ROR   103,SP
      ROR   <0,SP
      ASR   104,SP
      ASR   <0,SP
      ASL   105,SP
      ASL   <0,SP
      ROL   106,SP
      ROL   <0,SP
      DEC   107,SP
      DEC   <0,SP
      DBNZ  108,SP, *+113
      DBNZ  <0,SP, *+5
      INC   109,SP
      INC   <0,SP
      TST   110,SP
      TST   <0,SP
      CLR   112,SP
      CLR   <0,SP
      TXA
      SUB   #$A1
      CMP   #$A2
      SBC   #$A3
      CPX   #$A4
      AND   #$A5
      BIT   #$A6
      LDA   #$A7
      AIS   #-$58
      AIS   #0
      EOR   #$A9
      ADC   #$AA
      ORA   #$AB
      ADD   #$AC
      BSR   *-80
      LDX   #$AF
      AIX   #-$50
      AIX   #0
      SUB   $B1
      CMP   $B2
      SBC   $B3
      CPX   $B4
      AND   $B5
      BIT   $B6
      LDA   $B7
      STA   $B8
      EOR   $B9
      ADC   $BA
      ORA   $BB
      ADD   $BC
      JMP   $BD
      JSR   $BE
      LDX   $BF
      STX   $C0
      SUB   >$0001
      SUB   $0102
      CMP   >$0001
      CMP   $0102
      SBC   >$0001
      SBC   $0102
      CPX   >$0001
      CPX   $0102
      AND   >$0001
      AND   $0102
      BIT   >$0001
      BIT   $0102
      LDA   >$0001
      LDA   $0102
      STA   >$0001
      STA   $0102
      EOR   >$0001
      EOR   $0102
      ADC   >$0001
      ADC   $0102
      ORA   >$0001
      ORA   $0102
      ADD   >$0001
      ADD   $0102
      JMP   >$0001
      JMP   $0102
      JSR   >$0001
      JSR   $0102
      LDX   >$0001
      LDX   $0102
      STX   >$0001
      STX   $0102
      SUB   $D1D2,X
      SUB   >$0001,X
      CMP   $D2D3,X
      CMP   >$0001,X
      SBC   $D3D4,X
      SBC   >$0001,X
      CPX   $D4D5,X
      CPX   >$0001,X
      AND   $D5D6,X
      AND   >$0001,X
      BIT   $D6D7,X
      BIT   >$0001,X
      LDA   $D7D8,X
      LDA   >$0001,X
      STA   $D8D9,X
      STA   >$0001,X
      EOR   $D9DA,X
      EOR   >$0001,X
      ADC   $DADB,X
      ADC   >$0001,X
      ORA   $DBDC,X
      ORA   >$0001,X
      ADD   $DCDD,X
      ADD   >$0001,X
      JMP   $DDDE,X
      JMP   >$0001,X
      JSR   $DEDF,X
      JSR   >$0001,X
      LDX   $DFE0,X
      LDX   >$0001,X
      STX   $E0E1,X
      STX   >$0001,X
      SUB   225,X
      SUB   <0,X
      CMP   226,X
      CMP   <0,X
      SBC   227,X
      SBC   <0,X
      CPX   228,X
      CPX   <0,X
      AND   229,X
      AND   <0,X
      BIT   230,X
      BIT   <0,X
      LDA   231,X
      LDA   <0,X
      STA   232,X
      STA   <0,X
      EOR   233,X
      EOR   <0,X
      ADC   234,X
      ADC   <0,X
      ORA   235,X
      ORA   <0,X
      ADD   236,X
      ADD   <0,X
      JMP   237,X
      JMP   <0,X
      JSR   238,X
      JSR   <0,X
      LDX   239,X
      LDX   <0,X
      STX   240,X
      STX   <0,X
      SUB   ,X
      CMP   ,X
      SBC   ,X
      CPX   ,X
      AND   ,X
      BIT   ,X
      LDA   ,X
      STA   ,X
      EOR   ,X
      ADC   ,X
      ORA   ,X
      ADD   ,X
      JMP   ,X
      JSR   ,X
      LDX   ,X
      STX   ,X
