;;; AUTO GENERATED FILE
;;; generated by: gen_i8096 -u -C 8096 -o gen_i8096.asm -l gen_i8096.lst
      CPU   8096
      ORG   2000H
      SKIP  1
      CLR   2
      NOT   3
      NEG   4
      DEC   6
      EXT   7
      INC   8
      SHR   10, #9
      SHL   11, #10
      SHRA  12, #11
      SHRL  14, #13
      SHLL  15, #14
      SHLL  17, 16
      SHRAL 16, #15
      SHRAL 17, 16
      NORML 17, 16
      CLRB  18
      NOTB  19
      NEGB  20
      DECB  22
      EXTB  23
      INCB  24
      SHRB  26, 25
      SHLB  27, 26
      SHRAB 28, 27
      SJMP  $+33
      SJMP  $
      SJMP  $-987
      SCALL $+41
      SCALL $
      SCALL $-979
      JBC   49, 0, $+50
      JBC   49, 0, $-128
      JBC   49, 0, $
      JBS   57, 0, $+58
      JBS   57, 0, $-128
      JBS   57, 0, $
      AND   67, 66, 65
      AND   69, 68, #4342H
      AND   69, 68, [67]
      AND   71, 70, 69[68]
      AND   71, 70, -128[68]
      AND   73, 72, 4746H[68]
      ADD   71, 70, 69
      ADD   73, 72, #4746H
      ADD   73, 72, [71]
      ADD   75, 74, 73[72]
      ADD   75, 74, -128[72]
      ADD   77, 76, 4B4AH[72]
      SUB   75, 74, 73
      SUB   77, 76, #4B4AH
      SUB   77, 76, [75]
      SUB   79, 78, 77[76]
      SUB   79, 78, -128[76]
      SUB   81, 80, 4F4EH[76]
      MULU  79, 78, 77
      MULU  81, 80, #4F4EH
      MULU  81, 80, [79]
      MULU  83, 82, 81[80]
      MULU  83, 82, -128[80]
      MULU  85, 84, 5352H[80]
      ANDB  83, 82, 81
      ANDB  84, 83, #52H
      ANDB  85, 84, [83]
      ANDB  87, 86, 85[84]
      ANDB  87, 86, -128[84]
      ANDB  89, 88, 5756H[84]
      ADDB  87, 86, 85
      ADDB  88, 87, #56H
      ADDB  89, 88, [87]
      ADDB  91, 90, 89[88]
      ADDB  91, 90, -128[88]
      ADDB  93, 92, 5B5AH[88]
      SUBB  91, 90, 89
      SUBB  92, 91, #5AH
      SUBB  93, 92, [91]
      SUBB  95, 94, 93[92]
      SUBB  95, 94, -128[92]
      SUBB  97, 96, 5F5EH[92]
      MULUB 95, 94, 93
      MULUB 96, 95, #5EH
      MULUB 97, 96, [95]
      MULUB 99, 98, 97[96]
      MULUB 99, 98, -128[96]
      MULUB 101, 100, 6362H[96]
      AND   98, 97
      AND   100, #6362H
      AND   100, [99]
      AND   102, 101[100]
      AND   102, -128[100]
      AND   104, 6766H[100]
      ADD   102, 101
      ADD   104, #6766H
      ADD   104, [103]
      ADD   106, 105[104]
      ADD   106, -128[104]
      ADD   108, 6B6AH[104]
      SUB   106, 105
      SUB   108, #6B6AH
      SUB   108, [107]
      SUB   110, 109[108]
      SUB   110, -128[108]
      SUB   112, 6F6EH[108]
      MULU  110, 109
      MULU  112, #6F6EH
      MULU  112, [111]
      MULU  114, 113[112]
      MULU  114, -128[112]
      MULU  116, 7372H[112]
      ANDB  114, 113
      ANDB  115, #72H
      ANDB  116, [115]
      ANDB  118, 117[116]
      ANDB  118, -128[116]
      ANDB  120, 7776H[116]
      ADDB  118, 117
      ADDB  119, #76H
      ADDB  120, [119]
      ADDB  122, 121[120]
      ADDB  122, -128[120]
      ADDB  124, 7B7AH[120]
      SUBB  122, 121
      SUBB  123, #7AH
      SUBB  124, [123]
      SUBB  126, 125[124]
      SUBB  126, -128[124]
      SUBB  128, 7F7EH[124]
      MULUB 126, 125
      MULUB 127, #7EH
      MULUB 128, [127]
      MULUB 130, -127[128]
      MULUB 130, 0[128]
      MULUB 132, 8382H[128]
      OR    130, 129
      OR    132, #8382H
      OR    132, [131]
      OR    134, -123[132]
      OR    134, 0[132]
      OR    136, 8786H[132]
      XOR   134, 133
      XOR   136, #8786H
      XOR   136, [135]
      XOR   138, -119[136]
      XOR   138, 0[136]
      XOR   140, 8B8AH[136]
      CMP   138, 137
      CMP   140, #8B8AH
      CMP   140, [139]
      CMP   142, -115[140]
      CMP   142, 0[140]
      CMP   144, 8F8EH[140]
      DIVU  142, 141
      DIVU  144, #8F8EH
      DIVU  144, [143]
      DIVU  146, -111[144]
      DIVU  146, 0[144]
      DIVU  148, 9392H[144]
      ORB   146, 145
      ORB   147, #92H
      ORB   148, [147]
      ORB   150, -107[148]
      ORB   150, 0[148]
      ORB   152, 9796H[148]
      XORB  150, 149
      XORB  151, #96H
      XORB  152, [151]
      XORB  154, -103[152]
      XORB  154, 0[152]
      XORB  156, 9B9AH[152]
      CMPB  154, 153
      CMPB  155, #9AH
      CMPB  156, [155]
      CMPB  158, -99[156]
      CMPB  158, 0[156]
      CMPB  160, 9F9EH[156]
      DIVUB 158, 157
      DIVUB 159, #9EH
      DIVUB 160, [159]
      DIVUB 162, -95[160]
      DIVUB 162, 0[160]
      DIVUB 164, 0A3A2H[160]
      LD    162, 161
      LD    164, #0A3A2H
      LD    164, [163]
      LD    166, -91[164]
      LD    166, 0[164]
      LD    168, 0A7A6H[164]
      ADDC  166, 165
      ADDC  168, #0A7A6H
      ADDC  168, [167]
      ADDC  170, -87[168]
      ADDC  170, 0[168]
      ADDC  172, 0ABAAH[168]
      SUBC  170, 169
      SUBC  172, #0ABAAH
      SUBC  172, [171]
      SUBC  174, -83[172]
      SUBC  174, 0[172]
      SUBC  176, 0AFAEH[172]
      LDBZE 174, 173
      LDBZE 175, #0AEH
      LDBZE 176, [175]
      LDBZE 178, -79[176]
      LDBZE 178, 0[176]
      LDBZE 180, 0B3B2H[176]
      LDB   178, 177
      LDB   179, #0B2H
      LDB   180, [179]
      LDB   182, -75[180]
      LDB   182, 0[180]
      LDB   184, 0B7B6H[180]
      ADDCB 182, 181
      ADDCB 183, #0B6H
      ADDCB 184, [183]
      ADDCB 186, -71[184]
      ADDCB 186, 0[184]
      ADDCB 188, 0BBBAH[184]
      SUBCB 186, 185
      SUBCB 187, #0BAH
      SUBCB 188, [187]
      SUBCB 190, -67[188]
      SUBCB 190, 0[188]
      SUBCB 192, 0BFBEH[188]
      LDBSE 190, 189
      LDBSE 191, #0BEH
      LDBSE 192, [191]
      LDBSE 194, -63[192]
      LDBSE 194, 0[192]
      LDBSE 196, 0C3C2H[192]
      ST    194, 193
      ST    196, [195]
      ST    198, -59[196]
      ST    198, 0[196]
      ST    200, 0C7C6H[196]
      STB   198, 197
      STB   200, [199]
      STB   202, -55[200]
      STB   202, 0[200]
      STB   204, 0CBCAH[200]
      PUSH  201
      PUSH  #0CBCAH
      PUSH  [203]
      PUSH  -51[204]
      PUSH  0[204]
      PUSH  0CFCEH[204]
      POP   205
      POP   [207]
      POP   -47[208]
      POP   0[208]
      POP   0D3D2H[208]
      JNST  $-47
      JNST  $
      JNST  $+1
      JNH   $-46
      JNH   $
      JNH   $+1
      JGT   $-45
      JGT   $
      JGT   $+1
      JNC   $-44
      JNC   $
      JNC   $+1
      JNVT  $-43
      JNVT  $
      JNVT  $+1
      JNV   $-42
      JNV   $
      JNV   $+1
      JGE   $-41
      JGE   $
      JGE   $+1
      JNE   $-40
      JNE   $
      JNE   $+1
      JST   $-39
      JST   $
      JST   $+1
      JH    $-38
      JH    $
      JH    $+1
      JLE   $-37
      JLE   $
      JLE   $+1
      JC    $-36
      JC    $
      JC    $+1
      JVT   $-35
      JVT   $
      JVT   $+1
      JV    $-34
      JV    $
      JV    $+1
      JLT   $-33
      JLT   $
      JLT   $+1
      JE    $-32
      JE    $
      JE    $+1
      DJNZ  225, $-30
      DJNZ  225, $
      DJNZ  225, $+1
      BR    [228]
      LJMP  $-1618H
      LJMP  $+00E8H
      LCALL $-0E10H
      LCALL $+00F0H
      RET
      PUSHF
      POPF
      TRAP
      CLRC
      SETC
      DI
      EI
      CLRVT
      NOP
      MUL   79, 78, 77
      MUL   81, 80, #4F4EH
      MUL   81, 80, [79]
      MUL   83, 82, 81[80]
      MUL   84, 83, 5251H[80]
      MULB  95, 94, 93
      MULB  96, 95, #5EH
      MULB  97, 96, [95]
      MULB  99, 98, 97[96]
      MULB  100, 99, 6261H[96]
      MUL   110, 109
      MUL   112, #6F6EH
      MUL   112, [111]
      MUL   114, 113[112]
      MUL   115, 7271H[112]
      MULB  126, 125
      MULB  127, #7EH
      MULB  128, [127]
      MULB  130, -127[128]
      MULB  131, 8281H[128]
      DIV   142, 141
      DIV   144, #8F8EH
      DIV   144, [143]
      DIV   146, -111[144]
      DIV   147, 9291H[144]
      DIVB  158, 157
      DIVB  159, #9EH
      DIVB  160, [159]
      DIVB  162, -95[160]
      DIVB  163, 0A2A1H[160]
      RST
