name: Arduino CI

on:
  push:
    branches:
      - main
      - devel
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - ".github/**"
      - "**/*.adoc"
      - "**/*.md"
      - "**/*.txt"
      - "library.*"
      - "**/*.asm"
      - "**/*.inc"
      - "**/*.hex"
      - "**/*.s19"
      - "**/*.s28"
  pull_request:

jobs:
  compile-examples:
    name: 'Compile for ${{matrix.board.name}}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - vendor: MightyCore
            arch: avr
            name: 1284
          - vendor: DxCore
            arch: megaavr
            name: avrda
          - vendor: teensy
            arch: avr
            name: teensy41
        include:
          - index: https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json
            board:
              vendor: MightyCore
          # - index: https://drazzy.com/package_drazzy.com_index.json
          - index: https://descartes.net/package_drazzy.com_index.json
            board:
              vendor: DxCore
          - index: https://www.pjrc.com/teensy/package_teensy_index.json
            board:
              vendor: teensy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          cli-version: "1.0.4"
          fqbn: ${{matrix.board.vendor}}:${{matrix.board.arch}}:${{matrix.board.name}}
          platforms: |
            - source-url: ${{matrix.index}}
              name: ${{matrix.board.vendor}}:${{matrix.board.arch}}
          sketch-paths: |
            - examples
          libraries: |
            - source-path: ./
            - name: libcli
              version: 1.3.0
