name: Arduino CI

on:
  push:
    branches:
      - main
      - devel
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - ".github/**"
      - "**/*.adoc"
      - "**/*.md"
      - "**/*.txt"
      - "library.*"
      - "**/*.asm"
      - "**/*.inc"
      - "**/*.hex"
      - "**/*.s19"
      - "**/*.s28"
  pull_request:

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:megaavr:nona4809
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile Example
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - examples
          libraries: |
            - source-path: ./
            - name: libcli
              version: 1.2.3
