name: PlatformIO CI

on:
  push:
    branches:
      - main
      - devel
    tags-ignore:
      - '*.*.*'
    paths-ignore:
      - ".github/**"
      - "**/*.adoc"
      - "**/*.md"
      - "**/*.txt"
      - "library.*"
      - "**/*.asm"
      - "**/*.inc"
      - "**/*.hex"
      - "**/*.s19"
      - "**/*.s28"
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - asm32000
          - cdp1802
          - dis32000
          - f3850
          - i8048
          - i8051
          - i8080
          - i8086
          - i8096
          - ins8060
          - ins8070
          - mc6800
          - mc68000
          - mc6809
          - mn1610
          - mos6502
          - scn2650
          - tlcs90
          - tms32010
          - tms9900
          - z8
          - z80
          - z8000

    steps:
      - uses: actions/checkout@v3
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install library dependency
        run: pio lib install libcli@1.3.0
      - name: Run PlatformIO
        run: pio ci --lib="." --board=ATmega644P --board=nano_every --board=nano_33_iot --board=pico
        env:
          PLATFORMIO_CI_SRC: ./examples/${{ matrix.arch }}/${{ matrix.arch }}.ino
