name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        prog: [ asm, dis ]
        arch:
          - motorola
          - intel
          - zilog
          - scmp
          - mos6502
          - cdp1802
          - tms32010
          - tms9900
          - i8086
          - mc68000
          - ns32000
          - z8000

    steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Install library dependency
        run: pio lib -g install libcli@1.1.1
      - name: Run PlatformIO
        run: pio ci --lib="." --board=sparkfun_promicro16 --board=nano_every --board=nano_33_iot
        env:
          PLATFORMIO_CI_SRC: ./examples/${{ matrix.prog }}_${{ matrix.arch }}/${{ matrix.prog }}_${{ matrix.arch }}.ino
